### ISSUE TITLE
ImageBitmap does not exist on Safari

### ISSUE THREAD

**Issue by Nekronik** [vladmandic/human#103]
**Issue Description**
From the logs, I see there is an error thrown when loading the library. These are from an iPhone using Safari.
![image](https://user-images.githubusercontent.com/7140454/114576898-da299200-9c7b-11eb-90e6-50002ba44ec8.png)

I suspect this is because [ImageBitmap](https://caniuse.com/mdn-api_imagebitmap) is not available in Safari.

**Steps to Reproduce**
Use the library with an iPhone

**Expected Behavior**
Should handle this class so no errors are thrown.

**Environment**

- Module version? 1.4.2
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Safari
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? iOS 14

**Comment by vladmandic** [comment]
damn....  
i don't have iphone or mac for testing right now, so i'll try to fix this blindly.  
i just published version 1.5.1, can you test?

**Comment by Nekronik** [comment]
I don't have any either, but I've just asked someone.
With `1.3.4` it did not work, but with `1.5.1` it does.
In the console, I get `1.5.0` when I request `https://cdn.jsdelivr.net/npm/@vladmandic/human@1.5.1/dist/human.js`. Is this ok?

**Comment by vladmandic** [comment]
Perfect!

And yes, that's ok - i bumped the tag after running the build, so build has a previous tag.
It will be corrected by itself in the next version, but no point of pushing update just because of that.
