### ISSUE TITLE
Unable to load json models in React app

### ISSUE THREAD

**Issue by roelandwyns** [vladmandic/human#104]
**Issue Description**

I am unable to load the json models in a React webapp. I get the following error: `Failed to parse model JSON of response from ../models/blazeface-back.json.` .

Human() is working (with config as well), and gives back the expected the result. When calling .detect(image) on human, it gives this error that it was unable to load the models. I tried overwriting the basepath etc, but that didn't seem to help either. 

**Steps to Reproduce**

Start a react app with typescript template. Add the package ( I used yarn ). I try to run the code to detect my face on an image I have of myself. I import with 
 `import Human from '@vladmandic/human';`
also tried different types of input like `import Human from '@vladmandic/human/dist/human.esm';`

**Expected Behavior**

Give some result of the detect method instead of an error on not being able to load the models.

**Environment

Tried different versions of the package, 1.4.1, 1.5.1, and also some older ones. Same issue.
Running in latest version of Chrome and Firefox.
Mac OS
Running with yarn react-scripts start 

**Additional**
https://gist.github.com/roelandwyns/95c2bd6b43f9b1a07bda6d1e9ea63ffc
![image](https://user-images.githubusercontent.com/17416198/115129176-f151e200-9fe3-11eb-9ca8-4ceffcb684c6.png)

Thanks in advance! Awesome library, would love to integrate it in a react app :)

**Comment by vladmandic** [comment]
One quick suggestion - can you try placing models in a folder below your server root, not above it? http requests deal poorly with `..` in paths. so your `modelBasePath = 'models/'`

Second, check the network tab of your browser inspector:
- what is the http status code for the `blazeface-back.json`
- what is it's MIME type (I've seen cases where misconfigured web server returns incorrect MIME type so client doesn't know what it received)
- can you actually see a JSON response when you select that network request in browser?
- copy the URL from that network request and try to access it manually in a new browser tab - can you actually download the file correctly?

**Comment by roelandwyns** [comment]
Thank you for the quick response!

I tried the modelBasePath changing (already tried it with the absolute paths as well).

HTTP status code is 200 and content type is text/html; charset=UTF-8 .
On the third thing in the network tab, I am unable to see the json response of the file in the browser, in the response it gives back my index.html from my react-app, which is probably wrong. -> same goes for copying that url, it gives me back the react app instead of the json file. Will look deeper into it this week! 

Thanks again for the quick reaction, I will try to check what went wrong with it this week! :)

**Comment by vladmandic** [comment]
definitely a local web server issue.

btw, you can try using a local web server that ships with `human` instead: `npm run dev`

**Comment by vladmandic** [comment]
any update? i can keep the issue open for reference couple of days, but this is not a library issue.

**Comment by roelandwyns** [comment]
You can close the issue, I will look deeper into it. But indeed not a library issue!

**Comment by stefanCojocariu** [comment]
any update on this? i have the same issue

**Comment by vladmandic** [comment]
@stefanCojocariu what is the web server you're using? how is it configures? and did you try using built-in dev web server that ships with `human` library?

**Comment by stefanCojocariu** [comment]
I have a reactjs basic project, that's started with react-scripts start. It's running on localhost. I placed the models in src folder and modified the modelBasePath to 'models', and the get request url is, for example: http://localhost:1234/models/blazeface-back.json.

**Comment by stefanCojocariu** [comment]
Solved it just now, haha. 
So the reactjs project has a public folder for serving static files, added the models folder there and modified the value of modelBasePath to 'models'. I think that will help you, too, @roelandwyns.

Thank you for the quick reply and help!

**Comment by roelandwyns** [comment]
@stefanCojocariu oh that makes sense indeed! :) Didn't have time yet to check in the evenings this week, but that works perfectly! Awesome, thank you!
