### ISSUE TITLE
How can i pass image from uri at node.js

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#109]
Couldn't find how to pass image to human.detect from uri, i prepared a function like in demo but doesn' accept as valid input;

`let url = "https://firebasestorage.googleapis.com/v0/b/zetform-63ea7.appspot.com/o/organizations%2FHrJUmJjOAAgtmhiI4PK6%2Fmonitorings%2FGZoPjyFTjua0iWYQq2Ym%2Ftestinstances%2Fk1ULsrMNJU3ZUtk7GcJe%2Fphotos%2F1_2021-01-17%2010%3A15%3A48.jpg?alt=media&token=22024c06-a99e-4290-b59c-6a2da1b0786b";`

```
    async function urlImage(url: string): Promise<Canvas> {
        const img = await canvas.loadImage(url);
        const c: Canvas = canvas.createCanvas(img.width, img.height);
        const ctx = c.getContext('2d');
        ctx.drawImage(img, 0, 0, img.width, img.height);
        return c;
    }

```
const tempCanvas : Canvas  = await urlImage(url);
const result: LX.vladHuman.Result = await human.detect( tempCanvas , myConfig) as LX.vladHuman.Result;
```


My real question is to load image from uri and pass to detect function in healty way, there is a good example in demo but it loads images from disc

Best.

**Comment by vladmandic** [comment]
fair question, i've just added example to `demo/node.js`: <https://github.com/vladmandic/human/blob/main/demo/node.js#L51>  

it can be done using `canvas` library as well, i just like this as there are no external dependencies other than `fetch`

**Comment by vladmandic** [comment]
as question is answered, i'm closing this issue.

**Comment by okeoke85** [comment]
Sure it is solved thank you
