### ISSUE TITLE
Webcam image mirrored

### ISSUE THREAD

**Issue by Maiorquino** [vladmandic/human#110]
How I remove the webcam video mirror ?
I have tried using css transform: scaleX(-1) but not effect

**Comment by vladmandic** [comment]
css transform works when displaying, so when video is read, it has no effect.
you can either:
- draw video to canvas in mirror shape and then pass that inverted canvas to human as input
- perform css transform on output canvas
   in which case either draw the original video with css transform as well or don't even draw it (keep video element hidden)  
   and draw everything using canvas returned by `human`

**Comment by Maiorquino** [comment]
I tried to pass to canvas and then to human.detect and the result is still mirrored
and for example, if I was looking to left in the result gesture says im looking to right

**Comment by vladmandic** [comment]
i've just added new feature, `config.filter.flip = true|false`  
and main branch is updated on `github` (new package will be published on `npmjs` later this week)

in case you're curious, this is the code in `src/image/image.ts`:

```js
if (!config.filter.flip) {
  ctx.drawImage(input, 0, 0, originalWidth, originalHeight);
} else {
  ctx.translate(originalWidth, 0);
  ctx.scale(-1, 1);
  ctx.drawImage(input, 0, 0, originalWidth, originalHeight);
  ctx.setTransform(1, 0, 0, 1, 0, 0);
}
```

btw, there was a bug in gestures where face left/right was opposite of what iris left/right were saying - i've fixed that as well

**Comment by Maiorquino** [comment]
Very well!
congratulations for the quick return and for the excellent project!
I hope that I’m more familiar with the tool, I can also contribute
