### ISSUE TITLE
I get this error in some images

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#111]
I get this error when i call human.detect, not all images but some, i couldnt find anything to solve these, it is probably about conversition setting of image, conversiyon function and image are below; also logged final tensor data which is the parameter of human.detect(tensor)

Function;

```
export async function urlImageHuman(url: string): Promise<undefined | any> {
    const fetch = require("node-fetch");
    const res = await fetch(url);
    if (res && res.ok) {
        let buffer = await res.buffer();
        if (!buffer) {
            return undefined;
        }
        let decoded = human.tf.node.decodeImage(buffer);
        let casted = decoded.toFloat();
        let tensor = casted.expandDims(0);
        decoded.dispose();
        casted.dispose();
        return tensor;
    }
    return undefined;
}
```

Image;
![8_2021-04-20 17_57_05 (1)](https://user-images.githubusercontent.com/15729538/115548184-dca96e80-a2af-11eb-85fd-74fccbc08f4c.jpg)

Tensor : 

{"kept":false,"isDisposedInternal":false,"shape":[1,480,640,4],"dtype":"float32","size":1228800,"strides":[1228800,2560,4],"dataId":{},"id":10762,"rankType":"4","scopeId":9028}

Error;

>  (node:18860) UnhandledPromiseRejectionWarning: Error: Human: Input tensor shape must be [1, height, width, 3] and instead was 1,480,640,4
>      at j1 (C:\Development\hemsor\functions\node_modules\@vladmandic\human\dist\human.node.js:15:822)
>      at C:\Development\hemsor\functions\node_modules\@vladmandic\human\dist\human.node.js:734:8060
>      at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by vladmandic** [comment]
your image is *RGBA* (it has *alpha* channel) and tensorflow requires pure *RGB* input  
try something like this:  
(sorry for any typos, i wrote it from head without testing)

```js
const tensor = tf.tidy(() => {
  let decoded = human.tf.node.decodeImage(buffer);
  let casted = decoded.toFloat();
  let res;
  if (tensor.shape[3] !== 3) {
    const channels = tf.split(tensor, 4, 2); // split rgba to channels
    const rgb = tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb and ignore alpha
    res = tf.reshape(rgb, [1, decoded.shape[0], decoded.shape[1], 3]); // move extra dim from the end of tensor and use it as batch number instead
  } else {
    res = casted.expandDims(0); // just add batch number
  }
  return res; 
})
```

**Comment by vladmandic** [comment]
@okeoke85 any updates on this issue?

**Comment by okeoke85** [comment]
thanks to your help seems to be working
