### ISSUE TITLE
Face match with vlad.faceapi, wrong data format

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#112]
When trying to match two detecion data i got this error, error baseImage data and imageData are below;

Error;

```
Error: FaceRecognizer.constructor - expected inputs to be of type LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array | Array<LabeledFaceDescriptors | WithFaceDescriptor<any> | Float32Array>
    at C:\Development\hemsor\functions\node_modules\@vladmandic\face-api\dist\face-api.node.js:4481:13
    at Array.map (<anonymous>)
    at new FaceMatcher (C:\Development\hemsor\functions\node_modules\@vladmandic\face-api\dist\face-api.node.js:4471:43)
    at Object.<anonymous> (C:\Development\hemsor\functions\lib\util\vlad-face-api.util.js:19:16)
    at Generator.next (<anonymous>)
    at C:\Development\hemsor\functions\lib\util\vlad-face-api.util.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Development\hemsor\functions\lib\util\vlad-face-api.util.js:4:12)
    at Object.getFaceMatcher (C:\Development\hemsor\functions\lib\util\vlad-face-api.util.js:18:12)
    at C:\Development\hemsor\functions\lib\util\ai-util.js:109:71

```
>  `Base image detection : {"detection":{"_imageDims":{"_width":640,"_height":480},"_score":0.9686928987503052,"_classScore":0.9686928987503052,"_className":"","_box":{"_x":454.9592590332031,"_y":219.2596435546875,"_width":100.70419311523438,"_height":121.38046264648436}},"landmarks":{"_imgDims":{"_width":100,"_height":121},"_shift":{"_x":454.9592590332031,"_y":219.2596435546875},"_positions":[{"_x":457.7955788373947,"_y":274.79810521006584},{"_x":455.8875436335802,"_y":286.5654146671295},{"_x":456.68051674962044,"_y":298.1366723179817},{"_x":458.96097369492054,"_y":308.63758021593094},{"_x":462.24460288882256,"_y":320.30693769454956},{"_x":465.9631198644638,"_y":328.66408812999725},{"_x":469.84499603509903,"_y":333.61204957962036},{"_x":474.94090408086777,"_y":337.5555011034012},{"_x":487.29751765727997,"_y":340.2047301530838},{"_x":502.3620820045471,"_y":337.2347257733345},{"_x":516.916069984436,"_y":333.31238424777985},{"_x":528.8288867473602,"_y":328.38736468553543},{"_x":539.1570425033569,"_y":319.2793632745743},{"_x":546.2026572227478,"_y":307.60420721769333},{"_x":549.878523349762,"_y":295.52019369602203},{"_x":552.8075134754181,"_y":282.6771650314331},{"_x":554.6635127067566,"_y":269.4297107756138},{"_x":456.71929236501455,"_y":258.5899069905281},{"_x":458.2994854450226,"_y":253.5179107785225},{"_x":462.4326793849468,"_y":250.93901473283768},{"_x":467.3671631515026,"_y":250.55087059736252},{"_x":472.56822645664215,"_y":252.00682219862938},{"_x":493.5812121629715,"_y":251.0898426771164},{"_x":500.124836564064,"_y":248.90755784511566},{"_x":508.66381883621216,"_y":248.119802236557},{"_x":518.5417628288269,"_y":250.4396229982376},{"_x":527.1569406986237,"_y":254.91037011146545},{"_x":481.46510779857635,"_y":264.9688262939453},{"_x":478.3727025985718,"_y":272.6963405609131},{"_x":474.8985803127289,"_y":279.8749299645424},{"_x":473.7836158275604,"_y":287.18489611148834},{"_x":474.41680341959,"_y":294.45778453350067},{"_x":476.453555226326,"_y":295.812755048275},{"_x":479.88436728715897,"_y":296.3741569519043},{"_x":485.24633407592773,"_y":294.77281177043915},{"_x":489.85130846500397,"_y":293.72017508745193},{"_x":463.71563509106636,"_y":267.46946316957474},{"_x":465.22086694836617,"_y":264.9259752333164},{"_x":470.7351824641228,"_y":264.15974792838097},{"_x":476.72491282224655,"_y":266.8614670932293},{"_x":471.60392463207245,"_y":269.0662105977535},{"_x":466.11671432852745,"_y":269.2822581231594},{"_x":499.16064500808716,"_y":265.42910647392273},{"_x":503.96093785762787,"_y":261.68926510214806},{"_x":510.0673234462738,"_y":261.6694568991661},{"_x":516.157124042511,"_y":264.71637177467346},{"_x":510.39352774620056,"_y":266.95047959685326},{"_x":503.7195062637329,"_y":266.5281714498997},{"_x":470.3068068623543,"_y":312.33296221494675},{"_x":472.18376606702805,"_y":308.0835347175598},{"_x":477.0624226331711,"_y":305.3708242177963},{"_x":481.02106511592865,"_y":305.8787118792534},{"_x":484.65346455574036,"_y":304.50840109586716},{"_x":495.04682183265686,"_y":306.8852195739746},{"_x":505.4706907272339,"_y":309.66006284952164},{"_x":494.9705547094345,"_y":312.89019548892975},{"_x":487.4601876735687,"_y":315.1039686203003},{"_x":481.3606923818588,"_y":315.98395335674286},{"_x":476.9816866517067,"_y":315.8076087832451},{"_x":472.9878506064415,"_y":314.95839834213257},{"_x":471.2059488892555,"_y":312.17052268981934},{"_x":477.1176925301552,"_y":309.77621471881866},{"_x":481.7724800109863,"_y":309.25895845890045},{"_x":487.95234620571136,"_y":309.3286928534508},{"_x":503.8042551279068,"_y":309.58249604701996},{"_x":487.6369780302048,"_y":309.75305646657944},{"_x":481.8918204307556,"_y":310.40967333316803},{"_x":477.4653887748718,"_y":310.478051841259}]},"unshiftedLandmarks":{"_imgDims":{"_width":100,"_height":121},"_shift":{"_x":0,"_y":0},"_positions":[{"_x":2.8363198041915894,"_y":55.53846165537834},{"_x":0.9282846003770828,"_y":67.30577111244202},{"_x":1.7212577164173126,"_y":78.87702876329422},{"_x":4.001714661717415,"_y":89.37793666124344},{"_x":7.2853438556194305,"_y":101.04729413986206},{"_x":11.003860831260681,"_y":109.40444457530975},{"_x":14.885737001895905,"_y":114.35240602493286},{"_x":19.981645047664642,"_y":118.29585754871368},{"_x":32.33825862407684,"_y":120.9450865983963},{"_x":47.402822971343994,"_y":117.975082218647},{"_x":61.95681095123291,"_y":114.05274069309235},{"_x":73.8696277141571,"_y":109.12772113084793},{"_x":84.19778347015381,"_y":100.01971971988678},{"_x":91.24339818954468,"_y":88.34456366300583},{"_x":94.91926431655884,"_y":76.26055014133453},{"_x":97.84825444221497,"_y":63.417521476745605},{"_x":99.70425367355347,"_y":50.170067220926285},{"_x":1.760033331811428,"_y":39.33026343584061},{"_x":3.340226411819458,"_y":34.25826722383499},{"_x":7.473420351743698,"_y":31.679371178150177},{"_x":12.407904118299484,"_y":31.29122704267502},{"_x":17.608967423439026,"_y":32.74717864394188},{"_x":38.62195312976837,"_y":31.830199122428894},{"_x":45.1655775308609,"_y":29.64791429042816},{"_x":53.70455980300903,"_y":28.860158681869507},{"_x":63.58250379562378,"_y":31.17997944355011},{"_x":72.19768166542053,"_y":35.650726556777954},{"_x":26.50584876537323,"_y":45.70918273925781},{"_x":23.413443565368652,"_y":53.436697006225586},{"_x":19.939321279525757,"_y":60.61528640985489},{"_x":18.8243567943573,"_y":67.92525255680084},{"_x":19.45754438638687,"_y":75.19814097881317},{"_x":21.494296193122864,"_y":76.5531114935875},{"_x":24.92510825395584,"_y":77.1145133972168},{"_x":30.28707504272461,"_y":75.51316821575165},{"_x":34.89204943180084,"_y":74.46053153276443},{"_x":8.756376057863235,"_y":48.20981961488724},{"_x":10.26160791516304,"_y":45.66633167862892},{"_x":15.775923430919647,"_y":44.900104373693466},{"_x":21.765653789043427,"_y":47.601823538541794},{"_x":16.644665598869324,"_y":49.806567043066025},{"_x":11.157455295324326,"_y":50.02261456847191},{"_x":44.20138597488403,"_y":46.16946291923523},{"_x":49.001678824424744,"_y":42.429621547460556},{"_x":55.10806441307068,"_y":42.40981334447861},{"_x":61.19786500930786,"_y":45.45672821998596},{"_x":55.43426871299744,"_y":47.690836042165756},{"_x":48.760247230529785,"_y":47.26852789521217},{"_x":15.347547829151154,"_y":93.07331866025925},{"_x":17.22450703382492,"_y":88.82389116287231},{"_x":22.103163599967957,"_y":86.11118066310883},{"_x":26.061806082725525,"_y":86.61906832456589},{"_x":29.69420552253723,"_y":85.24875754117966},{"_x":40.087562799453735,"_y":87.62557601928711},{"_x":50.51143169403076,"_y":90.40041929483414},{"_x":40.011295676231384,"_y":93.63055193424225},{"_x":32.5009286403656,"_y":95.8443250656128},{"_x":26.4014333486557,"_y":96.72430980205536},{"_x":22.02242761850357,"_y":96.54796522855759},{"_x":18.028591573238373,"_y":95.69875478744507},{"_x":16.2466898560524,"_y":92.91087913513184},{"_x":22.158433496952057,"_y":90.51657116413116},{"_x":26.813220977783203,"_y":89.99931490421295},{"_x":32.99308717250824,"_y":90.06904929876328},{"_x":48.844996094703674,"_y":90.32285249233246},{"_x":32.67771899700165,"_y":90.49341291189194},{"_x":26.93256139755249,"_y":91.15002977848053},{"_x":22.5061297416687,"_y":91.2184082865715}]},"alignedRect":{"_imageDims":{"_width":640,"_height":480},"_score":0.9686928987503052,"_classScore":0.9686928987503052,"_className":"","_box":{"_x":446.00994672626257,"_y":238.91130944490433,"_width":118.53116288781166,"_height":110.50191349983216}},"angle":{"roll":0.05245019508173883,"pitch":0.8317519703872617,"yaw":-0.19297368625573164},"expressions":{"neutral":0.00735729094594717,"happy":0.9922767281532288,"sad":0.00025446360814385116,"angry":0.00000297511974167719,"fearful":1.666869864358489e-9,"disgusted":0.00010860323527595028,"surprised":1.277310346381455e-8}}`

`>  Image detection : {"detection":{"_imageDims":{"_width":640,"_height":480},"_score":0.9686928987503052,"_classScore":0.9686928987503052,"_className":"","_box":{"_x":454.9592590332031,"_y":219.2596435546875,"_width":100.70419311523438,"_height":121.38046264648436}},"landmarks":{"_imgDims":{"_width":100,"_height":121},"_shift":{"_x":454.9592590332031,"_y":219.2596435546875},"_positions":[{"_x":457.7955788373947,"_y":274.79810521006584},{"_x":455.8875436335802,"_y":286.5654146671295},{"_x":456.68051674962044,"_y":298.1366723179817},{"_x":458.96097369492054,"_y":308.63758021593094},{"_x":462.24460288882256,"_y":320.30693769454956},{"_x":465.9631198644638,"_y":328.66408812999725},{"_x":469.84499603509903,"_y":333.61204957962036},{"_x":474.94090408086777,"_y":337.5555011034012},{"_x":487.29751765727997,"_y":340.2047301530838},{"_x":502.3620820045471,"_y":337.2347257733345},{"_x":516.916069984436,"_y":333.31238424777985},{"_x":528.8288867473602,"_y":328.38736468553543},{"_x":539.1570425033569,"_y":319.2793632745743},{"_x":546.2026572227478,"_y":307.60420721769333},{"_x":549.878523349762,"_y":295.52019369602203},{"_x":552.8075134754181,"_y":282.6771650314331},{"_x":554.6635127067566,"_y":269.4297107756138},{"_x":456.71929236501455,"_y":258.5899069905281},{"_x":458.2994854450226,"_y":253.5179107785225},{"_x":462.4326793849468,"_y":250.93901473283768},{"_x":467.3671631515026,"_y":250.55087059736252},{"_x":472.56822645664215,"_y":252.00682219862938},{"_x":493.5812121629715,"_y":251.0898426771164},{"_x":500.124836564064,"_y":248.90755784511566},{"_x":508.66381883621216,"_y":248.119802236557},{"_x":518.5417628288269,"_y":250.4396229982376},{"_x":527.1569406986237,"_y":254.91037011146545},{"_x":481.46510779857635,"_y":264.9688262939453},{"_x":478.3727025985718,"_y":272.6963405609131},{"_x":474.8985803127289,"_y":279.8749299645424},{"_x":473.7836158275604,"_y":287.18489611148834},{"_x":474.41680341959,"_y":294.45778453350067},{"_x":476.453555226326,"_y":295.812755048275},{"_x":479.88436728715897,"_y":296.3741569519043},{"_x":485.24633407592773,"_y":294.77281177043915},{"_x":489.85130846500397,"_y":293.72017508745193},{"_x":463.71563509106636,"_y":267.46946316957474},{"_x":465.22086694836617,"_y":264.9259752333164},{"_x":470.7351824641228,"_y":264.15974792838097},{"_x":476.72491282224655,"_y":266.8614670932293},{"_x":471.60392463207245,"_y":269.0662105977535},{"_x":466.11671432852745,"_y":269.2822581231594},{"_x":499.16064500808716,"_y":265.42910647392273},{"_x":503.96093785762787,"_y":261.68926510214806},{"_x":510.0673234462738,"_y":261.6694568991661},{"_x":516.157124042511,"_y":264.71637177467346},{"_x":510.39352774620056,"_y":266.95047959685326},{"_x":503.7195062637329,"_y":266.5281714498997},{"_x":470.3068068623543,"_y":312.33296221494675},{"_x":472.18376606702805,"_y":308.0835347175598},{"_x":477.0624226331711,"_y":305.3708242177963},{"_x":481.02106511592865,"_y":305.8787118792534},{"_x":484.65346455574036,"_y":304.50840109586716},{"_x":495.04682183265686,"_y":306.8852195739746},{"_x":505.4706907272339,"_y":309.66006284952164},{"_x":494.9705547094345,"_y":312.89019548892975},{"_x":487.4601876735687,"_y":315.1039686203003},{"_x":481.3606923818588,"_y":315.98395335674286},{"_x":476.9816866517067,"_y":315.8076087832451},{"_x":472.9878506064415,"_y":314.95839834213257},{"_x":471.2059488892555,"_y":312.17052268981934},{"_x":477.1176925301552,"_y":309.77621471881866},{"_x":481.7724800109863,"_y":309.25895845890045},{"_x":487.95234620571136,"_y":309.3286928534508},{"_x":503.8042551279068,"_y":309.58249604701996},{"_x":487.6369780302048,"_y":309.75305646657944},{"_x":481.8918204307556,"_y":310.40967333316803},{"_x":477.4653887748718,"_y":310.478051841259}]},"unshiftedLandmarks":{"_imgDims":{"_width":100,"_height":121},"_shift":{"_x":0,"_y":0},"_positions":[{"_x":2.8363198041915894,"_y":55.53846165537834},{"_x":0.9282846003770828,"_y":67.30577111244202},{"_x":1.7212577164173126,"_y":78.87702876329422},{"_x":4.001714661717415,"_y":89.37793666124344},{"_x":7.2853438556194305,"_y":101.04729413986206},{"_x":11.003860831260681,"_y":109.40444457530975},{"_x":14.885737001895905,"_y":114.35240602493286},{"_x":19.981645047664642,"_y":118.29585754871368},{"_x":32.33825862407684,"_y":120.9450865983963},{"_x":47.402822971343994,"_y":117.975082218647},{"_x":61.95681095123291,"_y":114.05274069309235},{"_x":73.8696277141571,"_y":109.12772113084793},{"_x":84.19778347015381,"_y":100.01971971988678},{"_x":91.24339818954468,"_y":88.34456366300583},{"_x":94.91926431655884,"_y":76.26055014133453},{"_x":97.84825444221497,"_y":63.417521476745605},{"_x":99.70425367355347,"_y":50.170067220926285},{"_x":1.760033331811428,"_y":39.33026343584061},{"_x":3.340226411819458,"_y":34.25826722383499},{"_x":7.473420351743698,"_y":31.679371178150177},{"_x":12.407904118299484,"_y":31.29122704267502},{"_x":17.608967423439026,"_y":32.74717864394188},{"_x":38.62195312976837,"_y":31.830199122428894},{"_x":45.1655775308609,"_y":29.64791429042816},{"_x":53.70455980300903,"_y":28.860158681869507},{"_x":63.58250379562378,"_y":31.17997944355011},{"_x":72.19768166542053,"_y":35.650726556777954},{"_x":26.50584876537323,"_y":45.70918273925781},{"_x":23.413443565368652,"_y":53.436697006225586},{"_x":19.939321279525757,"_y":60.61528640985489},{"_x":18.8243567943573,"_y":67.92525255680084},{"_x":19.45754438638687,"_y":75.19814097881317},{"_x":21.494296193122864,"_y":76.5531114935875},{"_x":24.92510825395584,"_y":77.1145133972168},{"_x":30.28707504272461,"_y":75.51316821575165},{"_x":34.89204943180084,"_y":74.46053153276443},{"_x":8.756376057863235,"_y":48.20981961488724},{"_x":10.26160791516304,"_y":45.66633167862892},{"_x":15.775923430919647,"_y":44.900104373693466},{"_x":21.765653789043427,"_y":47.601823538541794},{"_x":16.644665598869324,"_y":49.806567043066025},{"_x":11.157455295324326,"_y":50.02261456847191},{"_x":44.20138597488403,"_y":46.16946291923523},{"_x":49.001678824424744,"_y":42.429621547460556},{"_x":55.10806441307068,"_y":42.40981334447861},{"_x":61.19786500930786,"_y":45.45672821998596},{"_x":55.43426871299744,"_y":47.690836042165756},{"_x":48.760247230529785,"_y":47.26852789521217},{"_x":15.347547829151154,"_y":93.07331866025925},{"_x":17.22450703382492,"_y":88.82389116287231},{"_x":22.103163599967957,"_y":86.11118066310883},{"_x":26.061806082725525,"_y":86.61906832456589},{"_x":29.69420552253723,"_y":85.24875754117966},{"_x":40.087562799453735,"_y":87.62557601928711},{"_x":50.51143169403076,"_y":90.40041929483414},{"_x":40.011295676231384,"_y":93.63055193424225},{"_x":32.5009286403656,"_y":95.8443250656128},{"_x":26.4014333486557,"_y":96.72430980205536},{"_x":22.02242761850357,"_y":96.54796522855759},{"_x":18.028591573238373,"_y":95.69875478744507},{"_x":16.2466898560524,"_y":92.91087913513184},{"_x":22.158433496952057,"_y":90.51657116413116},{"_x":26.813220977783203,"_y":89.99931490421295},{"_x":32.99308717250824,"_y":90.06904929876328},{"_x":48.844996094703674,"_y":90.32285249233246},{"_x":32.67771899700165,"_y":90.49341291189194},{"_x":26.93256139755249,"_y":91.15002977848053},{"_x":22.5061297416687,"_y":91.2184082865715}]},"alignedRect":{"_imageDims":{"_width":640,"_height":480},"_score":0.9686928987503052,"_classScore":0.9686928987503052,"_className":"","_box":{"_x":446.00994672626257,"_y":238.91130944490433,"_width":118.53116288781166,"_height":110.50191349983216}},"angle":{"roll":0.05245019508173883,"pitch":0.8317519703872617,"yaw":-0.19297368625573164},"expressions":{"neutral":0.00735729094594717,"happy":0.9922767281532288,"sad":0.00025446360814385116,"angry":0.00000297511974167719,"fearful":1.666869864358489e-9,"disgusted":0.00010860323527595028,"surprised":1.277310346381455e-8}}`

**Comment by vladmandic** [comment]
I assume this issue is for <https://github.com/vladmandic/face-api>, not <https://github.com/vladmandic/human> ?  

Can you create it there?

Also, can you post a short code snippet?

**Comment by okeoke85** [comment]
so sorry i will switch there

**Comment by neckaros** [comment]
You have two repo for face detection / recognition ? What are the differences / main incentive to use one over the other please?
