### ISSUE TITLE
Facemesh performance drop in latest vesion of human

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#114]
I tried your latest version of `human` (v1.7.0), and I noticed a significant framerate drop when using face detection. I checked the console, and I noticed that there was the 'disabling video optimization' message frequently popping up. It seems in your recent updates you have added the routine in `human.ts` to check and disable video optimization for inputs of type image. However, you may have missed the consideration that in web worker (my case), the input is practically always an image (video can't be transferred from main thread), even though the nature of the image content is still a continuous animation.

**Comment by vladmandic** [comment]
definitely a bug - and great diagnostic on your side.

i still want to leave the feature to disable optimizations for type image, but i think it's safe to disable the feature if `human` is running inside worker (assumption being advanced user knows what he's doing)

btw, how are you passing image to worker?
ideally, it's done by reference using ImageData, so there is no data copy and only ownership change:
```js
  worker.postMessage({ image: image.data.buffer, width: canvas.width, height: canvas.height, userConfig }, [image.data.buffer]);
```

**Comment by vladmandic** [comment]
i have version 1.7 queued in main branch with quite some large changed  
and this bug caused release slightly ahead of time  

please check major changes before upgrading:

- enable cross origin isolation in dev server
  to meet future chrome requirement
- complete rewrite of posenet decoder
  very slight performance drop on maxDetections=1 is possible, but precision is much higher
- replaced posenet model with higher resolution one
- remove experimental efficientpose
  too slow, working on blazepose instead
- remove from config face.age, face.gender, face.embeddin
  replaced by unified face.description several versions ago

**Comment by ButzYung** [comment]
1.71 works. Thanks for the quick fix.

I see why you want the routine to check the need for video optimization, since `videoOptimized` is on by default, and the autocheck is convenient for casual users. I could imagine the possibility of passing imagedata to `human` even for video in main thread, but this should be rare I suppose.

Yeah I am passing the image buffer's "ownership" to the worker, basically the same as your example.

I noticed that you rewrote the posenet decoder. In fact it's the reason why I want to try the upgraded version. And yes the precision is noticeably much higher. GJ on this.

**Comment by vladmandic** [comment]
> I see why you want the routine to check the need for video optimization, since videoOptimized is on by default, and the autocheck is convenient for casual users.

Exactly.

> I could imagine the possibility of passing imagedata to human even for video in main thread, but this should be rare I suppose.

Very rare. Typically, if a user passes something other than `Video` itself, its a `Canvas` snapshot of a video - that's why autocheck skips `Canvas` type (and its variations).

> And yes the precision is noticeably much higher. GJ on this.

Glad to hear!

> 1.71 works. Thanks for the quick fix.

Closing as resolved :)
