### ISSUE TITLE
Replacing webcam to camera

### ISSUE THREAD

**Issue by lghasemzadeh** [vladmandic/human#116]
Hello Vladimir,

I want to read streams from a camera not webcam? 
How can I do it?
I just simply changes all getVideoTracks()[0] to getVideoTracks()[1] in the index.js and face3d.js, but I got the 'Exception Error' on the screen.
Actually after allowing the camera to capture, the camera's lights get on (like what happen with webcam) and it seems camera is ready but not stream!

Thx

**Comment by lghasemzadeh** [comment]
It was connected without changing anything. I just changed it to the original getVideoTracks()[0] and run again and it worked with the my external camera.
Here I want to know what if I have several cameras and webcams connected to my laptop, what is the priority or how can I select a specific one to get streams from?

**Comment by vladmandic** [comment]
before call to `track = stream.getVideoTracks` there is a call to `stream = navigator.mediaDevices.getUserMedia(constraints)` which returns all streams that fit given constraints - and if you want to select a specific camera, you select contraints that match that camera.

check out specs at <https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia>

**Comment by lghasemzadeh** [comment]
Actually there are two cameras (s and ca), both of them are recognized by the algorithm and they appear in the permission pop-up but for one of them (ca) I receive error of 'CAMERA ERROR: STARTING VİDEO FAILED'. what is the reason? How can I fix it? both cameras are very similar in characteristics and same brand.
![photo5866404720921392852](https://user-images.githubusercontent.com/36885164/119570607-024afb80-bdb9-11eb-985d-449d14f4c205.jpg)

**Comment by vladmandic** [comment]
How are you accessing second camera?

Also, can you open browser inspector, there should be a more detailed error noted there.
(human library logs to browser console in more details)

**Comment by lghasemzadeh** [comment]
I do nothing, as soon as I connect the S camera via usb to the laptop it will be recognized by the algorithm and will be in the list of devices it the pop-up permission. I select it and the algorithm starts getting streams from the camera. but it is not true for the other camera, I don't know why?
![Screenshot from 2021-05-26 08-44-51](https://user-images.githubusercontent.com/36885164/119608731-216c7c00-bdff-11eb-96ed-589c51ad57d3.png)

**Comment by vladmandic** [comment]
it's not *algorithm* that picks up multiple cameras, it's the browser.  
demo simply asks browser 'give me camera that fits constraints' and since default constraints is basically anything, browser gives it full list.  
you picking camera in the browser pulldown list doesn't mean you're selecting it, algorithm will still try to use default (first one) if there is no more specific constrait.  
so you *select* second camera and that means nothing, it will still try to access first.  

what you should do is list all cameras programatically and then choose which one to use.  
i might be able to do it with a dynamic selector, but i don't have multiple webcams available, so cannot test anything.  

for example, this will list all cameras:
```js
const devices = await navigator.mediaDevices.enumerateDevices()
for (const device of devices) console.log('kind:', device.kind, 'label:', device.label, 'id:',device.deviceId);
```

and then in `index.js` modify camera constraints to explicitly choose which one to use:
```
const selectedCameraId = 'xxxxxxxxx'; // some camera id that you got from full list
const constraints = {
  audio: false,
  video: {
    facingMode: ui.facing ? 'user' : 'environment',
    resizeMode: ui.crop ? 'crop-and-scale' : 'none'
    deviceId: selectedCameraId, }
  },
};
```

**Comment by vladmandic** [comment]
i've added some additional messages to function `setupCamera()` in `demo/index.js`, new code is on *github* main branch:

it should log something like this to browser console on startup:

```log
status setting up camera
enumerated devices:
  kind:audioinput label: id:
  kind:videoinput label:HP Wide Vision FHD Camera (0408:5251) id:6794499e046cf4aebf41cfeb7d1ef48a17bd65f72bafb55f3c0b06405d3d487b
  kind:audiooutput label: id:
enumerated viable tracks: 1
  video: HP Wide Vision FHD Camera (0408:5251)
selected camera: HP Wide Vision FHD Camera (0408:5251) id: 6794499e046cf4aebf41cfeb7d1ef48a17bd65f72bafb55f3c0b06405d3d487b
```
