### ISSUE TITLE
Does it support React Native?

### ISSUE THREAD

**Issue by MadCoderme** [vladmandic/human#117]
I have been finding a suitable face analysis api in js for a while. I checked `face-api.js` and it seems like that is not supported in react native yet.

Is this library supported in react native?

**Comment by vladmandic** [comment]
I don't currently test for react-native, but it is on my to-do list  
In theory, it should work and I'm willing to help with any issues that may arise  

The key is to use `nobundle` flavor of `human` library and import `tfjs-react-native` manually before loading `human`, that way it can bind to it  

Also, react-native does not have native DOM elements, so you must prepare input before passing it to processing as a tensor (that part is not difficult and it's already well documented)

**Comment by MadCoderme** [comment]
Sounds cool!

**Comment by vladmandic** [comment]
i'm closing this issue as it was a general question only, but if there are any specific issues during implementation please report them and they will be looked at.

**Comment by danyhiol** [comment]
I am trying to use this library on expo (react native). But can't really figure out how to detect [faces ids](https://github.com/vladmandic/human/blob/main/demo/faceid/index.ts). Expo has a [camera](https://docs.expo.dev/versions/latest/sdk/camera/) package for interacting device camera. They even have a [face detector package](https://docs.expo.dev/versions/latest/sdk/facedetector/) to detect faces. But in my case, I need more than just detecting faces (single face, blick, live, gender, ...etc.)
I got more of the code from the face-id example. But I can't really figure out how to integrate what is being captured by the device camera with this library. The examples depend heavily on the dom. But react native has no dom. Here is the complicated part of the code to write: `await human.detect(dom.video);`. 
So having both `detectFace` and `detectionLoop` example-abstraction (without the dom) would be helpful. Any help would be appreciated.

**Comment by vladmandic** [comment]
first, any reason why piggyback on an issue that was closed a looong time ago? any questions, please open a new one. or if its just a question, open a discussion topic.

anyhow, if you take a look at <https://github.com/vladmandic/human#inputs> you'll see all input types that `human` supports.  
there are absolutely no needs to use DOM if you're using react-native.  
and `human` does not internally require DOM, that is only used in demos.
