### ISSUE TITLE
Implement unified person object

### ISSUE THREAD

**Issue by ikebastuz** [vladmandic/human#122]
Hello. Your library has a great interface to work with.  

What do you think about adding some sort of a tracking mechanism in order to let `communicate` with specific `person` from CV output? Faces and Bodies a sharing common `areas` (ie nose points). Thus they can be `combined` in some sort of a combo-object like
```json
[
  {
    "face": {
      "age": 15,
      "gender": "male",
      "annotations": {}
    } | null,
    "body": {
      "keypoints": []
    } | null
  }
]

```  
On top of that comparing with previous snapshot can let understand "who is where", and add some sort of a `hash` field to the object. Comparing could be using distance between noses for example, or embedding-similarity, or both at the same time (probably even calculating some movement vector to `predict` where the person will be in the next frame)

**Comment by vladmandic** [comment]
> Hello. Your library has a great interface to work with.

Thanks!

> On top of that comparing with previous snapshot can let understand "who is where", and add some sort of a hash field to the object. Comparing could be using distance between noses for example, or embedding-similarity, or both at the same time

Hmm...Good idea, but I'd hate to change the format of the output drastically at this time. However, I've added `id` field to each `face`, `body`, etc. - so that can be used to join them if ID was sorted by person - that is doable, I'll think about it.  
And then I could implement a virtual object `person` via getter function that returns corresponding both `face` and `body`.

> probably even calculating some movement vector to predict where the person will be in the next frame

Just yesterday I've added position interpolation for body so movement appears smoother when using built-in `draw` functions.
That interpolation could be extended to move to future as well. Take a look at `src/draw/draw.ts:calcBuffered()` function.

**Comment by ikebastuz** [comment]
> Hmm...Good idea, but I'd hate to change the format of the output drastically at this time.   

Yes, you're definitely right. 

> However, I've added id field to each face, body, etc. - so that can be used to join them if ID was sorted by person - that is doable, I'll think about it.
And then I could implement a virtual object person via getter function that returns corresponding both face and body.  

Well, that is also a good thing! At which version is it available?  

> Just yesterday I've added position interpolation for body so movement appears smoother when using built-in draw functions.   

Can't really use them since I'm converting CV output to a different format. But that is good to know. Thank you!

**Comment by vladmandic** [comment]
> Well, that is also a good thing! At which version is it available?

Its in git main at the moment, I'll probably publish a version later today.  
Taking a look at unified `person` object now.

> Can't really use them since I'm converting CV output to a different format

You can likely reuse the same code - idea is simple: 
- do a deep copy of previous result object when new detection happens
- on each call, do interpolation that converges each coordinate between previous result object and current result object

it's currently implemented for body (box, keypoints) and hand: (box, landmarks, annotations).

speed of convergence is controlled by `drawOptions.bufferedFactor` where 1 means converge 100% in first step, 2 means converge 50% in first step and so on.

**Comment by vladmandic** [comment]
i've added a draft version of creating unified person in `src/person.ts`  
algorithm looks for overlap of bounding boxes between face, body and hands  
it's triggered when you read `result.person` object  

```js
interface Result {
  ...
  readonly persons: Array<Person>, // this is a getter which is calculated on-demand (when accessed)
}
```

where `Person` is defined in `src/result.ts` as:

```js
interface Person {
  id: number,
  face: Face,
  body: Body | null,
  hands: { left: Hand | null, right: Hand | null },
  gestures: Array<Gesture>,
  box: [number, number, number, number],
  boxRaw?: [number, number, number, number],
}
```

code is in main branch on `github` and will be included in the next published version of `human`  

any testing feedback is welcome

**Comment by ikebastuz** [comment]
Awesome, thats is a response!   
Will play around and share my thoughts.

**Comment by vladmandic** [comment]
human v1.9.4 has been published
