### ISSUE TITLE
Head Pose

### ISSUE THREAD

**Issue by lghasemzadeh** [vladmandic/human#125]
Hello Vladimir,

There are several good head pose models available out there but when I test them in different conditions their performance drops.
I checked this [link](https://github.com/vladmandic/human/wiki/Models) to learn more details about head pose estimation (FACE: FACING CENTER/LEFT/RIGHT ...) of Human but I didn't find what I am looking for. 
How the head pose task works? What are the inputs? what is the reference parameters to calculate it? Do you use MediaPipe facemesh to calculate the 3D face and position?
**Or** do you use a pre-trained model for head pose estimation? if yes would you please share the link.

Thank you

**Comment by vladmandic** [comment]
entire gesture analysis is done in <https://github.com/vladmandic/human/blob/main/src/gesture/gesture.ts> and is based on calculations performed as a last step of `human.detect` method and takes `human.result` as input.  

specifically, for face gesture, its method `gesture.face` that looks at z-coordinate of the points of edges of the eyes:
(i choose edges of the eyes instead of edges of the face as edge face is more likely to get occluded with higher angles)  

```js
const eyeFacing = result.face[i].mesh[33][2] - result.face[i].mesh[263][2];
if (Math.abs(eyeFacing) < 10) gestures.push({ face: i, gesture: 'facing center' });
else gestures.push({ face: i, gesture: `facing ${eyeFacing < 0 ? 'left' : 'right'}` });
```

**Comment by lghasemzadeh** [comment]
Thank you
ok so you use the eyes outer corners and nose tip (or some where there) to calculate the distance and then the head pose.
Then what about the pitch yaw and roll of head? where they come from?

**Comment by vladmandic** [comment]
pitch/yaw/roll also come from face mesh point coordinates, but math is very different (and more complex)  
see <https://github.com/vladmandic/human/blob/main/src/face.ts> method `calculateFaceAngle`, code is annotated.

**Comment by lghasemzadeh** [comment]
Hello @vladmandic,

Hope you are fine.
I am struggling with head pose extracted from mediapipe facemesh. when I changed the camera position the head pose estimation gives wrong estimations, which I expected it actually. 
For example when I change the camera position from the center at the front to center at the bottom (there is not a huge difference in camera position), and change the thresholds for up, down, right and left but it doesn't work well correctly. 
Do you have any idea?

Thank you

**Comment by vladmandic** [comment]
are you having difficulty implementing your own algorithm or having an issue with algorithm in human?  
my algorithm for calculating face rotation angles should be agnostic to camera position.  
(some other things may depend on camera position such as eye gaze estimation, but not face itself).

take a look at:
<https://github.com/vladmandic/human/blob/26649c9cc1160bdfb674eb8b98aa389115f515ca/src/face/angles.ts#L30>

**Comment by lghasemzadeh** [comment]
I first checked the Mediapipe then tried the Human and I faced same problem. see the different for same **head pose** but different camera positions in images below.
First image: the camera is exactly at the **front center**, and my head is center as well, the estimation is correct.
Second image: the camera position is at the **front but bottom**, and my head is again center exactly the position in previous image, but the estimation is wrong and shows 'Head Up'. Of course from point of view of the camera my head is up but I need world actual coordinate not the head pose w.r.t. the camera' coordinate. 
I changed the thresholds but it still doesn't give correct estimation. can [this](https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html) or [this](https://learnopencv.com/head-pose-estimation-using-opencv-and-dlib/) work for Human?
![Screenshot from 2022-02-08 00-06-02](https://user-images.githubusercontent.com/36885164/152873795-0198f119-61d9-4644-ba33-a2dafc9d837a.png)
![Screenshot from 2022-02-08 00-05-34](https://user-images.githubusercontent.com/36885164/152873817-1ae2da8e-dd5c-4111-80ad-4f0b83ba3931.png)

**Comment by vladmandic** [comment]
i don't see an issue - there is no way that anyone (actual person or AI algorithm) can determine if person is looking up or camera is placed on a low mount unless there is some reference point.  

And if you have a reference point, then it's easy to calculate angle and simply subtract it from a detected one. Of if you already know angle of the camera, just subtract it from detected angle.

Trying to modify thresholds or looking how OpenCV does it is IMO non-necessary and overly complicated.
