### ISSUE TITLE
Anti-Spoofing Detection

### ISSUE THREAD

**Issue by Maiorquino** [vladmandic/human#128]
Is possible to add a model or something related to detect if the face in image is real or fake?
Check if the person is pointing a video or a photo in the image

**Comment by vladmandic** [comment]
not out-of-the-box, but for real-vs-fake, it wouldn't be difficult  
relatively decent dataset is published on <https://www.kaggle.com/ciplab/real-and-fake-face-detection>  
and models to differentiate between the two are simple enough to write model and train it quickly  

i might take a look at that, but given my other current plans, probably not before august  
i'll leave this open as enhancement request

**Comment by vladmandic** [comment]
I just created a quick model and tested it, it gives >97% accuracy for real-or-fake  

expected input is face in 128x128 resolution, so best to parse input image using some face detection model  
(e.g. `blazeface` as it's used in `human` - and `human` library does have config param to return processed face tensor which can be directly used by some other model such as this one)

but i don't think i'll include this in human - i just don't see the use case for it in the library itself  

feel free to use the model and incorporate it as needed

link is <https://github.com/vladmandic/anti-spoofing>

model is already converted and quanitized and with test app in js, so it should be simple to re-use it
