### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#13]
Run your online demo https://vladmandic.github.io/human/demo/index.html.  I am not familiar with esbuild so I am not sure what is wrong.  I started making this type of app myself but you have all of what I wanted to implement already done so why reinvent the wheel 👍   Awesome!!

**Comment by delebash** [comment]
I found the problem if you leave external:seedrandom in your build statement it fails. I removed it and the page loaded.

**Comment by vision-interactive** [comment]
Hi, can you elaborate on the solution? i cannot make it work either

**Comment by vladmandic** [comment]
sorry about that - that's why i mark the library as still in pre-production - a lot of active development and mistakes happen.  
i've pushed a new update with a fix, version `0.4.10`.

**Comment by delebash** [comment]
No need to be sorry, thanks for the app.  I would like to help when I can.

**Comment by vladmandic** [comment]
@delebash 

    I would like to help when I can.

Anytime :)
