### ISSUE TITLE
RSS Memory usage jumps high when using RTSP input

### ISSUE THREAD

**Issue by tssghost89** [vladmandic/human#130]
**Issue Description**
I use RTSP as an input, RSS Memory usage jumps high 
Watching video: [RSS Video.zip](https://github.com/vladmandic/human/files/6676764/RSS.Video.zip)

**Steps to Reproduce**
Change input from webcam to RTSP

**Expected Behavior**
RSS memory will not jump high

**Environment

- Module version? V2.0
- Built-in demo or custom code? 
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Nodejs 14.17.1, Chrome 89
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Ubuntu Linux on x64
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
- does this happen with any other native video type? webcam or a video file in any natively supported format?
- how are you using `rtsp` as input? chrome does not support rtsp natively.
- what is your `human` configuration?

**Comment by haohoangtran** [comment]
same with me on window, i think it  also in linux
 i edit your demo file in demo/node.js to process single image forever
 my code
 `/**
 * Human demo for NodeJS
 */

const log = require('@vladmandic/pilogger');
const fs = require('fs');
const path = require('path');
const process = require('process');
const fetch = require('node-fetch').default;

// for NodeJS, `tfjs-node` or `tfjs-node-gpu` should be loaded before using Human
// eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars
const tf = require('@tensorflow/tfjs-node'); // or const tf = require('@tensorflow/tfjs-node-gpu');

// load specific version of Human library that matches TensorFlow mode
const Human = require('../../dist/human.node.js').default; // or const Human = require('../dist/human.node-gpu.js').default;

let human = null;

const myConfig = {
  modelBasePath: 'file://../../models/',
  backend: 'humangl',
  debug: false,
  videoOptimized: false,
  async: true,
  return: false,
  warmup: 'face',
  filter: {
    enabled: true,
    width: 1280,
    height: 720,
    return: true
  },
  face: {
    enabled: true,
    detector: { rotation: true, return: true, minConfidence: 0.25, maxDetected: 5 },
    // detector: { rotation: true, return: true },
    mesh: { enabled: true },
    description: { enabled: true },
    iris: { enabled: true }
  },
  hand: {
    enabled: false
  },
  gesture: {
    enabled: false
  },
  body: { enabled: false },
  object: {
    enabled: false // maximum number of objects detected in the input
  }
};

async function init() {
  // create instance of human
  human = new Human(myConfig);
  // wait until tf is ready
  await human.tf.ready();
  // pre-load models
  log.info('Human:', human.version);
  log.info('Active Configuration', human.config);
  await human.load();
  const loaded = Object.keys(human.models).filter((a) => human.models[a]);
  log.info('Loaded:', loaded);
  log.info('Memory state:', human.tf.engine().memory());
}

async function detect(input) {
  // read input image file and create tensor to be used for processing
  let buffer;
  if (input.startsWith('http:') || input.startsWith('https:')) {
    const res = await fetch(input);
    if (res && res.ok) {
      buffer = await res.buffer();
    } else {
      log.error('Invalid image URL:', input, res.status, res.statusText, res.headers.get('content-type'));
    }
  } else {
    buffer = fs.readFileSync(input);
  }

  // decode image using tfjs-node so we don't need external depenencies
  // can also be done using canvas.js or some other 3rd party image library
  if (!buffer) return {};
  const tensor = human.tf.tidy(() => {
    const decode = human.tf.node.decodeImage(buffer, 3);
    let expand;
    if (decode.shape[2] === 4) { // input is in rgba format, need to convert to rgb
      const channels = human.tf.split(decode, 4, 2); // tf.split(tensor, 4, 2); // split rgba to channels
      const rgb = human.tf.stack([channels[0], channels[1], channels[2]], 2); // stack channels back to rgb and ignore alpha
      expand = human.tf.reshape(rgb, [1, decode.shape[0], decode.shape[1], 3]); // move extra dim from the end of tensor and use it as batch number instead
    } else {
      expand = human.tf.expandDims(decode, 0);
    }
    const cast = human.tf.cast(expand, 'float32');
    return cast;
  });
  let result;
  try {
    result = await human.detect(tensor, myConfig);
  } catch (err) {
    log.error('caught');
  }
  human.tf.dispose(tensor);
  return result;
}

let frame = 0;
let isInit = false;

async function main() {
  log.header();
  if (!isInit) {
    await init();
    isInit = true;
  }
  await detect('../../samples/groups/group1.jpg');
  console.log('input frame', frame++);
  const used = process.memoryUsage();
  for (const key in used) {
    console.log(`${key} ${Math.round(used[key] / 1024 / 1024 * 100) / 100} MB`);
  }
  return main();
}

main();
`
Memory usage: 
When start:
![image](https://user-images.githubusercontent.com/16833193/122595158-3c46af00-d092-11eb-935b-7172e1ae9d19.png)
Frame 422:
![image](https://user-images.githubusercontent.com/16833193/122595186-48cb0780-d092-11eb-9969-252b6ce8ce8e.png)

Thank you,

**Comment by vladmandic** [comment]
you have `myConfig.face.detector.return = true` which returns array of tensors (1 per detected face) for further usage by user  
(for example, if you want to have a tensor ready to be used by some other external model you want to use that takes face image as input)  

unless you explicitly need it, set it to `false` and there is no leak.  
(i verified with your code with both true showing leak and false showing no leak)

but if you leave it at `true`, you need to dispose it manually: `results.face.forEach((face) => human.tf.dispose(face.tensor));`

**Comment by haohoangtran** [comment]
I changed `myConfig.face.detector.return` to false,
it still happens but slower
numTensors always is 573
When start:
![image](https://user-images.githubusercontent.com/16833193/122601175-1a9df580-d09b-11eb-982b-1ba003dc1829.png)

Frame 947:
![image](https://user-images.githubusercontent.com/16833193/122601270-3acdb480-d09b-11eb-8085-a73c42b38898.png)

It grow up from 172Mb -> 617Mb

Any ideas,
Thank you.

**Comment by vladmandic** [comment]
javascript (this is valid for both browser and nodejs) is
a) single-threaded by definition
b) memory deallocation relies on garbage collection - and that is far from perfect
b) has an internal process tick loop

in your case, you're running infinite loop without any breaks so internal process loop never detects any free ticks to actually run garbage collection.
actually, your example would eventually crash due to maximum stack size (main is calling main recursively and stack also never has a chance to cleanup).

simple change from `return main()` to `setImmediate(() => main());` tells nodejs (and browser for that matter) to process system ticks and then start next iteration as soon as possible.
which means both garbage collection and stack cleanup will have a chance to complete (not every tick, but eventually they will which is better than never as in your case).

now, rss memory still grows because nodejs garbage collection is not perfect. but if for example stop a loop after 1,000 iterations, pause for 1min and then print memory stats you'd see it actually finally managed to catch up.

here's few sample data points:

using `return main()`
> frame:500 rss:575291392 heapTotal:101912576 heapUsed:52222168 tfBytes:20879104 tfTensors:573

using `setImmediate(() => main());`
> frame:500 rss:511606784 heapTotal:72552448 heapUsed:41986008 tfBytes:20879104 tfTensors:573

using `node --expose-gc` and `if (global.gc) global.gc();`
> frame:500 rss:491499520 heapTotal:66260992 heapUsed:35206504 tfBytes:20879104 tfTensors:573

limiting to 500 runs and then printing stats again with 30sec delay using `setTimeout`
> frame:500 rss:491499520 heapTotal:66260992 heapUsed:35206504 tfBytes:20879104 tfTensors:573
> frame:500 rss:386201216 heapTotal:65736704 heapUsed:25276016 tfBytes:20879104 tfTensors:573

you can see how much nodejs freed up after being idle for 30sec

**Comment by haohoangtran** [comment]
using `node --expose-gc` and adding line `if (global.gc) global.gc();`

I clean ram manual with this and it work.

Thank you so much
