### ISSUE TITLE
WASM backend is not loaded

### ISSUE THREAD

**Issue by pferreirafabricio** [vladmandic/human#131]
**Issue Description**
When trying to use methods like `human.load()` or `human.detect()` throws the error "WASM backend is not loaded".

**Error log:**
```js
/home/fabricio/Development/projects/node/face.recognition/node_modules/@vladmandic/human/dist/human.node.js:11382
              throw new Error("Human: WASM backend is not loaded");
                    ^

Error: Human: WASM backend is not loaded
    at Human.<anonymous> (/home/fabricio/Development/projects/node/face.recognition/node_modules/@vladmandic/human/dist/human.node.js:11382:21)
    at Human.load (/home/fabricio/Development/projects/node/face.recognition/node_modules/@vladmandic/human/dist/human.node.js:11565:47)
    at Server.<anonymous> (/home/fabricio/Development/projects/node/face.recognition/server.js:37:15)
    at Object.onceWrapper (node:events:513:28)
    at Server.emit (node:events:394:28)
    at emitListeningNT (node:net:1339:10)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Steps to Reproduce**
1. Use backend as "wasm" in config
2. Set `wasmPath` to "./node_modules/@tensorflow/tfjs-backend-wasm/dist"

**Configuration object:**
```js
{
    backend: 'wasm',
    async: false,
    warmup: 'face',
    debug: true,
    videoOptimized: false,
    modelBasePath: './models/',
    wasmPath: './node_modules/@tensorflow/tfjs-backend-wasm/dist',
    face: {
      enabled: true,
      detector: { skipFrames: 0, rotation: true, return: false, minConfidence },
      mesh: { enabled: true },
      embedding: { enabled: true },
      iris: { enabled: true },
      age: { enabled: true },
      gender: { enabled: true },
      description: { enabled: true, minConfidence },
      emotion: { enabled: false },
    },
    hand: { enabled: false },
    gesture: { enabled: false },
    body: { enabled: false },
    filter: {
      enabled: true,
      brightness: -0.3,
      contrast: 0.3,
      sharpness: -0.01,
    },
    segmentation: { enabled: false },
  }
```

**Expected Behavior**
The face `detect()` and `load()` method will execute normally.

**Environment**

- Module version? 2.0.3
- Built-in demo or custom code? Custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? js
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? NodeJS v16.4.0
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Ubuntu Linux x64 (WSL)
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?

**Additional**

- For installation or startup issues include your `package.json`

```json
{
  "main": "server.js",
  "scripts": {
    "start": "nodemon server.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC",
  "engines": {
    "node": ">=16.4.0"
  },
  "devDependencies": {
    "nodemon": "^2.0.7"
  },
  "dependencies": {
    "@tensorflow/tfjs-backend-wasm": "^3.7.0",
    "@tensorflow/tfjs-node": "^3.7.0",
    "@vladmandic/human": "^2.0.3",
    "express": "^4.17.1",
    "winston": "^3.3.3"
  }
}
```

- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
`tfjs-node` is really finicky about path synax - instead of `wasmPath: './node_modules/@tensorflow/tfjs-backend-wasm/dist'
`, try `wasmPath: 'node_modules/@tensorflow/tfjs-backend-wasm/dist/'`

btw, may i ask why are you using `wasm` backend with `tfjs-node`? in most cases it's inferior to native `tensorflow` backend.

but if you still want to use `wasm` and if you're using `tfjs-node`, then it should be `tensorflow` backend. and if you're trying to use `wasm` backend, dependency should be `tfjs`, not `tfjs-node`.

also i see in your config you have `filter` brightness/contrast/etc. settings - those are ignored in `tfjs-node` as filter settings require native canvas.

**Comment by pferreirafabricio** [comment]
- Using `wasmPath: 'node_modules/@tensorflow/tfjs-backend-wasm/dist/` results on the same error.

- `btw, may i ask why are you using wasm backend with tfjs-node?` 
Because I'm using the library as a backend service (API), so I follow the instructions on [this wiki page](https://github.com/vladmandic/human/wiki/Install#3-npm-module) and I thought that will work with all backends

- Trying to use `tensorflow` as backend throws this error:
```js
/home/fabricio/Development/projects/node/face.recognition/node_modules/node-fetch/lib/index.js:1305
                throw new TypeError('Only absolute URLs are supported');
                      ^

TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/fabricio/Development/projects/node/face.recognition/node_modules/node-fetch/lib/index.js:1305:9)
    at /home/fabricio/Development/projects/node/face.recognition/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/home/fabricio/Development/projects/node/face.recognition/node_modules/node-fetch/lib/index.js:1407:9)
    at HTTPRequest.PlatformNode.fetch (/home/fabricio/Development/projects/node/face.recognition/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:7330:16)
    at HTTPRequest.<anonymous> (/home/fabricio/Development/projects/node/face.recognition/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:8280:55)
    at step (/home/fabricio/Development/projects/node/face.recognition/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:82:23)
    at Object.next (/home/fabricio/Development/projects/node/face.recognition/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:63:53)
    at /home/fabricio/Development/projects/node/face.recognition/node_modules/@tensorflow/tfjs-core/dist/tf-core.node.js:56:71
    at new Promise (<anonymous>)
```

- `also i see in your config you have filter brightness/contrast/etc. settings - those are ignored in tfjs-node...`
So in my case is better to use the `wasm` backend with `tfjs` dependency?

- With `tensorflow` backend is not possible to use filter settings as it uses `tfjs-node`?

**Comment by vladmandic** [comment]
> Using wasmPath: 'node_modules/@tensorflow/tfjs-backend-wasm/dist/ results on the same error.

That is strange - I'd need to try to reproduce using your code.

> Because I'm using the library as a backend service (API), so I follow the instructions on this wiki page and I thought that will work with all backends

I'm not sure where it recommends to use WASM backend in NodeJS? In NodeJS recommended backend is `tensorflow`. WASM is supported, but definitely inferior.

> Trying to use tensorflow as backend throws this error:

That error is clear: `Only absolute URLs are supported`  
You need to use absolute paths. Unfortunately, your stack backtrace is too short so it doesn't say exactly where it comes from, but it's likely from model load since your `baseModelPath` is `./models` which is not an absolute path. Also, in NodeJS it should be URL starting with `file://` prefix. See `demo/nodejs/node.js` for example.

> So in my case is better to use the wasm backend with tfjs dependency?

If you want to use `WASM`, then yes, you should have `@tensorflow/tfjs` as dependency.
But as I said, recommended would be to use `tensorflow` with `tfjs-node` as dependency.

> With tensorflow backend is not possible to use filter settings as it uses tfjs-node?

Regarding filters, unfortunately it doesn't matter which backend you're using - they are simply not supported in NodeJS, they are browser-only feature.

**Comment by pferreirafabricio** [comment]
> `That error is clear: Only absolute URLs are supported`

As you suggest it was because of the `modelBasePath: './models'`, changing it to `modelBasePath: 'file://models' ` (like in `demo/nodejs/node.js`) works perfectly, thanks!

> ...recommended would be to use tensorflow with tfjs-node as dependency.

Thanks for the advice! I changed the configuration object and now works great:
```javascript
{
    backend: 'tensorflow',
    async: false,
    warmup: 'full',
    debug: true,
    videoOptimized: false,
    modelBasePath: 'file://models',
    face: {
      enabled: true,
      detector: { skipFrames: 0, rotation: true, return: false, minConfidence: 0.08 },
      mesh: { enabled: true },
      embedding: { enabled: true },
      iris: { enabled: true },
      age: { enabled: true },
      gender: { enabled: true },
      description: { enabled: true, minConfidence: 0.08 },
      emotion: { enabled: false },
    },
    hand: { enabled: false },
    gesture: { enabled: false },
    body: { enabled: false },
    segmentation: { enabled: false },
  }
```

> Regarding filters, unfortunately it doesn't matter which backend you're using 

Thanks for the explanation and support.
