### ISSUE TITLE
introduce stronger result typing

### ISSUE THREAD

**Issue by pgg** [vladmandic/human#133]
```Result.Face.gender```: type instead of just string
```Result.Face.emotion```: type emotion property instead of just string
```Result.Gesture```: type gender  property instead of just string
```Person.gestures```: consider typed object instead of ```Array<Gesture>```:

```
export interface Gestures {
   face: FaceGesture[] | null,
   iris: IrisGesture[] | null,
   hand: HandGesture[] | null,
   body: BodyGesture[] | null,
}
```

- Module version?
 2.0.3

**Comment by vladmandic** [comment]
V2 introduced stronger typing, but like you noticed, there is some work left.

Btw, contributions would be welcome.

**Comment by vladmandic** [comment]
Work is continuing under #134 so this issue can be closed.
