### ISSUE TITLE
Add live demo site

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#14]
I have added a live demo site at  https://human-human.netlify.app
I have also added npm scripts to publish to https://www.netlify.com/ under my account.  If you want to do add this then you should create an account under you as maintainer.  It is free hosting and has integration with github.  If you are interested I can submit a pull request with the changes.  I tried hosting the live demo site on github pages but github pages has a problem with relative links when trying to load the .json files.  I could not find a fix for this so I choose netlify.com to host the demo.

**Comment by vladmandic** [comment]
nice, but how is this different than live demo that is already running on github pages?  
<https://vladmandic.github.io/human/demo/index.html>

**Comment by delebash** [comment]
Lol, I can't believe I did not see the live demo link.  Thanks!

**Comment by delebash** [comment]
How did you get it to work loading the json files and relative path?  I guess I have more to learn about gh pages :)

**Comment by vladmandic** [comment]
i didn't notice any issues, not that i'm that experienced with git pages  
see `config.js` in project root on how json paths are set using relative paths

**Comment by delebash** [comment]
ok thanks
