### ISSUE TITLE
face.detector.minConfidence can't be modified after first load

### ISSUE THREAD

**Issue by ghostnumber7** [vladmandic/human#141]
**Issue Description**
`face.detector.minConfidence` can't be modified after first load, and is ignored when modified via `human.detect(image, userConfig)`

**Steps to Reproduce**
* create a human instance with some detector config `const human = new Human({ face: { detector: { minConfidence: 0.01 } } })`
* try to chage the minConfidence when doing `human.detect(image, { face: { detector: { minConfidence: 0.5 } } }))`
* see it does show faces with under 0.5 confidence

**Expected Behavior**
it should not show faces under wanted cofidence

**Environment

- Module version? - `2.0.3`
- Built-in demo or custom code? - `custom`
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? - `js`
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? - `NodeJS v14.17.3`
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? - `Window 10 / Ubuntu 20`
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)? - `none`

**Additional**

The issue happens because config is passed to blazeface only when [constructing](https://github.com/vladmandic/human/blob/main/src/blazeface/blazeface.ts#L91) and is never modified after that. Simple solution is to inject and merge `userConfig` when [calling](https://github.com/vladmandic/human/blob/main/src/blazeface/facepipeline.ts#L161) [getBoundingBoxes](https://github.com/vladmandic/human/blob/main/src/blazeface/blazeface.ts#L40)

**Comment by vladmandic** [comment]
Thanks for the PR.  

I'm currently traveling and will review and merge in about a week.

**Comment by ghostnumber7** [comment]
Hi @vladmandic, I noticed there are more options that can't be altered dynamically after initialization. Would you prefer I create a new issue (and PR) for each one, or to reuse and update this one?

**Comment by vladmandic** [comment]
@ghostnumber7 no need for separate PR, I'll review and merge in one go anyhow.

**Comment by ghostnumber7** [comment]
@vladmandic I was wrong when stating there were other things (error on my code). So just that one for now :)

**Comment by vladmandic** [comment]
merged pr so closing the issue
