### ISSUE TITLE
TypeDoc API Specification is not accessible

### ISSUE THREAD

**Issue by uzair004** [vladmandic/human#147]
**Issue Description**

Cannot access the human API documentation here [API Docs](https://vladmandic.github.io/human/typedoc/classes/human.html)

It shows 404 not found error

**Steps to Reproduce**
just visit [This link](https://vladmandic.github.io/human/typedoc/classes/human.html)

looks like there is problem with github pages

**Comment by vladmandic** [comment]
latest version of `typedoc` changed file name capitalization thus causing broken links  
update has been pushed
