### ISSUE TITLE
No camera image in Demo link

### ISSUE THREAD

**Issue by Krammig** [vladmandic/human#158]
Would love to try the demo but all that is displaying is the rotating progress circles and a message saying Starting Detection. 
Appreciate if you could let me know if there is something I need to do at my end. 

Chrome
Firefox
i5 16GB

**Comment by vladmandic** [comment]
I just tried with Chrome and Firefox and it works fine here.

- Can you open browser inspector (in firefox its menu -> more tools -> web developer tools) and copy&paste the log?
- Can you try with Chrome or Edge?

Btw, do you have a GPU or integrated graphics?

**Comment by Krammig** [comment]
Sorry just saw the message

**Comment by Krammig** [comment]
Sorry k

**Comment by Krammig** [comment]
Sorry just saw your reply. 
Dedicated GPU 
I had tried with both Chrome and Firefox. 
Will check the inspector in the coming hour and let you know.

**Comment by vladmandic** [comment]
closing due to idle time, will reopen if information is provided.
