### ISSUE TITLE
WASM backend having issue

### ISSUE THREAD

**Issue by mainisameer** [vladmandic/human#159]
**Issue Description**
when we are trying use WASM backend we are getting the following error message 
tfjs-backend-wasm-simd.wasm:0xaa3 Uncaught (in promise) RuntimeError: memory access out of bounds
    at tfjs-backend-wasm-simd.wasm:0xaa3
    at tfjs-backend-wasm-simd.wasm:0x1b3ef
    at Wk.move (human.js:4613)
    at Wk.write (human.js:4613)
    at rc.makeTensor (human.js:11)
    at Kr (human.js:11)
    at dn (human.js:11)
    at Object.Z5 (human.js:11)
    at x7.loadSync (human.js:40)
    at x7.load (human.js:40)

**Steps to Reproduce**
We are running human inside webworker and when we set the backend to webgl or cpu it works fine. Our front end is in react anad we have added the following 2 script tags to our index.html
 <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs"></script>

    <script src="https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm/dist/tf-backend-wasm.js"></script>
Our WASM path is specified as
"https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.8.0/dist/",
We are importing the human script 
self.importScripts(
  "https://cdn.jsdelivr.net/npm/@vladmandic/human/dist/human.js"
);

**Comment by mainisameer** [comment]
Fixed when I looked at the demo I saw that the WASM backend was point to 3.9 and I updated it and it is working

**Comment by vladmandic** [comment]
correct, version of wasm binaries must match version of tfjs used - and i've upgraded to tfjs 3.9.0 earlier this week  
to avoid versioning issues, i've added dynamic default for wasm path if there is no user setting:  
(if wasmpath is set in user config, it will override default value)  

```js
defaults.wasmPath = `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@${tf.version_core}/dist/`;
```
