### ISSUE TITLE
Simple example with webRtc to get yaw, roll, pitch

### ISSUE THREAD

**Issue by mmehdinasiri** [vladmandic/human#165]
Thanks for your great lib.
I need to detect user header yaw, roll, pitch with webRtc. I have checked your demo index.js file but it's so complicated.
It would be fantastic if you create some simple examples for different options, especially for my case.

**Comment by vladmandic** [comment]
glad you like it! :)

*browser* demo is a full fledged app that demonstrates all capabilities of human  
to see simple usage, best to take a look at *nodejs* demos - same principles apply to browser and node  

for example, <https://github.com/vladmandic/human/blob/main/demo/nodejs/node-canvas.js> is as short as possible  
and all data you need is in `results` object and that is documented at <https://vladmandic.github.io/human/typedoc/interfaces/Result.html>

**Comment by vladmandic** [comment]
added simple webcam and webrtc demo at:
- <https://github.com/vladmandic/human/tree/main/demo/simple>  
and live link at:  
- <https://vladmandic.github.io/human/demo/simple/index.html>
