### ISSUE TITLE
HUman New Version Erroring out

### ISSUE THREAD

**Issue by mainisameer** [vladmandic/human#166]
We are using the human API and downloading it from the CDN and importing it 
https://cdn.jsdelivr.net/npm/@vladmandic/human/dist/human.js
This was working before the new update this is the error message we are getting now
![image](https://user-images.githubusercontent.com/68697034/133723398-c6eac2c8-4fa7-440c-add9-d3fd6a832f2c.png)

**Comment by vladmandic** [comment]
Can you download updated models and place it in your CDN?

It's not just the library that's updated, models are as well and new library requires new models.

**Comment by mainisameer** [comment]
We will give it a try thank you for your prompt respone

**Comment by trancee** [comment]
I am having the same issue, and I am using the `blazeface` model. When I look at the changes in your repository, the last change for this model was 6 months ago. Do I have to get the model from somewhere else to make it work?

**Comment by vladmandic** [comment]
did you force download latest versions of models?  
last change to model was 6 months ago, but model signature was not enforced until in latest version of library  
so if you never updated model in the last 6 months, you'll get the error now

**Comment by vladmandic** [comment]
ah, very specific combination of enabled/disabled models was causing read on null value during model validation phase.
fixed and pushed new version 2.2.2.
