### ISSUE TITLE
Missing movenet-thunder model

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#172]
The docs say that `movenet-thunder` model is supported, but it seems the actual model is missing in the library.

As a side note, I have mentioned before that there are some accuracy/performance differences between `human` and the Google TFJS equivalents which use the same models, and this happens as well for `movenet-lightning`. The `human` version of `movenet` has a shorter inference time but the result is less accurate when compared with TFJS `posenet`.

**Comment by vladmandic** [comment]
from <https://github.com/vladmandic/human/wiki/Models>

## Using Alternatives

`Human` includes implementations for several alternative models which can be switched on-the-fly while keeping standardized `input` and `results` object structure

Switching model also automatically switches implementation used inside `Human` so it is critical to keep model filenames in original form  

`Human` includes all default models while alternative models are kept in a separate repository due to size considerations and must be downloaded manually from <https://github.com/vladmandic/human-models>

**Comment by ButzYung** [comment]
Thanks. It's funny how the thunder model's inference time is somewhat similar to the lightning model, though it's visibily more accurate. When compared with TFJS `pose-detection` using thunder, `human` inference time is still shorter but again less accurate.

I also wonder, is the `blazepose` model you included the latest one? I notice that Google has updated the `blazepose` models recently with 3 different sizes (lite/full/heavy), full 3D detection and since they have dropped the separated upper pose approach, the new model is accurate even when just detecting upper/partial body.

**Comment by vladmandic** [comment]
> It's funny how the thunder model's inference time is somewhat similar to the lightning model, though it's visibly more accurate.

`Thunder` on its own is very nice, but it blocks async execution for longer time thus overall frame rate when all models are enabled suffers.

> When compared with TFJS pose-detection using thunder, human inference time is still shorter but again less accurate

I haven't taken a look at TFJS implementation as I did mine before TFJS implementation was released  
But overall, model has very clean output, not much room for post-processing enhancements  
One thing I need to experiment is when resizing input to keep aspect-ratio intact  

> I also wonder, is the blazepose model you included the latest one? I notice that Google has updated the blazepose models recently with 3 different sizes (lite/full/heavy), full 3D detection and since they have dropped the separated upper pose approach, the new model is accurate even when just detecting upper/partial body.

No, my implementation is based on older version of `blazepose`  
I'll take a look at the new one  

Previously I really liked `blazepose` when body was nicely framed in input, but it suffered badly when body was not framed perfectly or partially obscured or out of frame  

On a separate note, did you take a look at `movenet-multipose`? It's based on lightning, but has slightly different internal architecture  

Also, any interest in the new `handtrack` model I released few days ago?

*Btw, I appreciate any feedback and suggestions!*

**Comment by vladmandic** [comment]
Ah, I took a quick look <https://github.com/tensorflow/tfjs-models/tree/master/pose-detection>,  
I have an idea why results look better and should be relatively easy to implement - I used the same approach with the new `handtrack` model  

Simplified, next frame does not take entire input as a whole, but cuts a box determined by scaling virtual box based on keypoints of the previous frame. Helps a lot with linear video inputs

Btw, old `facemesh` and `handdetect` use similar approach, but far less efficient with a lot of incorrect cache entries  
I need to reimplement `facemesh`, but that one is not a small task  

Expect implementation in the next few days

**Comment by ButzYung** [comment]
> Also, any interest in the new `handtrack` model I released few days ago?

Didn't notice this new feature when I opened this issue (since I was still using an older version of `human`). I tried the latest version, and quickly noticed some issues.

1. If I didn't manually specifiy the `maxDetected` attribute for `hand`, the output for the hand part is always an empty array, no matter whether it is `handtrack` or `handdetect`. This didn't happen for older versions, including the current stable release (`2.2.1`).

2. The way `handtrack` handles the output result when no skeleton is detected is different from `handdetect`. `handdetect` simply returns an empty array if no skeleton is detected, while `handtrack` still returns the results with detected boxes even though attributes like `annotations` and `landmarks` are empty objects.

3. It's hard to tell whether `handtrack` or `handdetect` is better at this point. `handdetect` still appears to detect more non-empty results in general, while `handtrack` sometimes detects a hand when `handdetect` misses. `handtrack` inference time appears to be better (though not very obvious). By the way, `handtrack` seems to give more meaningful ouputs when `minConfidence` is low enough. I think `handtrack` is promising in the long run.

**Comment by vladmandic** [comment]
> If I didn't manually specifiy the maxDetected attribute for hand, the output for the hand part is always an empty array, no matter whether it is handtrack or handdetect. This didn't happen for older versions, including the current stable release (2.2.1).

This is brand new - if `maxDetected` is not specified or specified as -1, its now autodetected based on number of detected faces (body.maxDetect = face.length and hand.maxDetected = 2x face.lenght) . This applies to both `hand` and `body`.  

If you have face detection disabled, they you have to specify `maxDetected` manually.  

But this logic is just in a main branch, it hasn't been published yet. I'll polish it a bit more before publishing.

> The way handtrack handles the output result when no skeleton is detected is different from handdetect. handdetect simply returns an empty array if no skeleton is detected, while handtrack still returns the results with detected boxes even though attributes like annotations and landmarks are empty objects.

Correct. I think this is better way of handling it will change `handdetect` to work the same way. That's why there are also separate scores for detection and details now.

> It's hard to tell whether handtrack or handdetect is better at this point. handdetect still appears to detect more non-empty results in general (though some detections are actually false positive), while handtrack sometimes detects a hand when handdetect misses. handtrack inference time appears to be better (though not very obvious). By the way, handtrack sometimes give more meaningful ouputs when minConfidence is low enough. I think handtrack could be promising in the long run.

This pretty much matches my observations. I'll work on handtrack more and when it's ready, i'll do the switch. In the meantime, I'll keep it as optional.

**Comment by ButzYung** [comment]
> If you have face detection disabled, they you have to specify `maxDetected` manually.

Oh this explains it. For various reasons I am detecting face and body/hand on separated workers, and obviously on the body/hand side, face detection is disabled.

**Comment by vladmandic** [comment]
> Oh this explains it. For various reasons I am detecting face and body/hand on separated workers, and obviously on the body/hand side, face detection is disabled.

That's a valid scenario, I'll disable autodetection for maxDetected if face detection is disabled.

**Comment by vladmandic** [comment]
i've just added box caching to movenet and pushed update to github, but its not a major difference in quality of results  

one thing i forgot to ask - are you using temporal smoothing in `human`?

implementation in `human` and `tfjs-models` is very different:
- `tjfs-models` perform temporal smoothing (if enabled which is by default) before returning results
- `human.detect()` always returns current result and temporal smoothing is done explicitly by using `human.next()`

idea is to run detection in a separate thread and in main thread that performs draw updates calls `human.next()` before each redraw and uses interpolated & smoothened results. and interpolation calculation is fast, so it doesn't slow down main thread

**Comment by vladmandic** [comment]
update on new `blazepose` - implementation is done, but i don't like it  
pose tracking requires very carefully preprocessed input where center of torso is found and them image constructed with padding so torso is always in the middle and entire body is in the frame, regardless if it exists or not  

and it does that based on really heavy anchor calculations. 

`blazepose` has benefits that its
a) 3D model, not 2D,
b) also returns heatmaps (not just points) which is nice for advanced analysis

but...i think `blazepose` itself is pretty useless without a heavy-weight `blazepose-detector` which is just too complex and slow for `human`  

im leaving implementation in, but will not enable it and i don't plan to implement detector code anytime soon  
if there was no alternative, maybe - but movenet seems a much cleaner model

**Comment by vladmandic** [comment]
since issue was about `movenet-thunder` and that was provided (plus additional enhancements to `movenet` implemenation plus `blazepose` test implementation), i'm closing this issue for now

**Comment by ButzYung** [comment]
It's a pity to know that `blazepose` may not fit `human`. Yeah movenet is clean and fast, but there exists situations where 3D positioning is a must, and right now `blazepose` is the only solution here.

**Comment by vladmandic** [comment]
FYI...

ive added basic implementation of **blazepose v2**:
- all variations (lite/full/heavy) are supported
- models can be downloaded from <https://github.com/vladmandic/human-models>
  they are *almost* identical to ones on `tfhub`, but there is some manual tuning present as well
- enable as usual, just set `body.modelPath` to one of new models and it will  
  automatically trigger appropriate implementation
- my implemenation completely skips `blazepose-detector` (which i really dont like) and instead does  
  a best-guess on the possible body box before passing it to model for processing  
  there is a of possible improvements to that method and im playing with that,  
  i just thought you might want to try implementation as-is

my core issues with the model:
- it returns ghost predictions when there is no body in the input at all
  (i recommend setting `body.minConfidence = 0.6` at minimum, but it can still happen)
- it returns *keypoints* with relatively high score even if they are not in the input at all  
  (although i made some progress on this)

btw, model is actually really fast - so fast that its sometimes better to slow it down a bit  
e.g., set `body.skipFrames = 5` or delay `human.detect()` loop  
and let time-based interpolation do some smoothing instead using `human.next()`

oh, `blazepose` also includes heatmaps for joints - that might be useful, although not sure what for right now :)
