### ISSUE TITLE
EventTarget error in NodeJS

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/human#175]
### Discussed in https://github.com/vladmandic/human/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **olmerg** September 30, 2021</sup>
amazing library, thanks in advance by your help.

After I install Human in node v14.7.6 /Ubuntu 20.04 and try to create a Human object inside my node project I receive and error in line 12580 of human.node.js `this.events = new EventTarget();`

If I comment this line in the library it works, what else should I install?
</div>

**Comment by vladmandic** [comment]
`EventTarget` should be supported in `NodeJS` *v14*, but there seems to be a missing definition  
I'll add code to handle this

**Comment by vladmandic** [comment]
I just pushed an update on `github` that should fix this - basically marking event notifications as optional - if supported by Browser or NodeJS, they will be used and if not, they will be skipped (event notifications exist so app can subscribe to human events which is totally optional)

Can you test as I cannot reproduce the issue?

**Comment by olmerg** [comment]
Great that works for me in node v14.7.6 /Ubuntu 20.04 with human.node.js

**Comment by vladmandic** [comment]
perfect, thanks for the quick confirmation.
