### ISSUE TITLE
extract types

### ISSUE THREAD

**Issue by pgg** [vladmandic/human#176]
**Issue Description**
npm i @vladmandic/human includes entire human lib. When only interested in the types, it bloats the download. This is not ideal for docker image size

**Expected Behavior**
install only human types

**Comment by vladmandic** [comment]
currently npm includes:
>  0.5MB   types
>  0.6MB   src
>  1.4MB   demo
>  2.4MB   assets
> 13MMB   dist (partial)
> 40MMB   models

while full git repository additionally includes:
>  0.1MB   wiki
>  0.1MB   test
>  0.1MB   typedoc
> 18MB   samples
> 21MB   dist (full)

what is the use case for `/types` only?

now, if goal is to reduce overall `human` npm size
- `/src` could be excluded from npm, but i consider that bad practice  
- `/models` (largest component by far) that are required for `human` library  
  note that `/models` includes only default models used by `human`  
  while alternative & optional ones are held separately  
  in `@vladmandic/human-models` repository which is 110MB  
- `/assets` are mostly icons and screenshots used in docs  

what could be done is to create a separate npm `human-minimal` that points to a  
hosted CDN as a model location and assets but i haven't seen enough demand for that

**Comment by vladmandic** [comment]
i think what would be better is to create optimized docker recipe - that is a valid enhancement request.

**Comment by vladmandic** [comment]
added wiki page on how to optimize docker deployment with human: <https://github.com/vladmandic/human/wiki/Docker>

**Comment by pgg** [comment]
> currently npm includes:
> 
> > 0.5MB   types
> > 0.6MB   src
> > 1.4MB   demo
> > 2.4MB   assets
> > 13MMB   dist (partial)
> > 40MMB   models
> 
> while full git repository additionally includes:
> 
> > 0.1MB   wiki
> > 0.1MB   test
> > 0.1MB   typedoc
> > 18MB   samples
> > 21MB   dist (full)
> 
> what is the use case for `/types` only?
> 
> now, if goal is to reduce overall `human` npm size
> 
> * `/src` could be excluded from npm, but i consider that bad practice
> * `/models` (largest component by far) that are required for `human` library
>   note that `/models` includes only default models used by `human`
>   while alternative & optional ones are held separately
>   in `@vladmandic/human-models` repository which is 110MB
> * `/assets` are mostly icons and screenshots used in docs
> * `/dist` is `human` library itself in different formats,
>   it could be reduced in size significantly if i enable minification
>   (currently disabled purely as a choice during active development)
> 
> what could be done is to create a separate npm `human-minimal` that is fully minified and points to a hosted CDN as a model location and assets but i haven't seen enough demand for that

human runs as micro service in its own docker container, no issue there wrt container size. the api gateway however only needs the types and not the entire human lib. the build tool generates package.json based on usage, and since the types are part of the lib as a whole, that is what is used and npm install then pulls the +- 60mb for just the types . . .

**Comment by vladmandic** [comment]
That is a **very specific** way of using the library.  
And if you're doing all that, nothing is stopping you to extract types yourself instead of installing library each time.  
This will not be implemented.

**Comment by pgg** [comment]
sure i can do that no prob, just thought it would be nice to decouple what is already there . . .

**Comment by vladmandic** [comment]
AFAIK, only libraries that are not written in TS natively have externally decoupled `types` published as a separate module to be consumed by other TS projects  

What you're asking for would be a separate npm, `@types/@vladmandic/human` which I have no intention of publishing as its redundant

**Comment by vladmandic** [comment]
closing due to reasons described above
