### ISSUE TITLE
improve GestureResult

### ISSUE THREAD

**Issue by pgg** [vladmandic/human#177]
**Issue Description**
GestureResult type inference fails/is hard to use for individual results. Consider returning individual arrays per gesture instead of gesture as array, ie:

```
gestures: {
    face: FaceGesture[] | undefined;
    iris: IrisGesture[] | undefined;
    body: BodyGesture[] | undefined;
    hand: HandGesture[] | undefined;
  };
```

**Comment by vladmandic** [comment]
very valid and i though about it already  

but it would create a breaking change to any existing apps that use gestures  
(also, id have to change all of demos that use gestures)  

i might reconsider, so keeping this request open

**Comment by pgg** [comment]
this is the current gymnastics needed to transform/make it usable:
```
... gestures.reduce((p, c) => {
            if ((c as { face: number }).face != null)
              p.face = [...(p.face ?? []), c.gesture as FaceGesture];
            if ((c as { iris: number }).iris != null)
              p.iris = [...(p.iris ?? []), c.gesture as IrisGesture];
            if ((c as { body: number }).body != null)
              p.body = [...(p.body ?? []), c.gesture as BodyGesture];
            if ((c as { hand: number }).hand != null)
              p.hand = [...(p.hand ?? []), c.gesture as HandGesture];
            return p;
          }, {} as Gestures)
```

**Comment by vladmandic** [comment]
*"gymnastics"* is only required if you dont want to use them in the current form - and they are usable as it is.

and even if you really want them in your recommended format, there are much easier ways of performing a transform using `Object.entries(gestures)`

like I said, this request is a valid suggestion, but it has to be weighted against current install base. And it's far from prohibiting usage or requiring what you did.

**Comment by pgg** [comment]
would you mind showing me the much easier Object.entries way that is still type safe?

**Comment by vladmandic** [comment]
There are places for full type-safe (which is internal usage in Human to avoid typos when assigning gestures)  
and places where you only consume results  

this is copy&paste from the nodejs demo:

```js
for (let i = 0; i < result.gesture.length; i++) {
  const [key, val] = Object.entries(result.gesture[i]);
  log.data(`Gesture: ${key[0]}#${key[1]} gesture:${val[1]}`);
}
```

You insist doing things your way which is totally ok.  
But lets not get into shouting match which way is the only correct way.

**Comment by vladmandic** [comment]
Also, your proposed structure is missing property which result is gesture belonging to as each gesture becomes just an array.
E.g, currently you can have `{ face:0, gesture: 'first_gesture' }` and `{ face:0 ,gesture: 'second gesture' }` and `{ face:1, gesture: 'third_gesture' }` - that is not possible with your simplified structure

**Comment by pgg** [comment]
> There are places for full type-safe (which is internal usage in Human to avoid typos when assigning gestures) and places where you only consume results
> 
> So to get your transform, it would be something like this:
> 
> ```js
>   const transformed = { face: [], iris: [], body: [], hand: [] };
>   result.gesture.forEach((gesture) => transformed[Object.keys(gesture)[0]].push(Object.values(gesture)[1]));
> ```
> 
> You insist doing things your way which is totally ok. But lets not get into shouting match which way is the only correct way.

i am not trying to get into a shouting match, sorry if it comes across that way. what i am trying to point out however is that using the api in a type safe way is difficult (especially when ts is in strict mode). in a purely js env it works fine. . .

**Comment by pgg** [comment]
> Also, your proposed structure is missing property which result is gesture belonging to as each gesture becomes just an array. E.g, currently you can have `{ face:0, gesture: 'first_gesture' }` and `{ face:0 ,gesture: 'second gesture' }` and `{ face:1, gesture: 'third_gesture' }` - that is not possible with your simplified structure

sure, was just giving an idea of a shape that can be considered. for my example i am only allowing a single match, so not an issue, but the prop can obviously be added to the gesture itself . . .

**Comment by pgg** [comment]
in a typescript strict mode environment your transform example is not allowed
```
....gestures.reduce((p, c) => p[Object.keys(c)[0]].push(Object.values(c)[1]))
```
yields the following
```
Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ face: FaceGesture[] | undefined; iris: IrisGesture[] | undefined; body: BodyGesture[] | undefined; hand: HandGesture[] | undefined; }'.
  No index signature with a parameter of type 'string' was found on type '{ face: FaceGesture[] | undefined; iris: IrisGesture[] | undefined; body: BodyGesture[] | undefined; hand: HandGesture[] | undefined; }'.ts(7053)
```

**Comment by vladmandic** [comment]
typecast string index to string union to pass ts strict checks  

anyhow, i think it would be best to close this thread for now

**Comment by vladmandic** [comment]
closing the issue
