### ISSUE TITLE
Face recognition nit work correctly

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/human#190]
Hi I tested Human.js with anti spoofing
Why if i show webcam 2 absolytle other person male and female it say that is similar?
face 0 is 47.722392031248134% simmilar 
` 
face_detection: async function (video, canvas) {
            const result = await this.parent.human.detect(canvas);
            console.log(result, 'result')
            console.log(this.descriptor_ids, 'descriptor_ids')

            if (result.face.length) {
                this.parent.human.draw.all(canvas, result);

                for (let i = 0; i < this.descriptor_ids.length; i++) {
                    if (this.parent.face_recognition_pro_photo_check){
                        let check = await this.antiSpoofingCheck(result.face[0].tensor)
[found emb.txt](https://github.com/vladmandic/human/files/7327996/found.emb.txt)
[from db.txt](https://github.com/vladmandic/human/files/7327997/from.db.txt)
                        console.log("check: " + check)
                        if (check < 0.80)
                            continue
                    }
                    const similarity = this.parent.human.similarity(result.face[0].embedding, this.descriptor_ids[i]);
                    console.log(`face ${i} is ${100 * similarity}% simmilar`);
                    // Found employee
                    console.log(100 * similarity)
                    if (100 * similarity < 60) {
                        this.check_in_out(canvas, this.labels_ids[i]);
                        return 'stop'
                    }
                }

            }
        },
`
And also match function not work return dict with empty item
And dont matter Float32Array or Array i combine all variants

**Comment by vladmandic** [comment]
> Why if i show webcam 2 absolytle other person male and female it say that is similar?  
> face 0 is 47.722392031248134% simmilar 

That is possible, why couldn't male and female persons be somewhat similar - it's not like its a high similarity  
Can you provide example images?  

> And also match function not work return dict with empty item

Can you provide code and example for this?

**Comment by vladmandic** [comment]
Any updates?
