### ISSUE TITLE
tf.nonMaxSuppression() in webgl locks the UI thread. Call tf.nonMaxSuppressionAsync() instead

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#20]
Browser Microsoft Edge v86.0.622.63 x64

Steps to reproduce

1) Open this repo's live demo link https://vladmandic.github.io/human/demo/index.html
2) Open dev tools
3) Click Start Video
4) Error will display in console.  Disable hand pose using slider and error will stop, enable hand pose and it will start.

**Comment by vladmandic** [comment]
fixed and pushed git update
<https://github.com/vladmandic/human/commit/db80af4b68eac92b5cb3ca08fdede3ec6ad70dc2>
