### ISSUE TITLE
[Safari]: exception: null is not an object (evaluating 'gl.isContextLost')

### ISSUE THREAD

**Issue by MaKleSoft** [vladmandic/human#205]
Safari throws the following exception:

```
exception: null is not an object (evaluating 'gl.isContextLost')
```

**Environment**

- Human library version: 2.5.1
- Built-in demo or custom code: Main demo
- Browser or NodeJS and version:  Safari 14.1.1
- OS and Hardware platform: MacOS 11.4 (M1 Air)

**Diagnostics**

- Only happens with the following backends: humangl, tensorflow, webgpu (works with cpu, webgl and wasm)

**Additional**

<img width="1349" alt="Screenshot 2021-11-08 at 16 01 09" src="https://user-images.githubusercontent.com/1270940/140767130-fb91d9ff-8c3b-47fa-b1fc-599e3942009c.png">
<img width="1773" alt="Screenshot 2021-11-08 at 16 04 23" src="https://user-images.githubusercontent.com/1270940/140767164-a02bcc3b-29a9-4390-9ccb-d602603b3556.png">

**Comment by vladmandic** [comment]
Strange that `gl` is undefined on error in Safari, but ok, I'll patch TFJS to check for that condition. However, that happens inside error handler - there is no working around the fact that GL context got destroyed.

Can you copy & paste browser log instead of screenshots? I need them to submit patch to TFJS as that is where error happens (I could create a workaround in `Human`, but its better to fix at the source)?

Anyhow, `TensorFlow` backend doesnt exist in browser, so if you select it Human will automatically use `WebGL` instead  

Similar for `WebGPU` unless `WebGPU` is enabled in experimental flags in browser (*Safari->Settings->Advanced->Experimental Features->WebGPU*)

Can you try couple of things?
- `Human` 2.5.1 with `WebGPU` backend after its enabled in Safari
- `Human` 2.3.x as it uses older version of `tfjs-backend-webgl`

**Comment by MaKleSoft** [comment]
> Can you copy & paste browser log instead of screenshots? I need them to submit patch to TFJS as that is where error happens (I could create a workaround in Human, but its better to fix at the source)?

Of course!
```
[Log] 16:53:31.448 – "demo starting ..." (index.js, line 169)
[Log] 16:53:31.448 – "webworker functionality is disabled due to missing browser functionality" (index.js, line 169)
[Log] 16:53:31.450 – "pwa found:" – "https://vladmandic.github.io/human/demo/index.html" (index.js, line 169)
[Log] 16:53:31.450 – "pwa ctive:" – "https://vladmandic.github.io/human/demo/index-pwa.js" (index.js, line 169)
[Log] 16:53:31.484 – "pwa cache:" – 16 – "files" (index.js, line 169)
[Log] 16:53:31.484 – "url options:" – "" (index.js, line 169)
[Log] 16:53:31.485 – "human version:" – "2.5.1" (index.js, line 169)
[Log] 16:53:31.485 – "tfjs version:" – "3.11.0-20211108" (index.js, line 169)
[Log] 16:53:31.493 – "status" – "setting up camera" (index.js, line 169)
[Log] 16:53:31.499 – "camera constraints" – {audio: false, video: Object} (index.js, line 169)
{audio: false, video: Object}Object
[Log] 16:53:31.503 – "enumerated input devices:" – [MediaDeviceInfo, MediaDeviceInfo] (2) (index.js, line 169)
[MediaDeviceInfo, MediaDeviceInfo]Array (2)
[Log] 16:53:33.302 – "enumerated viable tracks:" – [MediaStreamTrack] (1) (index.js, line 169)
[MediaStreamTrack]Array (1)
[Log] 16:53:33.303 – "selected video source:" (2) (index.js, line 169)
MediaStreamTrack {kind: "video", id: "29355b12-a9b0-486e-9316-7ef2626cae81", label: "FaceTime HD Camera", enabled: true, contentHint: "", …}MediaStreamTrack{deviceId: "532CBAA39CEAB9BA4196274B70EEC70F9AA5F869", frameRate: 30, height: 827, width: 804}Object
[Log] Error when getting WebGL context:  – TypeError: null is not an object (evaluating 'gl.isContextLost') — tfjs.esm.js:45072 (human.esm.js, line 46257)
TypeError: null is not an object (evaluating 'gl.isContextLost') — tfjs.esm.js:45072
[Log] 16:53:38.936 – "Human:" – "humangl webgl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 16:53:38.936 – "Human:" – "backend registered:" – "humangl" (human.esm.js, line 58)
[Log] 16:53:38.936 – "Human:" – "available backends:" (human.esm.js, line 58)
["cpu", "webgl", "wasm", "humangl"] (4)
[Log] 16:53:38.936 – "Human:" – "setting backend:" – "humangl" (human.esm.js, line 58)
[Log] 16:53:38.938 – "Human:" – "gl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 16:53:38.939 – "status" – "human: ready" (index.js, line 169)
[Log] 16:53:38.940 – "environment:" (index.js, line 169)
Env {browser: true, node: false, worker: undefined, platform: "Macintosh; Intel Mac OS X 10_15_7", agent: "Mozilla/5.0 AppleWebKit/605.1.15 Version/14.1.1 Safari/605.1.15", …}
[Log] 16:53:38.940 – "backend:" – {name: "humangl", priority: 999, canvas: <canvas>, …} (index.js, line 169)
{name: "humangl", priority: 999, canvas: <canvas>, gl: null, extensions: [], …}Object
[Log] 16:54:24.419 – "status" – "starting detection" (index.js, line 169)
[Log] 16:54:24.430 – "Human:" – "error: humangl backend invalid context" (human.esm.js, line 58)
[Log] 16:54:24.430 – "Human:" – "available backends:" – ["cpu", "webgl", "wasm", …] (4) (human.esm.js, line 58)
["cpu", "webgl", "wasm", "humangl"]Array (4)
[Log] 16:54:24.431 – "Human:" – "setting backend:" – "humangl" (human.esm.js, line 58)
[Log] 16:54:24.432 – "Human:" – "gl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 16:54:24.434 – "Human:" – "version: 2.5.1" (human.esm.js, line 58)
[Log] 16:54:24.434 – "Human:" – "tfjs version: 3.11.0-20211108" (human.esm.js, line 58)
[Log] 16:54:24.434 – "Human:" – "error: humangl backend invalid context" (human.esm.js, line 58)
[Log] 16:54:24.435 – "Human:" – "available backends:" – ["cpu", "webgl", "wasm", …] (4) (human.esm.js, line 58)
["cpu", "webgl", "wasm", "humangl"]Array (4)
[Log] 16:54:24.435 – "Human:" – "setting backend:" – "humangl" (human.esm.js, line 58)
[Log] 16:54:24.436 – "Human:" – "gl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 16:54:24.437 – "Human:" – "configuration:" – {backend: "humangl", modelBasePath: "../models/", wasmPath: "https://vladmandic.github.io/tfjs/dist/", …} (human.esm.js, line 58)
{backend: "humangl", modelBasePath: "../models/", wasmPath: "https://vladmandic.github.io/tfjs/dist/", debug: true, async: true, …}Object
[Log] 16:54:24.438 – "Human:" – "environment:" – Env {browser: true, node: false, worker: undefined, …} (human.esm.js, line 58)
Env {browser: true, node: false, worker: undefined, platform: "Macintosh; Intel Mac OS X 10_15_7", agent: "Mozilla/5.0 AppleWebKit/605.1.15 Version/14.1.1 Safari/605.1.15", …}Env
[Log] 16:54:24.438 – "Human:" – "tf flags:" – {IS_BROWSER: true, IS_NODE: false, DEBUG: false, …} (human.esm.js, line 58)
{IS_BROWSER: true, IS_NODE: false, DEBUG: false, CPU_HANDOFF_SIZE_THRESHOLD: 256, WEBGPU_CPU_HANDOFF_SIZE_THRESHOLD: 1000, …}Object
[Log] 16:54:24.510 – "Human:" – "load model:" – "../models/blazeface.json" (human.esm.js, line 58)
[Log] 16:54:24.536 – "Human:" – "load model:" – "../models/iris.json" (human.esm.js, line 58)
[Log] 16:54:24.548 – "Human:" – "load model:" – "../models/facemesh.json" (human.esm.js, line 58)
[Log] 16:54:24.557 – "Human:" – "load model:" – "../models/emotion.json" (human.esm.js, line 58)
[Log] 16:54:24.641 – "Human:" – "load model:" – "../models/handtrack.json" (human.esm.js, line 58)
[Log] 16:54:24.693 – "Human:" – "load model:" – "../models/movenet-lightning.json" (human.esm.js, line 58)
[Log] 16:54:24.875 – "Human:" – "load model:" – "../models/handlandmark-full.json" (human.esm.js, line 58)
[Log] 16:54:24.875 – "Human:" – "load model:" – "../models/faceres.json" (human.esm.js, line 58)
[Log] 16:54:24.875 – "Human:" – "tf engine state:" – 52887856 – "bytes" – 1475 – "tensors" (human.esm.js, line 58)
[Error] null is not an object (evaluating 'gl.isContextLost')
	(anonymous function) (index.js:960)
[Log] 16:54:50.068 – "status" – "exception: null is not an object (evaluating 'gl.isContextLost')" (index.js, line 169)
```

**Comment by vladmandic** [comment]
actually, can you paste the log using <https://vladmandic.github.io/human/demo/typescript/index.html> ?  
it should be more verbose since exception handler there is disabled by default, so it should show stack trace

**Comment by MaKleSoft** [comment]
> actually, can you paste the log using https://vladmandic.github.io/human/demo/typescript/index.html ?
it should be more verbose since exception handler there is disabled by default, so it should show stack trace

Here you go:

```
[Log] human version: – "2.5.1" – "| tfjs version:" – "3.11.0-20211108" (index.js, line 28)
[Log] platform: – "Macintosh; Intel Mac OS X 10_15_7" – "| agent:" – "Mozilla/5.0 AppleWebKit/605.1.15 Version/14.1.1 Safari/605.1.15" (index.js, line 28)
[Log] 17:02:49.227 – "Human:" – "version: 2.5.1" (human.esm.js, line 58)
[Log] 17:02:49.227 – "Human:" – "tfjs version: 3.11.0-20211108" (human.esm.js, line 58)
[Log] Error when getting WebGL context:  – TypeError: null is not an object (evaluating 'gl.isContextLost') — tfjs.esm.js:45072 (human.esm.js, line 46257)
TypeError: null is not an object (evaluating 'gl.isContextLost') — tfjs.esm.js:45072
[Log] 17:02:49.231 – "Human:" – "humangl webgl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 17:02:49.231 – "Human:" – "backend registered:" – "humangl" (human.esm.js, line 58)
[Log] 17:02:49.231 – "Human:" – "available backends:" – ["cpu", "webgl", "wasm", …] (4) (human.esm.js, line 58)
["cpu", "webgl", "wasm", "humangl"]Array (4)
[Log] 17:02:49.231 – "Human:" – "setting backend:" – "humangl" (human.esm.js, line 58)
[Log] 17:02:49.231 – "Human:" – "gl version:WebGL 1.0 renderer:WebKit WebGL" (human.esm.js, line 58)
[Log] 17:02:49.232 – "Human:" – "configuration:" – {backend: "humangl", modelBasePath: "../../models", wasmPath: "https://vladmandic.github.io/tfjs/dist/", …} (human.esm.js, line 58)
{backend: "humangl", modelBasePath: "../../models", wasmPath: "https://vladmandic.github.io/tfjs/dist/", debug: true, async: true, …}Object
[Log] 17:02:49.232 – "Human:" – "environment:" – Env {browser: true, node: false, worker: undefined, …} (human.esm.js, line 58)
Env {browser: true, node: false, worker: undefined, platform: "Macintosh; Intel Mac OS X 10_15_7", agent: "Mozilla/5.0 AppleWebKit/605.1.15 Version/14.1.1 Safari/605.1.15", …}Env
[Log] 17:02:49.232 – "Human:" – "tf flags:" – {IS_BROWSER: true, IS_NODE: false, DEBUG: false, …} (human.esm.js, line 58)
{IS_BROWSER: true, IS_NODE: false, DEBUG: false, CPU_HANDOFF_SIZE_THRESHOLD: 256, WEBGPU_CPU_HANDOFF_SIZE_THRESHOLD: 1000, …}Object
[Log] 17:02:49.278 – "Human:" – "load model:" – "../../models/blazeface.json" (human.esm.js, line 58)
[Log] 17:02:49.293 – "Human:" – "load model:" – "../../models/emotion.json" (human.esm.js, line 58)
[Log] 17:02:49.293 – "Human:" – "load model:" – "../../models/iris.json" (human.esm.js, line 58)
[Log] 17:02:49.293 – "Human:" – "load model:" – "../../models/facemesh.json" (human.esm.js, line 58)
[Log] 17:02:49.373 – "Human:" – "load model:" – "../../models/movenet-lightning.json" (human.esm.js, line 58)
[Log] 17:02:49.373 – "Human:" – "load model:" – "../../models/handtrack.json" (human.esm.js, line 58)
[Log] 17:02:49.373 – "Human:" – "load model:" – "../../models/handlandmark-full.json" (human.esm.js, line 58)
[Log] 17:02:49.373 – "Human:" – "load model:" – "../../models/faceres.json" (human.esm.js, line 58)
[Log] 17:02:49.373 – "Human:" – "tf engine state:" – 52887856 – "bytes" – 1475 – "tensors" (human.esm.js, line 58)
[Log] backend: – "humangl" – "| available:" – ["cpu", "webgl", "wasm", …] (4) (index.js, line 28)
["cpu", "webgl", "wasm", "humangl"]Array (4)
[Log] loaded models:8 (index.js, line 28)
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'gl.isContextLost')
	(anonymous function) (human.esm.js:83073)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise
```

**Comment by MaKleSoft** [comment]
> Similar for WebGPU unless WebGPU is enabled in experimental flags in browser (Safari->Settings->Advanced->Experimental Features->WebGPU)

Enabling `WebGPU` doesn't make a difference (Human will still use the `humangl` backend). **But enabling `WebGL 2.0` does fix the problem!**

**Comment by MaKleSoft** [comment]
> Using Chrome instead of Safari

Sorry, forgot to mention: It does work fine in the latest Chrome and Firefox.

**Comment by vladmandic** [comment]
> Enabling WebGPU doesn't make a difference (Human will still use the humangl backend).

`Human` runs several checks to see if browser supports `WebGPU` correctly before allowing its usage (`WebGPU` is still experimental), check output of `console.log(human.env.webgpu)` to see details.

>  But enabling WebGL 2.0 does fix the problem!

I cannot believe that Safari still hides WebGL v2 behind a flag and uses v1 by default as v2 was added in Safari 12 which is over 3 years ago!

> But enabling WebGL 2.0 does fix the problem!

Yup, I though that might work. Chrome and Firefox have WebGL v2 enabled by default  

Anyhow, I'll create a workaround for WebGL v1 (which is basically to disable some internal features if GL v1 is detected so performance will be slightly slower)

**Comment by MaKleSoft** [comment]
> I cannot believe that Safari still hides WebGL v2 behind a flag and uses v1 by default as v2 was added in Safari 12 which is over 3 years ago!

Yeah, well... I've stopped being surprised by this kind of BS from Safari a long time ago. Honestly I was surprised Safari is supported as well as it is 😄 The only thing worse than Safari right now (not counting IE) is Mobile Safari. I'll be testing there as well once you've published a fix.

Btw, I've also tested with v2.3.2 and no difference - in case that helps.

**Comment by MaKleSoft** [comment]
Btw, I appreciate the fast and helpful answer! I've only started looking into this project but so far I'm beyond impressed! Is there any way to donate or support you in some other way?

**Comment by vladmandic** [comment]
> Btw, I've also tested with v2.3.2 and no difference - in case that helps.

Didn't think it would, but wanted to check - human v2.5.1 is first release that uses my custom built `tfjs` and wanted to make sure that is not the cause in any way

`Human` by default uses `humangl` backend which my custom variation of `webgl` with some tweaks, but it requires `webgl` 2.0 (main difference is in startup time - its about 2.5x faster, but that makes it about 0.1x slower in inference which in my book is a good tradeoff)

[This patch](https://github.com/vladmandic/human/commit/62a735d348c71f7c6aced6914d0aa24f54eb244d) basically disables `humangl` and forces fallback to default `webgl`

New code is on github, still using same 2.5.1 tag (i'll wait few days to see if there are more issues with 2.5.1 before publishing 2.5.2)

Also added a trivial fix to TFJS itself: <https://github.com/tensorflow/tfjs/pull/5825>

> Btw, I appreciate the fast and helpful answer! I've only started looking into this project but so far I'm beyond impressed! 

thanks!

> Is there any way to donate or support you in some other way?

no donations needed  
support? i welcome any suggestions and contributions!

**Comment by vladmandic** [comment]
quick update: my patch for `tfjs` is approved & merged to master branch which triggered new build of `@vladmandic/tfjs` and `human` - new ci pipeline reduces this process from months waiting for a release to hours!

**Comment by MaKleSoft** [comment]
Awesome. Thanks for the update!
