### ISSUE TITLE
'ls' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#21]
**Issue Description**
'ls' is not recognized as an internal or external command,

**Steps to Reproduce**
npm run build
**Expected Behavior**
ls should work.  I don't think this is a valid command in windows
**Environment
Windows 10
Node 15.0.1
npm 7.0.3

**Additional**
   "build": "rimraf dist/* && npm run build-iife && npm run build-esm-bundle && npm run build-esm-nobundle && npm run build-node && npm run build-node-nobundle && npm run build-demo &&` ls `-l dist/",

**Comment by vladmandic** [comment]
true. and `ls` is really not needed anymore, i used it in early versions to monitor build process. since it's stable, i'm just removing ls completely from build.
new version is published.

**Comment by vladmandic** [comment]
can you confirm it works on windows? it should, but i haven't had time to fully test it yet.

**Comment by delebash** [comment]
It is working.
