### ISSUE TITLE
human.detect only returns one face when there are two in the image

### ISSUE THREAD

**Issue by brendon** [vladmandic/human#210]
**Issue Description**
I'm probably missing something in the configuration but is there a way to return all the faces detected in an image? So far I only seem to get one returned.

**Steps to Reproduce**
Issue `human.detect` without any configuration.

**Expected Behavior**
I'd expect to receive an array of detected faces.

**Environment**
Node
```
    "@tensorflow/tfjs-node": "^3.11.0",
    "@vladmandic/human": "^2.5.1",
```

**Comment by vladmandic** [comment]
set `config.detector.maxDetected` to any number

default is 1 as most common use-case is real-time processing of a single person in front of webcam, but `human` is tested with images containing very large number of faces

higher number of faces to process, lower the performance - thus default cutoff

**Comment by brendon** [comment]
Thanks @vladmandic, of course I found that just after posting the issue! :D

If maxDetected is set to 1, is it the face with the highest confidence score?

**Comment by vladmandic** [comment]
its the face with highest detection score (seen in results as `boxScore`) and actual face analysis for other possible boxes is skipped, so it is possible (in theory, but rarely in real-world) that some other face would have higher `faceScore` (which comes from face analysis)  

overall `score` is combination of `boxScore` and `faceScore`

**Comment by brendon** [comment]
That's perfect. I'm really only after the 'highest' result anyway :)
