### ISSUE TITLE
cropSize must be atleast [1,1]

### ISSUE THREAD

**Issue by accidentalChange** [vladmandic/human#213]
This used to work in previous versions (I think since 2.4.1) 

I am just using the face detector without mesh or rotation.

The error comes from human.esm.js from the call to **correctFaceRotation**

Here is my configuration:

`
const humanConfig = {
  backend: 'wasm' as 'wasm',
  modelBasePath: 'https://cdn.jsdelivr.net/npm/@vladmandic/human@2.5.1/models',
  debug: false,
  async: true,
  warmup: 'face' as 'face',
  cacheSensitivity: 0,
  skipAllowed: false,
  deallocate: false,
  filter: { enabled: false },
  gesture: { enabled: false },
  face: {
    enabled: true,
    detector: {
      rotation: false,
      maxDetected: 5,
      return: false,
    },
    mesh: { enabled: false },
    iris: { enabled: false },
    emotion: { enabled: false },
    description: { enabled: false },
    antispoof: { enabled: false },
  },
  body: { enabled: false },
  hand: { enabled: false },
  object: { enabled: false },
  segmentation: { enabled: false },
};
`

Also attempted to do a minimal replication project check the console when running it.

Thank you

[stackblitz reproduction url](https://stackblitz.com/edit/typescript-kweatt?file=index.ts)

**Comment by vladmandic** [comment]
my bad, mistake during last optimization of the face module - **when mesh is disabled**, it should fall back to use detector size  
new code is on `github` and new version will be published on `npmjs` next week.
