### ISSUE TITLE
Issues identifying a face

### ISSUE THREAD

**Issue by brendon** [vladmandic/human#216]
**Issue Description**

See the attached file:

https://www.dropbox.com/t/ZeQmLIHdj2TEJVvc

The tensor is:

```
Tensor {
  kept: false,
  isDisposedInternal: false,
  shape: [ 1, 2448, 3264, 3 ],
  dtype: 'float32',
  size: 23970816,
  strides: [ 23970816, 9792, 3 ],
  dataId: {},
  id: 1412,
  rankType: '4',
  scopeId: 1316
}
```

But I get the following face:
```
{
      id: 0,
      mesh: [],
      meshRaw: [],
      box: [Array],
      boxRaw: [Array],
      score: 0,
      boxScore: 0.77,
      faceScore: 0,
      annotations: {},
      age: 29.7,
      gender: 'unknown',
      genderScore: 0,
      embedding: [Array],
      emotion: [Array],
      real: null,
      iris: 0,
      rotation: [Object],
      tensor: null
    }
```

```
[{"box":[0,0,0,0],"boxRaw":[0,0,0,0]}]
```

I tried a smaller copy of the image and it worked. Is there some kind of upper limit for the image processor?

**Steps to Reproduce**

Nothing special.

**Expected Behavior**

Expect a face to be found.

**Comment by vladmandic** [comment]
limits are system specific, i just tried your image and it works ok on my system  

but exactly that reason there is `human.config.filter.width` or `human.config.filter.height` property which can be set to any number and forces input to be resized if larger than that number. so if you set `human.config.filter.width=1000` any images larger than 1000px width will be resized (and if height is not set, it will be resized to keep same aspect ratio)

see documentation at <https://vladmandic.github.io/human/typedoc/interfaces/FilterConfig.html>

currently default is set to `0` which means no resizing but i'll set default value for future versions to `2048` as there is no value of larger inputs anyhow

**Comment by brendon** [comment]
Thanks @vladmandic, I'll have a go with those settings. I suspect it might be an issue with `express` and the `fileUpload` plugin and limits there. Much appreciated :)

**Comment by brendon** [comment]
Hi @vladmandic, unfortunately setting a width didn't work. I tried bypassing `express` and loading the file straight off the filesystem in case it was an issue with `express` but I still get the strange "yes there's a face but I'm not telling you where" result. This is the node app I'm running:

```
const pick = require('lodash/pick')
const map = require('lodash/map')

const fileUpload = require('express-fileupload')

const tf = require('@tensorflow/tfjs-node') // Required
const Human = require("@vladmandic/human").default
const app = require("express")()

const human = new Human({
  modelBasePath: 'file://../../node_modules/@vladmandic/human/models'
})

app.use(fileUpload({
  limits: {
    fieldSize: 60 * 1024 * 1024,
    fileSize: 60 * 1024 * 1024
  }
}))

const configuration = {
  backend: 'tensorflow',
  face: {
    enabled: true,
    detector: { maxDetected: 10 }
  },
  body: { enabled: false },
  hand: { enabled: false },
  gesture: { enabled: false },
  filter: { enabled: true, width: 2048 }
}

app.post("/detect", (req, res) => {
  if (req.files.image.truncated) {
    res.json([])
  } else {
    const tensor = human.tf.tidy(() => {
      const decode = human.tf.node.decodeImage(req.files.image.data, 3)

      let expand
      if (decode.shape[2] === 4) { // RGBA -> RGB Conversion
        const channels = human.tf.split(decode, 4, 2)
        const rgb = human.tf.stack([channels[0], channels[1], channels[2]], 2)
        expand = human.tf.reshape(rgb, [1, decode.shape[0], decode.shape[1], 3])
      } else {
        expand = human.tf.expandDims(decode, 0)
      }
      return human.tf.cast(expand, 'float32')
    })

    human.detect(tensor, configuration).then(result => {
      res.json(
        map(result.face, (face) => {
          return pick(face, ['box', 'boxRaw'])
        })
      )
    }).catch(() => {
      res.status(500).send("Unable to process the image for faces.")
    }).finally(() => {
      human.tf.dispose(tensor)
    })
  }
})

human.tf.ready()
  .then(human.load())
  .then(app.listen(3010))
```

To use it: 

```curl -F 'image=@Zoe_D_with_Henry.JPG' http://127.0.0.1:3010/detect```

I've had a good look through your `node.js` example but can't see any additional config that would make a difference.

**Comment by vladmandic** [comment]
- remove `if (decode.shape[2] === 4)` (leave only part under else), that part is obsolete since `decodeImage` already has a fixed param `3`
- add `console.log(tensor.shape)` just before `human.detect`
- capture actual error! you're silently ignoring it, so no chance of seeing what went wrong. never silently ignore errors.
- force cache disable (in your case it will always be false anyhow for each upload, so lets skip that code, i think that is where it goes wrong). `configuration.cacheSensitivity=0`

```js
}).catch((err) => {
      console.error(err);
      res.status(500).send("Unable to process the image for faces.")
```

**Comment by brendon** [comment]
Thanks @vladmandic :)

I was actually reporting any caught errors out via Bugsnag but I stripped that code out to make the app simpler :)

Running it with your modifications yields no error (a result is generated): `[{"box":[0,0,0,0],"boxRaw":[0,0,0,0]}]` so the same result. The tensor logs out as: `[ 1, 2448, 3264, 3 ]`.

**Comment by vladmandic** [comment]
is there anything in `result.error` after `human.detect`?
and did you disable cache?

**Comment by brendon** [comment]
No, no `result.error` and the cache is disabled:

```
const configuration = {
  backend: 'tensorflow',
  face: {
    enabled: true,
    detector: { maxDetected: 10 }
  },
  body: { enabled: false },
  hand: { enabled: false },
  gesture: { enabled: false },
  filter: { enabled: true, width: 2048 },
  cacheSensitivity: 0
}
```

**Comment by brendon** [comment]
This is the output from boot:

```
2021-11-17 12:30:21.407737: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
12:30:21.578 Human: version: 2.5.1
12:30:21.578 Human: tfjs version: 3.11.0
12:30:21.578 Human: available backends: [ 'cpu', 'tensorflow' ]
12:30:21.580 Human: setting backend: tensorflow
12:30:21.635 Human: load model: file://../../node_modules/@vladmandic/human/models/blazeface.json
12:30:21.644 Human: load model: file://../../node_modules/@vladmandic/human/models/emotion.json
12:30:21.676 Human: load model: file://../../node_modules/@vladmandic/human/models/iris.json
12:30:21.692 Human: load model: file://../../node_modules/@vladmandic/human/models/facemesh.json
12:30:21.779 Human: load model: file://../../node_modules/@vladmandic/human/models/handtrack.json
12:30:21.852 Human: load model: file://../../node_modules/@vladmandic/human/models/movenet-lightning.json
12:30:21.897 Human: load model: file://../../node_modules/@vladmandic/human/models/handlandmark-full.json
12:30:21.961 Human: load model: file://../../node_modules/@vladmandic/human/models/faceres.json
12:30:21.962 Human: tf engine state: 52887856 bytes 1475 tensors
```

**Comment by vladmandic** [comment]
found the issue, but you're not going to like it as i don't have a solution :(

its nothing to do with either image size or `human` library in general  

the problem is decoding JPG - basically, this JPG is taken with old iPhone 6 which wrote it in portrait mode with EXIF flag
```text
Orientation: Rotate 90 CW
```
which is wrong format for that flag
browsers deal with it somehow, but none of jpg decoding libraries for node i've tried do

anyhow, human does find something, but it has a hard time working with photo which is rotated 90 degrees.

as soon as i opened image in a any photo editing software and saved it, it works

**Comment by brendon** [comment]
I had a funny feeling it might have been something like that. This is pretty obscure so I might just add a check for a zero sized face and skip it. I'll have a hunt also to see if I can find something to correct the rotation and post back here if I find anything.

Thank you so much for your support :)

**Comment by vladmandic** [comment]
using `node-canvas` works *partially*, image is still not fully correctly decoded as some segments are actually missing, but it does handle orientation. you can check `demo/nodejs/node-canvas` on how to use that external library for decoding.

![zoe](https://user-images.githubusercontent.com/57876960/142091365-091450ea-8bca-4a12-aa69-59b4e3f322d7.jpg)

**Comment by brendon** [comment]
Thanks @vladmandic, I'll definitely look into that. In this current situation I have the good fortune to be using `imagemagick` already to create a few different size variations of these images so I'm just passing through one of those instead of the original.
