### ISSUE TITLE
Tensor leak when calling detect with specific configuration.

### ISSUE THREAD

**Issue by lambdacerro** [vladmandic/human#232]
Internal Tensorflow tensor count keeps increasing as further detect calls are being made, disabling return in the detector fixes the leak.

```
    const human = new Human({
        debug: false,
        modelBasePath: 'file://models/',
        cacheSensitivity: 0,
        deallocate: true,
        face: {
            enabled: true,
            detector: { maxDetected: 10, return: true, cropFactor: 1.2 },
            mesh: { enabled: true },
            iris: { enabled: false },
            description: { enabled: true },
            emotion: { enabled: false },
        },
        hand: {
            enabled: false,
        },
        // body: { modelPath: 'blazepose.json', enabled: true },
        body: { enabled: false },
        object: { enabled: false },
    });
    await human.load();
    await human.warmup();
    const buffer = fs.readFileSync(inputFile);
    console.log(human.tf.engine().memory().numTensors);
    let tensor;
    for (let i = 0; i < 100; i++)
    {
        tensor = human.tf.node.decodeImage(buffer);
        await human.detect(tensor);
        human.tf.dispose(tensor);
    }
    console.log(human.tf.engine().memory().numTensors);
```

Both tensor counts before and after should match.

Nodejs 16.3, both windows and linux, tfjs-node

- Human library version? 2.5.6
- Built-in demo or custom code? Custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)? 3.11.0
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? Node 16.3
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Windows 10 and Ubuntu 18
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

```
2021-12-27 19:53:05.826991: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
19:53:05.900 Human: version: 2.5.6
19:53:05.901 Human: tfjs version: 3.11.0
19:53:05.902 Human: available backends: [ 'cpu', 'tensorflow' ]
19:53:05.905 Human: setting backend: tensorflow
19:53:05.951 Human: load model: file://models/blazeface.json
19:53:05.961 Human: load model: file://models/facemesh.json
19:53:05.999 Human: load model: file://models/faceres.json
19:53:05.999 Human: tf engine state: 17459532 bytes 366 tensors
19:53:06.277 Human: Warmup full 276 ms
367
767
Warming up human
Warming up human
```

**Comment by vladmandic** [comment]
this works as intended  

you have `config.face.detector.return = true` *(default is false)*  
which means that face results will include face tensor as well  

either set it to false if you don't need it or if you do need it, then manually deallocate it once you're done with it.

for example:

```js
    const res = await human.detect(tensor);
    if (res && res.face) res.face.forEach((face) => human.tf.dispose(face.tensor));
```

**Comment by lambdacerro** [comment]
My bad, that's why I didn't want to create an issue first, I was thinking that the return option was to return the embedded array in order to compare faces.

**Comment by vladmandic** [comment]
no, that's `face.description` option.

`face.return` is to return face tensor, idea is if you want to use some other model as well to run on a face, you already have pre-processed and cropped tensor of a face ready. it's the clone of the same tensor that is used as input for description/emotion/age/gender built-in models.

**Comment by zmk-punchbowl** [comment]
> this works as intended
> 
> you have `config.face.detector.return = true` _(default is false)_ which means that face results will include face tensor as well
> 
> either set it to false if you don't need it or if you do need it, then manually deallocate it once you're done with it.
> 
> for example:
> 
> ```js
>     const res = await human.detect(tensor);
>     if (res && res.face) res.face.forEach((face) => human.tf.dispose(face.tensor));
> ```

When using this method of disposal, i am logging `face.tensor` before passing it to `dispose` and it is `undefined`. I'm assuming that's not expected and, if so, that the disposal is not working? I'm tracking down a memory leak in our application and seem to have isolated it to this code:

```
  const tensor = (await getHuman()).tf.node.decodeImage(buffer);
  const res = await (await getHuman()).detect(tensor);

  // Dispose all tensors
  if (res?.face) {
    res.face.forEach(async (f: FaceResult) => {
      console.log(`Disposing tensor`, f.tensor);
      (await getHuman()).tf.dispose(f.tensor);
    });
  }
```

The `getHuman` function initializes `human` the first time around and then returns the already-initialized version after that.

**Comment by zmk-punchbowl** [comment]
I tried adding this, too:

```
  if (tensor) {
    console.log(`Disposing tensor`, tensor);
    (await getHuman()).tf.dispose(tensor);
  }
```

In this case, `tensor` is indeed defined. However, I do not notice a decrease in memory usage by the process. If I exclude all of this code (in the previous post), the process exhibits reasonable memory usage.

**Comment by zmk-punchbowl** [comment]
I created #481 instead of adding to this already-closed issue.
