### ISSUE TITLE
WASM not working

### ISSUE THREAD

**Issue by djthegr8** [vladmandic/human#24]
**Issue Description**
WASM doesn't work in the demo
**Steps to Reproduce**
Simply go to the demo site and set backend to wasm
![image](https://user-images.githubusercontent.com/44142719/98509765-d1293480-2287-11eb-8a8f-e6ef487efffb.png)

**Expected Behavior**
Sets properly
**Environment
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 86) Chrome, Edge
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10) Win10
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)

**Additional**
- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by djthegr8** [comment]
Have uncommented the scripts, now am getting the below
![image](https://user-images.githubusercontent.com/44142719/98510066-73e1b300-2288-11eb-9369-131976aa495e.png)

**Comment by djthegr8** [comment]
Also, how do I disable the persistent loading of _all_ models????

**Comment by vladmandic** [comment]
WASM doesn't work in the demo

index.html was loading wrong script, fixed and pushed new version  

    Also, how do I disable the persistent loading of all models????

See bottom of `demo/browser.js`:

```js
  // this is not required, just pre-loads all models
  if (ui.modelsPreload) {
    status('loading');
    await human.load(userConfig);
  }
  // this is not required, just pre-warms all models for faster initial inference
  if (ui.modelsWarmup) {
    status('initializing');
    const warmup = new ImageData(256, 256);
    await human.detect(warmup, userConfig);
  }
```

**Comment by djthegr8** [comment]
Alright...
