### ISSUE TITLE
Electron app not working

### ISSUE THREAD

**Issue by avestaHarsh** [vladmandic/human#243]
I am using the face comparison feature in my electron app. On the laptop (with default camera) it's working fine but when I try to run this app in the system(PC) (which does not have a default camera), also I have tried setting external webcam in the system, the app is not starting even not getting any errors/warnings. 

**Environment**

Human library version: **2.3.2**
TensorFlow/JS version : **3.9.0**
NodeJS and version : **14.17.6**
OS : **Ubuntu(18.04.5) Linux on x64**
Electron version : **12.0.18**
RAM : **8 GB**
Processor : **Intel® Core™ i3-3220 CPU @ 3.30GHz × 4** 

Below is my configuration for Human.

```
humanConfig: {
		async: true,
		warmup: 'face',
		backend: 'webgl',
		modelBasePath: process.env.NODE_ENV !== 'staging' ? modelPath : `${app.getAppPath()}${modelPath}`,
		filter: {
			enabled: true,
			flip: true
		}
       }
```
Note: I have also checked with the updated latest version of the Human Library (**2.6.1** npm package), TensorFlow/JS (**3.13.0** npm package), and checked in i5 processor CPU but still not working.

**Comment by vladmandic** [comment]
there have to be some errors/warnings, did you open browser inspector window (it exists even in electron) and see what's written there?

**Comment by avestaHarsh** [comment]
> there have to be some errors/warnings, did you open browser inspector window (it exists even in electron) and see what's written there?

The app does not start itself. so the browser inspector window will not be prompt.

Here Is the terminal screen. 
![Screenshot from 2022-01-21 18-01-52](https://user-images.githubusercontent.com/16647220/150527655-42bd836d-5cc3-4bbd-a846-466f606b2e7d.png)

All I came to know after spending a day is, the app is crashed while I am creating an instance of Human class.

`const human = new Human(humanConfig)`

**Comment by vladmandic** [comment]
So the EXE you've built works on your notebook, but completely fails to start on your desktop system?

What you've just posted is build log (and PLEASE, post such items as text, not as image screenshots) but that should not be relevant since EXE is already built?

> All I came to know after spending a day is, the app is crashed while I am creating an instance of Human class.

Enable **ElectronJS** logging (see <https://www.electronjs.org/docs/latest/tutorial/application-debugging/> and post what happens

Without actual error, nothing I can do.

**Comment by avestaHarsh** [comment]
> So the EXE you've built works on your notebook, but completely fails to start on your desktop system?

Yes, whatever I have developed/built is working on my laptop but not working on a desktop.

> 
> What you've just posted is build log (and PLEASE, post such items as text, not as image screenshots) but that should not be relevant since EXE is already built?
> 
> > All I came to know after spending a day is, the app is crashed while I am creating an instance of Human class.
> 
> Enable **ElectronJS** logging (see https://www.electronjs.org/docs/latest/tutorial/application-debugging/ and post what happens
> 
> Without actual error, nothing I can do.

I got this error in the console.

```
Uncaught Error: EBADF: bad file descriptor, write internal/fs/utils.js:307
at writeSync (fs.is:711)
at SyncWriteStream,write (internal/fs/sync write strean.js:24)
at writeOrBuffer (internal//streams writable.js:358)
at SyncWriteStream.Writable.write (internal streams writable.js:303)
at EventEmitter. log.write (/home/upd2/Downloads Lis/npmlog/log.js:271)||
at EventEmitter. canonymous: (/home/upc2/Downloads...s npmlog/log.js:234)
at Array.forEach anonymous at EventEmitter. log.emitlog (/home/upc2 Downloads...se/npmlog/log.js:232)
at EventEmitter <canonymous> (/home/upc2/Downloads.us/npmlog/log.js:214)
at EventEmitter <canonymous> (/home/upc2/Downloads...s/npmloo/log.is:286)
```

**Comment by vladmandic** [comment]
this error is an issue with your electronjs logging - it cannot open a log file and it aborts with unhandled error.

**Comment by avestaHarsh** [comment]
> this error is an issue with your electronjs logging - it cannot open a log file and it aborts with unhandled error.

To overcome the above error I have tried with close electronjs logging, and the error was gone but still unable to start the app.

The issue with below line, something is wrong with the default config value.
`const human = new Human(humanConfig)`

If I am commenting above line then the app starts smoothely.

**Comment by vladmandic** [comment]
I'd love to help, but I need an actual error to be able to do anything  

Check `ElectronJS` documentation on how to display browser console log and post entire log here  
I don't use `ElectronJS` at the moment, but there are plenty of hints in this thread:
<https://stackoverflow.com/questions/31759367/using-console-log-in-electron-app>

**Comment by avestaHarsh** [comment]
> I'd love to help, but I need an actual error to be able to do anything
> 
> Check `ElectronJS` documentation on how to display browser console log and post entire log here I don't use `ElectronJS` at the moment, but there are plenty of hints in this thread: https://stackoverflow.com/questions/31759367/using-console-log-in-electron-app

At the time of **compiling**, something goes wrong at below line 

`const human = new Human(humanConfig)`

that's why I have debugged today in the library (more specifically in Human class, namely human.ts (under src folder) / human.esm.js(under dist folder)) and tried to console logs but nothing consoled anything.

I am curious to know, Does Human class looking for a default camera by default and my desktop does not have a default one and my laptop does have so it works well? 

Currently, I have set `backend: 'webgl'` , `async: true`,  `warmup: 'face'` for face comparison, do I make any mistake here? Do I need to change the backend for the electron app? 

(Also I have tried with add an additional webcam to the desktop before compiling my app).

**Comment by vladmandic** [comment]
Human does not look for input at all at the time of creating an instance. It only looks at input once you call `human.detect(input)`  
Even then, it doesn't care about WebCam - it uses HMTLElement you pass - Image, Video, Canvas, etc.  

Re: WebGL - I don't see why that would matter in Electron.

But you can simplify startup by saying `warmup: 'none'` so it just creates a class instance without triggering any work at the startup time.

Again, why don't you enable proper logging and see whats actually going on?  
Human logs everything to console and its very informative - any error will be immediately visible

**Comment by vladmandic** [comment]
closing the issue as no actual information or logs were provided so far (its been over 10 days).  
once logs are available, issue can be reopened.
