### ISSUE TITLE
DOMException: Failed to execute 'texSubImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [vladmandic/human#244]
**Issue Description**
I want to detect all AI analysis on local video file ( not by input uploading ) but when i tried by code i get this error
my code is 
```
<video id="video" ref={localVideoref}  
      controls muted
      autoPlay={true}
      >
      </video>
      <button onClick={onClickLoadedData} >
        click
      </button>
```
```

const onClickLoadedData = async () =>{
    console.log('loaded all data');
    const inputVideo = localVideoref.current;
    inputVideo.src= "http://localhost:4025/images/videos/RecordRTC-2022021-2fva5fvao7a.mp4"
    inputVideo.play();
    inputVideo.onloadeddata = () => process();
  }
```
```
const process = async () => {
    const video = localVideoref.current;
    if (video.readyState > 2 && !video.paused)  {
      console.log('//////////////////');
      const res = await human.detect(video);      
    }
    // requestAnimationFrame(() => process()); // trigger processing loop as soon as previous processing has finished
    // setTimeout(() => process, 5000) // trigger processing loop every 5 seconds
  }
```

```
Uncaught (in promise) DOMException: Failed to execute 'texSubImage2D' on 'WebGL2RenderingContext': Tainted canvases may not be loaded.
    at http://localhost:3001/static/js/vendors~main.chunk.js:61280:33
    at callAndCheck (http://localhost:3001/static/js/vendors~main.chunk.js:57889:23)
    at uploadPixelDataToTexture (http://localhost:3001/static/js/vendors~main.chunk.js:61280:7)
    at GPGPUContext.uploadPixelDataToTexture (http://localhost:3001/static/js/vendors~main.chunk.js:61432:5)
    at Object.fromPixels2 [as kernelFunc] (http://localhost:3001/static/js/vendors~main.chunk.js:70251:18)
    at kernelFunc3 (http://localhost:3001/static/js/vendors~main.chunk.js:9602:22)
    at http://localhost:3001/static/js/vendors~main.chunk.js:9667:19
    at _Engine.scopedRun (http://localhost:3001/static/js/vendors~main.chunk.js:9487:19)
    at _Engine.runKernelFunc (http://localhost:3001/static/js/vendors~main.chunk.js:9665:10)
    at _Engine.runKernel (http://localhost:3001/static/js/vendors~main.chunk.js:9541:17)
    at fromPixels_ (http://localhost:3001/static/js/vendors~main.chunk.js:12504:19)
    at Object.fromPixels__op (http://localhost:3001/static/js/vendors~main.chunk.js:10342:22)
    at process2 (http://localhost:3001/static/js/vendors~main.chunk.js:90733:36)
    at http://localhost:3001/static/js/vendors~main.chunk.js:106579:25

```
**Steps to Reproduce**

**Expected Behavior**
get results of detected faces from playing video;

**Environment**
- Human library version? 
- 2.5.8
- Built-in demo or custom code? 
- custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? 
- Browser
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Windows 10
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- webpack
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?
- React

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
This is not `Human` issue, this is a security enforcement by all modern browsers - pixel data from images and videos loaded from an URL different than app itself cannot be read and when attempting to do so, browser rejects read and reports 'Tainted canvases may not be loaded.'

Two possible solutions:
- Make sure that app and video are loaded from the same base URL  
  For example, if you can load video using **relative** path like </images/videos/RecordRTC-2022021-2fva5fvao7a.mp4> (so not FQDN such as <http://localhost:4025/...>), then it will work
- Set **CORS header** to allow on the http server that is serving video
  for example, `Access-Control-Allow-Origin: *`
