### ISSUE TITLE
Correct .wasm path.

### ISSUE THREAD

**Issue by shabashaash** [vladmandic/human#249]
**Issue Description**
So Im very sorry for such a stupid question but Im really new to web development and vue. 
I have vue-cli dev server as backend and Im trying to load 'blazeface' model on browser for face detection. The main idea is that backend should just host static-like page and provide files, while the fronted with .wasm should do all the work. 

I have tfjs-backend wasms in my 'public/wasm' folder.
 I have config like that:
```json
{
        cacheSensitivity: 0,
        deallocate: false,
        cacheModels: true,
        async:true,
        debug:true,
        wasmPath:"./wasm/",
        return:true,
        backend:'wasm',
        gesture: {
            enabled: false,
        },
        face: {
            enabled: true,
            detector: {
              modelPath: 'blazeface.json',
              maxDetected: 50,
              minConfidence: 0.3,
              iouThreshold: 0.1
            },
            mesh: {
              enabled: false
            },
            iris: {
              enabled: false
            },
            emotion: {
              enabled: false
            },
            description: {
              enabled: false
            }
        },
        body: {
            enabled: false
        },
        hand: {
        enabled: false
        }
}
```
 (Btw I think I have some defaults here, Im gonna fix that later)

So when Im loading the page im getting this warnings:
![sample](https://user-images.githubusercontent.com/43162766/153514756-1c8a6e09-875b-4d9d-9444-230eae8fcf06.png)
As like the path is not right. And Human just intialize with any supported backend (webgl).

But file is actually loading I think:
![sample2](https://user-images.githubusercontent.com/43162766/153515238-9035c29d-a35b-45d7-872c-ef6ace09a3ba.png)
![sample3](https://user-images.githubusercontent.com/43162766/153516671-1697c0ab-1189-4cf8-8dad-490b823ce7dc.png)

Also when Im using onnx-runtime for another model on same vue app I can get wasm files from 'public/js' folder. 

P.S I also have troubles with SIMD, but with onnx-runtime SIMD mode works fine. (I enabled everying I need in about:config and passing the needed headers)
**Steps to Reproduce**
vue-cli sample app and just trying to initialize the model with cutom wasm path) 
**Expected Behavior**

**Environment**

- Human library version?
Human: version: 2.6.2
Human: tfjs version: 3.13.0-20220207
- Built-in demo or custom code? 
Custom
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
esm + bundler (webpack)
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
Firefox 84.0.2
node 12.16.1 (I must update it like right now lol)
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
Win10
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
webpack
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?
Vue3

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
```json
{
  "name": "sample-vue",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "@tensorflow/tfjs": "^3.13.0",
    "@tensorflow/tfjs-backend-wasm": "^3.13.0",
    "@vladmandic/human": "^2.6.2",
    "blueimp-load-image": "^5.16.0",
    "core-js": "^3.6.5",
    "onnxruntime-web": "^1.10.0",
    "vue": "^3.0.0",
    "vue-ellipse-progress": "^2.1.0",
    "vue3-dropzone": "0.0.7"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-vue": "^7.0.0"
  },
  "eslintConfig": {
    "root": true,
    "env": {
      "node": true
    },
    "extends": [
      "plugin:vue/vue3-essential",
      "eslint:recommended"
    ],
    "parserOptions": {
      "parser": "babel-eslint"
    },
    "rules": {}
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not dead"
  ]
}

```

UPD:

So I revisited the onnx-runtime version and actuially find out why I can retrieve .wasm files from public folder. 
(Last answer here)
https://github.com/microsoft/onnxruntime/issues/9322

~~So if I get it right I should just set my bundler with some plugns (Copy plugin for example) to serve files in folders I needed.~~

**Comment by vladmandic** [comment]
thanks for posting detailed issue, it helps.  
unfortunately, i don't use vue so not really sure what went wrong, but from the information provided it seems that `wasm` files do get loaded, but they look corrupt.

first of all, can you confirm that browser inspector network tab shows code 200 for requests for wasm files and url path is as you'd expect?

but otherwise, this sounds eerie familiar to another currently open issue #248 for which i've just posted a possible patch on github (not yet published as npm) - can you check?

**Comment by shabashaash** [comment]
1. Yeah I am getting 200 and url is right. I get this .wasm files from tsjs-backend-wasm. 
2. I installed newer ESM version in node (with github link) and set wasmPlatformFetch: true. Now Im getting this:
![sample](https://user-images.githubusercontent.com/43162766/153607083-8bc71862-16b6-4f01-9bb2-7666ad0ef94a.png)
Im getting the same error when using your workaround. 
Here is the code with error:
```js
export async function createModelCpu(model){
    const config = init();
    config.backend = 'wasm';
    config.modelBasePath = model;
    const human = new Human(config);
    console.log('before_wasmtf');
    await human.load(); //ERROR HERE
    console.log(human);
    return human;
}
```
Im awating this function in main code.
Also I updated node to latest version and packages accordingly.

**Comment by vladmandic** [comment]
silly question, but why is it reporting that simd is not supported? chrome supports it out-of-the-box for a while now, only older versions required experimental flag.

anyhow, this looks quite different than previous error - but unfortunately, there is no error reported - its blank, just rejected promise. normally i'd expect that can be expanded in browser to show call stack?

one more thing, can you add `await human.init()` before `load()` and add console output before/after?  
that function is implicit if not already performed, so load would call init, but for this case its best to call it explicitly since thats where wasm loading happens.

**Comment by shabashaash** [comment]
I am on firefox, but yeah I think SIMD is supported.

I tried to catch the error for stack trace but no luck. Im just getting the same error, and code just keeps going.

I added await human.init():
![sample](https://user-images.githubusercontent.com/43162766/153681472-242e58bd-cee4-4174-bbc7-a2a77a30d498.png)

**Comment by shabashaash** [comment]
I managed to kinda catch the error with 'unhandledrejection' EventListener this is what Im getting:
![sample](https://user-images.githubusercontent.com/43162766/153683062-ac919fcc-e4e2-421c-9c15-16e5191d8f71.png)

Seems like the error before. I wonder if wasm files are corrupted but I downloaded them straight from https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.9.0/dist/

**Comment by vladmandic** [comment]
You downloaded 3.9.0, but this version of Human is based on TFJS 3.13.0 - versions **must** match.

**Comment by shabashaash** [comment]
Oh sorry my bad. I got two tabs with 9 and 13 version and copied the wrong link. But anyway I deleted all old files and downloaded from https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@3.13.0/dist/, still same error.

**Comment by vladmandic** [comment]
WASM SIMD support in Firefox should also be available - can you go to `about:config` and then check `javascript.options.wasm_simd` ?

Any chance you can try with Chrome as a test?  
Not just because of SIMD, but I'm hoping it would show more in the backtrace.

**Comment by vladmandic** [comment]
its definitely loading and attempting to initialize, but then failing inside wasm code - that normally happens with incorrect version since entry point map does not match, but haven't seen that happen otherwise.  

can you try with wasm files from <https://github.com/vladmandic/tfjs/tree/main/dist>?

**Comment by shabashaash** [comment]
IT WORKED. Thank you so much. And sorry for the wasted time.

**Comment by vladmandic** [comment]
I'm glad it worked!

**Comment by robksawyer** [comment]
I'm trying to use the library with nextjs and I'm getting the following issue. 
```failed to inference ONNX model: Error: no available backend found. ERR: [wasm] RuntimeError: abort(both async and sync fetching of the wasm failed). Build with -s ASSERTIONS=1 for more info..```

It's trying to load the files from ```http://localhost:3000/_next/static/chunks/ort-wasm-simd.wasm 404 (Not Found)```

**Comment by vladmandic** [comment]
i've recently updated the wasm path to correct one, but didn't push new release to npmjs - and cdn mirrors npmjs. will do it soon.
