### ISSUE TITLE
What's the branching model/practice of this repo?

### ISSUE THREAD

**Issue by timepp** [vladmandic/human#253]
I noticed that there is a release brance forked from very begining which is merely repeating all the things in main branch, except that all the dist (i.e. build output) are added to this branch. 

I know that this practice can help main branch clean. But what's the tooling/flow to maintain the release branch? Does the author need to cherry-pick each commit whenever a new commit happen in main? 

Is this a common practice across github?  Just willing to learn about it, thanks.

**Comment by vladmandic** [comment]
i keep it very simple:
- main branch is always kept stable and considered as latest,  
  there are no separate branches used to do dev work
- all releases are just versioned tags (using semver versioning)  
  and automatically pushed to npmjs as well
- major releases are additionally tagged as release and archived  
  at <https://github.com/vladmandic/human/releases>

is it common? for multi-team projects, it may be needed to have feature branches  
but for smaller teams, i find it much more productive to use single dev branch as a forcing function to keep it stable  
plus any dev work should happen on up-to-date local clone - dev should do a pull to sync with main before any work  
that way there are no conflicts, no cherry picking on commits and no complex merges  

if you have any specific questions, let me know
