### ISSUE TITLE
How disable all models and work only with face and face recognition

### ISSUE THREAD

**Issue by shurshilov** [vladmandic/human#257]
I try use this, but body tracking age still detect and it very slowly          
  const myConfig = {
                debug:false,
                modelBasePath: '/hr_attendance_face_recognition_pro/static/src/js/models',
                main: { // processes input and runs gesture analysis
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: false },
                    object: { enabled: false },
                    gesture: { enabled: false },
                    hand: { enabled: false },
                    body: { enabled: false },
                    segmentation: { enabled: false },
                  },
                  face: { // runs all face models
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: true },
                    object: { enabled: false },
                    gesture: { enabled: false },
                    hand: { enabled: false },
                    body: { enabled: false },
                    segmentation: { enabled: false },
                    description: { enabled: true },
                  },
                  body: { // runs body model
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: false },
                    object: { enabled: false },
                    gesture: { enabled: false },
                    hand: { enabled: false },
                    body: { enabled: false },
                    segmentation: { enabled: false },
                  },
                  hand: { // runs hands model
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: false },
                    object: { enabled: false },
                    gesture: { enabled: false },
                    hand: { enabled: false },
                    body: { enabled: false },
                    segmentation: { enabled: false },
                  },
                  object: { // runs object model
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: false },
                    object: { enabled: false },
                    gesture: { enabled: false },
                    hand: { enabled: false },
                    body: { enabled: false },
                    segmentation: { enabled: false },
                  },
            };
            this.human = new Human.Human(myConfig);
            await this.human.load();

**Comment by shurshilov** [comment]
const myConfig = {
                debug:false,
                modelBasePath: '/hr_attendance_face_recognition_pro/static/src/js/models',
                face: { // runs all face models
                    async: false,
                    filter: { enabled: false },
                    face: { enabled: true },
                    mesh: { enabled: true },
                    iris: { enabled: false },
                    description: { enabled: true },
                    emotion: { enabled: false },
                },
                hand: { enabled: false },
                body: { enabled: false },
                object: { enabled: false },
            };
FOund

**Comment by vladmandic** [comment]
btw, note that `async` and `filter` are global properties, not part of `face` object.  
also, do you have a reason to disable async execution at all?

**Comment by shurshilov** [comment]
Thank you one question why result.face[0].tensor not work in 2.5.6 version?

**Comment by vladmandic** [comment]
`result.face[0].tensor` is optional since when tensor is returned, it would have to be manually disposed by user and most users would forget to do that thus creating a leak.

if you want to enable it, set configuration
`myConfig.face.return = true`

and then don't forget to dispose all returned face tensors when you're done with them.

for example

```js
res.face.forEach((f) => tf.dispose(f.tensor));
```
