### ISSUE TITLE
How to scale the camara display (together with results overlay)?

### ISSUE THREAD

**Issue by timepp** [vladmandic/human#260]
I do want to scale what's diaplay on the screen, while ensure the detection performed on the original video image (the larger the image is, the better the result would be, is that correct?)

As for the following 2 lines of code:
```typescript
      await human.draw.canvas(video, canvas); // draw canvas to screen
      await human.draw.all(canvas, interpolated); // draw labels, boxes, lines, etc.
```
I know the first line can be changed to (I have already resized the canvas previously):
```typescript
      canvas.getContext('2d')?.drawImage(video, 0, 0, canvas.width, canvas.height)
```
But how about the 2nd line?

**Comment by vladmandic** [comment]
> the larger the image is, the better the result would be, is that correct

not really. models are trained on a specific (and quite low) resolution. any larger input just means that image is resized to that lower resolution before detection. and different models use different resolutions. plus some work on entire image and some work on cropped parts of image (e.g. face analysis works after face detection has determined there is a face and cropped it from whole image and then resized cropped part).

i've done best to clean-up model signatures, so you can open each `model/*.json` and look at `inputs` line near the top - it will say whats the `size` used by each model (you can also look at it from the code by inspecting `human.models[model_name].inputs[0].size` property of each loaded model).

> I do want to scale what's diaplay on the screen

like you've done already, its easy to rescale draw of entire canvas.
but second line (`human.draw.all`) calls a lot of low-level canvas draw operations which are fixed per input canvas size.

if you only need some functionality and perform rescaling before draw, you can take it from `src/util/draw.ts`, that's where method is implemented.

**Comment by timepp** [comment]
Thanks for the very detailed explain!
As you said video resolution is not a very big deal, my current quick workaround is setting the video width to 640 through `MediaStreamConstraints`. 
Will back to `src/util/drawts` later when I have more time.

**Comment by vladmandic** [comment]
thats a valid approach.
closing the issue as resolved since there is nothing for me to do in the code, but feel free to post any follow-up questions when you have them.
