### ISSUE TITLE
incorrect project dependencies

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/human#264]
### Discussed in https://github.com/vladmandic/human/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **pgg** April  1, 2022</sup>
Hi Vlad,

Cannot find type definition file for 'offscreencanvas' in a new project that uses a package that i build that uses Human
```
[ng] Error: node_modules/@vladmandic/human/types/human.d.ts:1:23 - error TS2688: Cannot find type definition file for 'offscreencanvas'.
[ng] 
[ng] 1 /// <reference types="offscreencanvas" />
[ng]                         ~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/@vladmandic/human/types/human.d.ts:7:53 - error TS2304: Cannot find name 'OffscreenCanvas'.
[ng] 
[ng] 7 export declare type AnyCanvas = HTMLCanvasElement | OffscreenCanvas;
```

npm i -D @types/offscreencanvas fixes the issue in the new project, but wondering, should human not enforce this instead of installing it manually? Or is there something i should rather do in my lib?
</div>

**Comment by vladmandic** [comment]
@types/offscreencanvas is explicitly listed in api-extractor bundledPackages configuration, so it should be included - and it was in the previous versions, i guess something broke/change in api-extractor functionality that i use to create .d.ts bundle.
i'll take a look.

**Comment by pgg** [comment]
is this intended OffscreenCanvas_2? getting the following error for:
```
canvas.getContext('2d')?.drawImage(result.canvas, 0, 0);
```
```
Argument of type 'AnyCanvas' is not assignable to parameter of type 'CanvasImageSource'.
  Type 'OffscreenCanvas_2' is not assignable to type 'CanvasImageSource'.
    Type 'OffscreenCanvas_2' is missing the following properties from type 'HTMLCanvasElement': captureStream, toBlob, toDataURL, accessKey, and 277 more.ts(2345)
```

**Comment by vladmandic** [comment]
OMG, I hate OffscreenCanvas typedefs. No, thats not intended. Should have tested more before pushing update.

**Comment by vladmandic** [comment]
link to issue <https://github.com/microsoft/rushstack/issues/3306>

**Comment by pgg** [comment]
2.6.4 also not installing in stackblitz, asking for tfjs-node and worker_threads packages . . .

**Comment by vladmandic** [comment]
2.6.4 is **older** version, last available on *npmjs*. 2.6.5 with changes is available only on github until i publish it to npmjs as well  

in either case, i just tried stackblitz and error is identical with both versions and not related to `offscreencanvas` typedefs at all.

stackblitz is trying to be smart and import all possible dependencies even if they are NOT used. `tfjs-node` is used by `dist/human.node.js`. it is NOT used (or even mentioned in) by `dist/human.esm.js`. 

and `worker_threads` are conditionally used (only when platform is node) within `@tensorflow/tfjs-backend-wasm`. so only way to avoid those is not to package tfjs at all.

there is no way to specify separate dependencies in `package.json` for different targets. and i definitely don't want to publish separate packages for browser and node. i consider this a BUG in stackblitz, not Human.

**Comment by vladmandic** [comment]
took a while, but traced it down to regression in `@tensorflow/tfjs-backend-cpu`, created issue <https://github.com/tensorflow/tfjs/issues/6315>

**Comment by pgg** [comment]
for 2.6.5 getting slightly different OffscreenCanvas error:  `node_modules/@vladmandic/human/types/human.d.ts:5:53 - error TS2304: Cannot find name 'OffscreenCanvas'` is this fix in 2.7.0 or is 2.7.0 fixing the tfjs dep?

**Comment by vladmandic** [comment]
i've tried one thing so:
- **2.6.4** requires `@types/offscreencanvas` dependency while 2.6.5 does not  
- **2.6.5** requires that `webworker` is added to `compilerOptions.lib` entry in `tsconfig.json`  

neither of options are ideal, but I just don't know how to bundle `offscreencanvas` typedefs until **api-extractor** allows to do that (tracked under <https://github.com/microsoft/rushstack/issues/3306>)  
let me know which option do you prefer for now?  

**2.7.0** is a preview version of the new feature that is currently in develeopment:  
support for **facemesh attenction** model with special processing for eyes and lips. 
that one is tricky since mediapipe introduced some custom tensor ops which do not exist in normal tfjs.  
see <https://github.com/PINTO0309/PINTO_model_zoo/issues/143> for details.

**Comment by vladmandic** [comment]
ok, i've reverted changes in 2.7.0 so it behaves like 2.6.4 in reference to `OffscreenCanvas` and updated version is on github  

i've also just completed integrating **facemesh attention** model, but will hold-on official release (npmjs) until <https://github.com/tensorflow/tfjs/issues/6315> is resolved

**Comment by vladmandic** [comment]
remaining issue is a in **stackblitz** when using tfjs in general and their team is not responsive so far  
see issue <https://github.com/stackblitz/core/issues/1832>

**Comment by vladmandic** [comment]
closing the issue as its being actively tracked by stackblitz team. root cause is regression in `systemjs` parser that mistakes code in strings as live code.

**Comment by vladmandic** [comment]
stackblitz issue has been resolved.
