### ISSUE TITLE
some faces not detected

### ISSUE THREAD

**Issue by jan-bogaerts** [vladmandic/human#267]
**Issue Description**

In the following image, I've highlighted the faces that get detected. Other faces aren't. I was wondering why this was the case and if it could be improved a little, so that at least the guy holding the wine bottle is picked up?

![20160603_131043_2](https://user-images.githubusercontent.com/7602101/168273795-f36339fa-55d7-4343-b114-75ee5bfd6df9.jpg)

**Steps to Reproduce**

`
const engineConfig = {
    backend: 'humangl',
    //modelBasePath: 'file://models/',
    modelBasePath: 'https://cdn.jsdelivr.net/npm/@vladmandic/human/models/',
    debug: false,
    async: false,
    filter: {
        enabled: false,
    },
    face: {
        enabled: true,
        detector: { enabled: true, return: false, rotation: true, maxDetected: 50, iouThreshold: 0.01, minConfidence: 0.2 },
        mesh: { enabled: true },
        iris: { enabled: true },
        description: { enabled: true },
        emotion: { enabled: true },
    },
    hand: {
        enabled: false,
    },
    body: { enabled: false },
    object: { enabled: false },
    gesture: { enabled: false },
    segmentation: { enabled: false }
};

const result = await human.detect(imageTensor, engineConfig);
`

**Expected Behavior**

perhaps 3 or 4 people being picked up?

**Environment**

- Human library version:
human version: 2.7.1 | 
platform: Windows NT 10.0; Win64; x64 | agent: Mozilla/5.0 AppleWebKit/537.36 findpeople/0.2.4 Chrome/91.0.4472.164 Electron/13.6.9 Safari/537.36
- custom code
- js, electron
- TensorFlow/JS version (if not using bundled module)? tfjs version: 3.16.0-20220509 (although I didn't install an external version, relying on the bundled module, but comes out as 3.16?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? electron 13.1.4, comes with node  v14.17.0
- Packager (if any)  *webpack*
- Framework *React*

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**
it sometimes even works with dogs :)

**Comment by vladmandic** [comment]
how it works here is that face detector detects possible face candidates, but then since you have mesh enabled it fails to detect mesh on a face previously detected by detector, so it invalidates it leaving you with only 2 faces  

using your image and running with `mesh: { enabled: false }` and having the same thresholds returns 4 possible faces, but they are not validated in any way  

now, why does mesh mapping fails on face of a person holding a wine bottle? too much contrast - one side of face is almost white while another side is almost black

**Comment by jan-bogaerts** [comment]
That's interesting. 

> they are not validated in any way

What exactly do you mean by that?  Is the mesh perhaps used as an extra filter to check if the face is a real face (and not some weird artifact)? Would it perhaps help to play with some of the  parameters of the mesh matcher?

I'm gonna do some tests with the mesh disabled to see what that gives. and do some thinking on how/if to handle this case... (currently code is a bit 'in between stages', so this is gonna take a couple of hours...

**Comment by vladmandic** [comment]
> Is the mesh perhaps used as an extra filter to check if the face is a real face (and not some weird artifact)?

exactly.

> Would it perhaps help to play with some of the parameters of the mesh matcher?

only params mesh model has are `rotation` and `minConfidence` and they are shared with detector.

btw, on images with weird contrast, you can try running histogram equalization which would try to even out each detected face as it runs after face after detector and before mesh runs: `config.filter.equalization = true` (filter must be enabled for this to work).

**Comment by jan-bogaerts** [comment]
cool, thanks. I'll try. Much appreciated.

**Comment by vladmandic** [comment]
any updates?

**Comment by jan-bogaerts** [comment]
didn't yet get to this, on my to-do list for friday :)

**Comment by jan-bogaerts** [comment]
So, some interesting results. I've played a little with 3 parameters: 
- filter.equalization = true or false
- mesh: { enabled: true or false }
- face.detector.minConfidence from 0.2 to 0.7

Equalization doesn't appear to do very much of a difference (a little, but not for the picture in the example, I did get a couple of extra false positives). 
Turning on/off the mesh does have a serious influence. The minConfidence becomes important. Without the mesh, it initially gives a lot of false positives, but it becomes better round 65%.  In the example picture, I had to go as low as 26% to get 4 faces discovered (without mesh).
In contrast, when using an ntcnn (from here https://github.com/ipazc/mtcnn), it finds 6 faces, out of which 5 have a confidence of +97% and the last comes in at 71%. However, it is a lot slower.

I was wondering about 2 things: 
- would it be possible to have the mesh values as 'optional'. So that the face is still returned, but if the mesh can't be calculated, it remains null?
- You mention that it is possible to use different models other than the default ones. Would something similar to the mtcnn model also be possible to use?

**Comment by vladmandic** [comment]
> would it be possible to have the mesh values as 'optional'. So that the face is still returned, but if the mesh can't be calculated, it remains null?

yes, i can add that option

> You mention that it is possible to use different models other than the default ones. Would something similar to the mtcnn model also be possible to use?

sure, but each model requires some implementation work, its non-trivial  

i'm not happy with `blazeface` face detector, but it is the fastest one by far and majority of use-cases with `human` are  
using real-time inputs  
i did look at adding some alternatives in the past, but didn't finish that part as it was never a priority  

i'll take a look at what can be done, will keep this thread updated

**Comment by vladmandic** [comment]
i've added a new config flag: `config.face.mesh.keepInvalid`, set it to true if you want to keep all detected faces regardless of results of mesh module

new version of `human` is published on github, but not yet on npmjs (will be later next week)  

btw, i've also implemented newer `facemesh-detection` which is based on `blazeface` that i'm already using and its actually worse so i'm going to keep it out of default config  

if you want to try it, feel free - just copy model from `human-models` repository and set `config.detector.modelPath` to the new model, `human` will auto-detect which model it is and trigger necessary processing in the backend
