### ISSUE TITLE
how to gracefully handle 'Failed to compile fragment shader' - 'WebGL: CONTEXT_LOST_WEBGL'

### ISSUE THREAD

**Issue by jan-bogaerts** [vladmandic/human#268]
**Issue Description**

Sometimes, I get the following exception: Error: 

```
Couldn't parse line number in error: 
human.esm.js:23098 #version 300 es
    precision highp float;
    precision highp int;
    precision highp sampler2D;
    in vec2 resultUV;
    out vec4 outputColor;
    const vec2 halfCR = vec2(0.5, 0.5);
....

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

Uncaught (in promise) Error: Failed to compile fragment shader.
    at e1 (human.esm.js:23090)
    at GK (human.esm.js:24760)
    at human.esm.js:26085
    at j1.getAndSaveBinary (human.esm.js:26102)
    at j1.runWebGLProgram (human.esm.js:26085)
    at Ii (human.esm.js:26674)
    at $8 (human.esm.js:26744)
    at Object.th [as kernelFunc] (human.esm.js:26749)
    at i (human.esm.js:4762)
    at human.esm.js:4785
    at am.scopedRun (human.esm.js:4714)
    at am.runKernelFunc (human.esm.js:4784)
    at am.runKernel (human.esm.js:4736)
    at lD (human.esm.js:7398)
    at sum__op (human.esm.js:5084)
    at skip (human.esm.js:38902)
    at human.esm.js:51461

13:21:26.657 Human: error: humangl: webglcontextlost

13:21:26.659 Human: possible browser memory leak using webgl or conflict with multiple backend registrations

human.esm.js:48974 Uncaught (in promise) Error: backend error: webgl context lost
    at HTMLCanvasElement.<anonymous> (human.esm.js:48974)
```

In this case, the application was running 1 process using the GPU, but in the mean time I was using chrome as well. From my experience, when only the app runs with 1 GPU process, everything remains stable, but whenever multiple processes use the GPU, things go wrong.  Doing this from a laptop that doesn't have a very good gpu.... 

I believe this issue is related to this:
https://github.com/tensorflow/tfjs/issues/1644

So I don't think you can do much about the error itself, it's related to the GPU and how tensorflow works. I was just wondering if there was a graceful way to manage this error (other than not using the GPU at all).  
Right now, when this happens, the process running the model is basically dead.  If I could catch this somehow, the process could be restarted.

I have found this: https://stackoverflow.com/questions/61020416/how-to-handle-webgl-context-lost-webgl-errors-more-gracefully-in-pixijs  which explains a way to capture the error, but the event handler appears attached to the object providing the context, which I don't know how to do with this shader business..

**Steps to Reproduce**
running multiple processes at the same time, using the GPU, on a crappy laptop. The more processes running the model, the faster it blows up...

some code:
```
const engineConfig = {
    backend: 'humangl',
    //modelBasePath: 'file://models/',
    modelBasePath: 'https://cdn.jsdelivr.net/npm/@vladmandic/human/models/',
    debug: false,
    async: false,
    filter: {
        enabled: false,
    },
    face: {
        enabled: true,
        detector: { enabled: true, return: false, rotation: true, maxDetected: 50, iouThreshold: 0.01, minConfidence: 0.2 },
        mesh: { enabled: true },
        iris: { enabled: true },
        description: { enabled: true },
        emotion: { enabled: true },
    },
    hand: {
        enabled: false,
    },
    // body: { modelPath: 'blazepose.json', enabled: true },
    body: { enabled: false },
    object: { enabled: false },
    gesture: { enabled: false },
    segmentation: { enabled: false }
};

async evaluate(filename) {
        console.log("start loading image in tensor");
        const imageTensor = await this.loadTensor(filename);
        try {
            try {
                return = await this.engine.detect(imageTensor, engineConfig);
            }
            catch(error) {
                console.log(error);
                return [];
            }
        }
        finally {
            this.engine.tf.dispose(imageTensor);
        }
    }
```

**Expected Behavior**
Some sort of way to capture this gracefully in the javascript section?

**Environment**

- Human library version? human version: 2.7.1
- Built-in demo or custom code?  custom code
- Type of module used: js
- TensorFlow/JS version (if not using bundled module)? using bundle, but it keeps reporting 3.16
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?  electron 13.1.4, comes with node v14.17.0
- OS and Hardware platform:   *Windows 10*
- Packager (if any):  *webpack* (default electron setup)
- Framework  *React*

**Comment by vladmandic** [comment]
you're correct in all of the assumptions  

just a bit more context - this is related purely to amount of gpu memory, not gpu performance at all  

but its also related to how browsers  
a) handle background processes - chrome (and other browsers) will often forcefully suspend code running in non-active tabs and even worse, it will suspend events from firing, so if process is running in a background tab, it really cannot do much to listen to anything. there are ways to make this work using complicated workarounds (e.g. service workers, etc.), but overal its pretty bad  
b) multiple processes - chrome may be optimized in may ways, but it has only a single process for gpu communication, so only running multiple processes that using gpu will cause it to switch back and forth and that part of chrome is quite buggy in my experience  

second problem is that once webgl context lost occurs, everything that was on gpu is lost - which means only way to "handle" it is to reload everything from scratch (reload model and let it compile itself again into wgsl code)  

when context lost issue does occur, `human` will resurface the `error` event which you can listen to  
for example:

```js
human.events.addEventListener('error', () => {
  // do something here
});
```

but after it publishes the event, `human` will still do a force-throw  
i could add a config flag not to throw on error (i would leave it enabled by default),  
so you can handle errors in your code if you wish?

**Comment by jan-bogaerts** [comment]
```
human.events.addEventListener('error', () => {
  // do something here
});
```

Cool. hadn't thought of that. I'll try this one to see if it gives me enough to get a message back to the main process.


> handle background processes - chrome (and other browsers) will often forcefully suspend code running in non-active tabs and even worse, it will suspend events from firing, so if process is running in a background tab, it really cannot do much to listen to anything. there are ways to make this work using complicated workarounds (e.g. service workers, etc.), but overal its pretty bad

true and very annoying. With electron it should be possible to disable this behaviour with the following flag: 'disable-renderer-backgrounding'

> but after it publishes the event, human will still do a force-throw

this could still give some issues. I'll try first before adding extra flags?

**Comment by jan-bogaerts** [comment]
so the eventhandler works. The processes that fail are able to report back that they failed and so the main process can relaunch them. My whole computer is cracking all over the place when testing this with lots of gpu thread, with everything else slowing down to a creep, but it works.
