### ISSUE TITLE
Face Liveness and Antispoof

### ISSUE THREAD

**Issue by berry-lai** [vladmandic/human#270]
**Issue Description**

After some check with different real human images, the result is ok with its speed.
However, when I tried to check on cartoon, the result shown the face spoofing and liveness model would be too noisy ?...

The original image

![14](https://user-images.githubusercontent.com/87605316/171940012-d1917d26-2843-46c7-98ac-0238849a5caa.jpg)

The result image

![14](https://user-images.githubusercontent.com/87605316/171939967-8983316b-7402-4219-960c-97ed598bbaac.png)

**Steps to Reproduce**

```javascript
const config = {
  backend: 'tensorflow',
  modelBasePath: `file://${path.resolve('./node_modules/@vladmandic/human/models')}`,
  wasmPath: './node_modules/@tensorflow/tfjs-backend-wasm/dist/',
  debug: true,
  async: false,
  filter: { enabled: true, flip: true, },
  face: {
    enabled: true,
    detector: {
      enabled: true, rotation: false,
      minConfidence: 0.5,
      iouThreshold: 0.3,
      maxDetected: 50,
    },
    mesh: { enabled: false },
    iris: { enabled: false },
    description: { enabled: false },
    emotion: { enabled: false },
    antispoof: { enabled: true },
    liveness: { enabled: true },
  },
  hand: { enabled: false },
  body: { enabled: false },
  object: { 
    enabled: true,
    minConfidence: 0.15,
    iouThreshold: 0.3,
    maxDetected: 50,
  },
};

// Method to generate those boxes
const Canvas = require('canvas');
const pixel = require('pixel-util');
const fs = require('fs');

const result = await human.detect(tensor, config);

// Draw Image
var image = new Canvas.Image;
image.src = await pixel.createBuffer('your-image-file');
const canvas = Canvas.createCanvas(image.width, image.height);
const ctx = canvas.getContext('2d');
ctx.drawImage(image, 0, 0);

const drawRect = (text, box) => {
    const [x, y, width, height] = box;
    const color = Math.floor(Math.random()*16777215).toString(16);
    ctx.strokeStyle = '#' + color;
    ctx.font = '0.875em Arial';

    // Draw rectangles and text
    ctx.beginPath();   
    ctx.fillStyle = '#' + color;
    ctx.lineWidth = Math.ceil((image.height + image.width) * 0.0025);
    ctx.fillText(text, x+15, y+30);
    ctx.rect(x, y, width, height); 
    ctx.stroke();
}

for (const face of result.face) {
    drawRect(`#Face${face.id} [(${(face.score * 100).toFixed(2)})% | Real : ${(face.real * 100).toFixed(2)}% | Live : ${(face.live * 100).toFixed(2)}%]`, face.box);
}

for (const obj of result.object) {
    if (obj.label !== 'person') { continue; }
    drawRect(`${obj.label} [(${(obj.score * 100).toFixed(2)})%]`, obj.box);
}

fs.writeFileSync('your-png-output-path', canvas.toBuffer('image/png'));
```

**Expected Behavior**

Lower liveness and real score on those faces ?.... (Just a question not a bug or problem)

**Environment**

- Human library version : NPM v2.7.3
- Built-in demo or custom code : Custom Code
- Type of module used : NPM version
- TensorFlow/JS version (if not using bundled module)
    - @tensorflow/tfjs-node": "^3.18.0"
- Browser or NodeJS and version : NodeJS v14.17.3
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Mac OSX 12.1
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**
A even more difficult problem is separating person and hot toy which will be out of scope of this project.

**Comment by vladmandic** [comment]
none of the models in this project are designed to work with cartoon images. to work reliable, models would need to be fully retrained. the fact that it works at all is more than i expect.  
sorry, i don't know what you expect me to add here?

**Comment by berry-lai** [comment]
> none of the models in this project are designed to work with cartoon images. to work reliable, models would need to be fully retrained. the fact that it works at all is more than i expect. sorry, i don't know what you expect me to add here?

The question would be about face anti spoofing and liveness. As cartoon faces may not classified with high real and live score ?

**Comment by vladmandic** [comment]
Those models are **very** simple and trained with images of human faces VS real faces.
They would need to be retrained as well with cartoon images.
