### ISSUE TITLE
When using the front camera, the content of the camera is opposite to the reality. How can I mirror it like a mobile camera?

### ISSUE THREAD

**Issue by a1782680475** [vladmandic/human#273]
When using the front camera, the content of the camera is opposite to the reality. How can I mirror it like a mobile camera?

**Comment by a1782680475** [comment]
First of all, thank you for your answer.
I can do this by using scaleX (-1), but some face detection boxes will be flipped so that they cannot be read. See the following for specific effects.
![image](https://user-images.githubusercontent.com/32875468/172970246-f021b4d8-f4cb-45dd-a6b2-f0e825dcb143.png)
![image](https://user-images.githubusercontent.com/32875468/172970290-37a59c5d-3373-4937-9991-85f5c66f7ede.png)

**Comment by vladmandic** [comment]
Boxes seem fine, what's reflected is text - and you don't have to use built-in methods, you can draw it yourself.

And what about second method I've mentioned?

**Comment by vladmandic** [comment]
Second method should not produce results you're seeing, I'll take a look, but may be a slow response as I'm leaving for a trip tomorrow.

**Comment by a1782680475** [comment]
Thank you very much. Do you need my code?

**Comment by a1782680475** [comment]
It's all according to your time. I'm not in a hurry. I can wait until you come back from your trip.

**Comment by vladmandic** [comment]
Yes, having your code would help.

**Comment by vladmandic** [comment]
i just a quick look before my flight and i don't think there is an issue, its just a question of which canvas you're drawing.

if you have 'config.filter.flip = true` and you use `inputVideo` as input, it will be correctly flipped before processing. but then the question is what is displayed on screen? if you display original video (or copy it to output canvas), it will not be flipped so detected results will look exactly opopsite of image.

instead, you can draw processed image (so after it has been flipped) - it is part of the result output.

for example:

```js
const result = human.detect(inputVideo);
human.draw.canvas(results.canvas, outputCanvas); // this will draw processed image onto HTMLCanvasElement
human.draw.all(outputCanvas, results); // this will draw detection boxes, text, etc.
```

**Comment by a1782680475** [comment]
Think u.
According to your method, the problem has been solved.
