### ISSUE TITLE
Similarity is always above 50% for every face in main browser live demo.

### ISSUE THREAD

**Issue by saifxx** [vladmandic/human#274]
Similarity is always above 50% for every face in main browser live demo.

I have tested different faces in full demo that you provided but similarity is always above 50%. Please check the following test in which similarity is 61%.

![demo](https://user-images.githubusercontent.com/29164221/173008637-923cba93-f58a-4b7a-b86f-6310015b37dd.png)

Settings:

![image](https://user-images.githubusercontent.com/29164221/173010374-7392c107-8fb6-45bf-9196-ae3d29e0c0eb.png)

Demo link: https://vladmandic.github.io/human/demo/index.html
Laptop specs: Hp i5, 6th gen, 8GB Ram, 250GB Nvme
Browser: Microsoft Edge v102.0.1245.33

**Comment by vladmandic** [comment]
i've just tested using `demo/facematch` which has 100+ test faces and results are within expected range  
can you provide actual images (not just one) that you've used and getting incorrect results?

**Comment by saifxx** [comment]
Thanks for your reply.

demo/facematch is working as expected but in demo/index.js, face comparison is not working correctly as you can see my above test. Can you please compare two different faces using webcam in this demo: https://vladmandic.github.io/human/demo/index.html

**Comment by vladmandic** [comment]
I'll check, but I'm just leaving for extended travel so it may be slow.

**Comment by saifxx** [comment]
> I'll check, but I'm just leaving for extended travel so it may be slow.

I’m looking forward to hearing from you 😊

**Comment by vladmandic** [comment]
I just tested and it seems like it's working, although with limited precision - there is no way to tune it for all use-cases out-of-the-box.

for example, I'm really not similar to Einstein at all (<8% with default settings) ! :)
![image](https://user-images.githubusercontent.com/57876960/178742950-9d812c74-ab04-42cf-8c5f-35375675022c.png)

to tune behavior of `human.similarity()` and `human.match()` methods to fit your use case, see `MatchOptions` in <https://github.com/vladmandic/human/blob/12687eadcc0a5f42cc06ead11b8288ad6f6504a3/src/face/match.ts#L31>

also, there was no way to reset baseline once face compare was started in the demo app.  
i've added a feature when click on a baseline image (upper left) will reset it on-demand.
