### ISSUE TITLE
Integrate BlazePalm into human

### ISSUE THREAD

**Issue by djthegr8** [vladmandic/human#28]
**Issue Description**
![image](https://user-images.githubusercontent.com/44142719/98764095-145ae300-2401-11eb-9d27-e218296cc719.png)
This is what Im getting
**Steps to Reproduce**
Switch on Hand and keep only the detection (not landmark), see console
**Expected Behavior**
Works as expected
**Environment**
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 86) Chrome
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10) Win10
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.) N/A

**Additional**
- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by djthegr8** [comment]
I am using a [h5 blazeface model from here](https://github.com/SBoulanger/blazepalm/blob/master/saved_model.h5).

**Comment by djthegr8** [comment]
Update: That model returns the classifications and regressions separately; have made it different, yet getting a very bad output

**Comment by vladmandic** [comment]
you cannot switch models and expect it to work out-of-the-box, models are very different and require a totally different pre and post processing.

i took a look at blazepalm from the link you've provided and that is not a finished model

first, all test code uses raw weights and creates model on the fly: keras saved model at the end is just a dump and there is no code that indicates it's usage  

at a bare minimum, it requires custom anchors and post-processing of output nodes  

see <https://github.com/SBoulanger/blazepalm/blob/master/test.py>
```python
    classificators, regressors = pm.model.predict(input_image)
    ...
    x1y1 = anchors[:,:2] * 256 - regressors[:,2:4]/2#regressors[:,:2] - regressors[:,2:4]/2
    x2y2 = anchors[:,:2] * 256 + regressors[:,2:4]/2#regressors[:,:2] + regressors[:,2:4]/2
    dets = np.concatenate((x1y1,x2y2),axis=1)
    dets = np.concatenate((dets,classificators),axis=1)
```
and <https://github.com/SBoulanger/blazepalm/blob/master/anchors.csv>

unfortunately, repo has been discontinued - it has not been updated in 11 months and author noted
`Although do not think I will continue with this TF implementation.`

as such, this is a dead-end, sorry.

**Comment by djthegr8** [comment]
RIP ☠️ thanks for the clarification.
