### ISSUE TITLE
: spawn ffmpeg ENOENT in nodejs video example

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [vladmandic/human#284]
**Issue Description**
I tried to run node-video example from demo folder but got this error while running
https://github.com/vladmandic/human/blob/main/demo/nodejs/node-video.js

`Error: spawn ffmpeg ENOENT
     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
     at onErrorNT (internal/child_process.js:469:16)
     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
   errno: 'ENOENT',
   code: 'ENOENT',
   syscall: 'spawn ffmpeg',
   path: 'ffmpeg',
   spawnargs: [
     '-loglevel',
     'quiet',
     '-i',
     './RecordRTC-1652871745540-blob.mp4',
     '-an',
     '-c:v',
     'mjpeg',
     '-pix_fmt',
     'yuvj422p',
     '-f',
     'image2pipe',
     'pipe:1'
   ]
 }
`

**Steps to Reproduce**

**Expected Behavior**

**Environment**

- Human library version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
if you look at `node-video` header, it states:

```text
/**
 * Human demo for NodeJS
 * Unsupported sample of using external utility ffmpeg to capture to decode video input and process it using Human
 *
 * Uses ffmpeg to process video input and output stream of motion jpeg images which are then parsed for frame start/end markers by pipe2jpeg
 * Each frame triggers an event with jpeg buffer that then can be decoded and passed to human for processing
 * If you want process at specific intervals, set output fps to some value
 * If you want to process an input stream, set real-time flag and set input as required
 *
 * Note that pipe2jpeg is not part of Human dependencies and should be installed manually
 * Working version of ffmpeg must be present on the system
*/
```

**Comment by vladmandic** [comment]
i'm closing the issue as its not a product defect, but feel free to post on this thread if you have further questions.
