### ISSUE TITLE
what are the RAM requirements for node-js server. How can i improve performance in node-js server?

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [vladmandic/human#285]
**Issue Description**
what are the RAM requirements for the node-js server? How can I improve performance in the node-js server?

i have 1GB server on digitalocean.
and use this module to analyze videos via the node js server. but after some time the error was received.

`W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 9830400 exceeds 10% of free system memory.
`
and my pm2 restart.

please tell me how much RAM is required to run this smoothly and how can I improve to the batter.

**Steps to Reproduce**

**Expected Behavior**

**Environment**

- Human library version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
how much memory is required depends on which models you have enabled  
you can always monitor you engine memory usage with `console.log(human.tf.memory())`

and if you need more info on tensorflow internals memory allocation, you can increase its logging with 
`process.env.TF_CPP_MIN_LOG_LEVEL = '0'`;

there are some `TF_` environment variables that change default behavior of tensorflow's memory allocator, but i didn't experiment much with that.

i'm closing the issue as its not a product issue per-say, but feel free to post further on this thread.
