### ISSUE TITLE
Face id demo example is unable to recognize my face

### ISSUE THREAD

**Issue by philter87** [vladmandic/human#294]
Thanks for making a great library with a intuitive api. 
The demo "Face ID" is not able to match my face. I have tried on my Phone (Android & samsung s21) and my laptop (chrome, windows 11). 
Maybe I have misunderstood the purpose of the demo, but I expect the app to find my name after the second face scan. 

It should be pretty easy to reproduce (unless it is a compatibility issue). You can go to https://vladmandic.github.io/human/demo/faceid/index.html and then try to scan you face three times.

**Comment by vladmandic** [comment]
i just tried, and it works here

are you able to scan face before timeout (meaning all markers turn green)? and then enter a name label and save it?
after that, it should persist as it gets stored in browser's indexdb. so if you press retry or even close browser and reopen it, once you pass the checks (all checks turn green), it should match it to closest entry in the database.

btw, you may need to store several variations in database for best results matches

**Comment by philter87** [comment]
Alright. Thanks for the quick response. Maybe the issue is that I am unable to pass all the checks. I think you can close this issue

**Comment by vladmandic** [comment]
I'll increase the timeout for checks from 10sec to 30sec for demo anyhow.

Btw, which checks are you having trouble passing?
They are all marked on the right hand side.

**Comment by philter87** [comment]
Thanks. Blink detected is always red. I think I have a fairly regular face, but maybe not :)

**Comment by vladmandic** [comment]
it works pretty reliably on my tests, but if you want to test `faceid` demo without blink detection,  
simply set its value to be `true` always in  
<https://github.com/vladmandic/human/blob/2e5ca3b95480c27569c7df74fb28204f535c0247/demo/faceid/index.ts#L141>

anyhow, blink is detected if `human` detects that either eye gets closed and opened again,  
but it has to be closed for min 10ms and it has to reopen in less than 800ms  

you can change those values at <https://github.com/vladmandic/human/blob/2e5ca3b95480c27569c7df74fb28204f535c0247/demo/faceid/index.ts#L40>  

how `human` detects blink internally is if ratio of  
- center of eye inner lid y-coord and 
- center of wider eye border y coord
is less than 0.2 (20%)  
setting it to a higher value (e.g. 0.3) would increase detection sensitivity, but it would be more prone to false positives  
(there is no single value that is best for everyone, this is just a value i came up from experimentation)  
(see <https://github.com/vladmandic/human/blob/2e5ca3b95480c27569c7df74fb28204f535c0247/src/gesture/gesture.ts#L65> for details)

**Comment by vladmandic** [comment]
fyi, faceid demo has been updated and it will provide more detailed explanations on what its doing during runtime.

**Comment by philter87** [comment]
Awesome! It works and it is able recognize my face. Thanks for adding more comments in the demo and here
