### ISSUE TITLE
How to get an image from detected faces

### ISSUE THREAD

**Issue by IgorSamer** [vladmandic/human#300]
How do I get a base64, Blob, etc from detected faces? I currently save the descriptors in a faces.json but now I want to save the image of the faces as well.

I already set `return: true` in `config.face.detector` but I didn't find how to work with the returned tensor.

I know I can use `toDataURL()` to get the `canvas` as an image, but I just want the face without the box, labels, etc. What is the correct way to achieve this through `human.result.face`?

**Comment by vladmandic** [comment]
if you want `dataUrl`, fastest is to use temp canvas to draw just the face directy like this  

```js
human.tf.browser.toPixels(result.face[0].tensor, canvas);  
```

and then use `canvas.toDataUrl()`

and to get underlying data of a face tensor as a flat array:
```js
const data = await result.face[0].tensor.data();  
```

or to get a 3d array:
```js
const data = await result.face[0].tensor.array();  
```

in either case, amount of data is `[width, height, rgb]` and values are in `Float32Array` in `0..1` range.

from there, you can either first renormalize to int values in `0..255` range or just create `Blob` or `ImageData` or whatever directly.

in any case, if you're using `return=true`, make sure you deallocate tensor once you've done with it as it is not done as part of JS garbage collection.

```js
human.tf.dispose(result.face[0].tensor);
```

btw, for future github discussions are better suited for product usage questions as its not really a product issue.  
in any case, i'm closing the issue, but feel free to post further on this thread.

**Comment by IgorSamer** [comment]
I didn't even know about GitHub discussions actually and if new questions arise that aren't related to product issues, now I know where to go.

`human.tf.browser.toPixels()` and `toDataURL()` do the trick, but I had no success trying to create a `Blob` from `tensor.data()` or `tensor.array()`.

I tried this:

```
const data = await human.result.face[0].tensor.array();
const blob = new Blob([data], { type: 'image/jpeg' }); // tried with several MIME types, but I don't know where I'm going wrong

// Just to test the result
const image = new Image();
image.src = URL.createObjectURL(blob);
document.body.appendChild(image);

human.tf.dispose(human.result.face[0].tensor);
```

But no image is loaded.

Is there any advantage to use `data()` or `array()` to create a `Blob` instead of `toDataURL()`? (either for speed or performance - since theoretically I wouldn't need to create a temp canvas for each registered face)

I'll send the data to `Node.js` to save the image using `FileSystem`.

**Comment by vladmandic** [comment]
your blob example ends up with float values which are 4bytes per element and also in wrong range (`0..1`).  
if you want blob, you need to multiply by 256 and convert to `uint8` array before creating blob.  
and even then, that would give you a RAW blob, not 'jpeg' - its pure width x height x rgb values.  
(btw, this method is best when working with web workers and things like that as arrays can be passed as reference to workers without any performance hit).

whats better?  
depends on your network. if you're on 1gbit lan, fastest is to to use blobs and send data via sockets (not even http).  
but then you still need to encode raw -> jpeg on server side (`sharp` is a beast for that).  
btw, if you go down that route, `ImageData` is a better container than `Blob` as you can fill it with raw data.  
(this is what i do when i need hybrid client-server video processing - client runs as fast as possible and sends raw frames to server via sockets)

and if you're on slower network, `toDataURL` is better.  
don't worry about canvas creation, that's pretty fast (plus you can just create one and re-use it all the time).  
what's slow is raw->jpeg->base64 encoding and encapsulation - that takes CPU.
but you end up with smaller image, so less pressure on network.
