### ISSUE TITLE
webpack with human-nobundle reports package not exported error

### ISSUE THREAD

**Issue by jacobg** [vladmandic/human#301]
I used to import:
`const Human = require('@vladmandic/human/dist/human.esm-nobundle.js').Human`

However, since the exports section was added to package.json:
https://github.com/vladmandic/human/blob/be10bd5f72cc348071abf2551302c5296d512f3e/package.json#L10-L21
importing `dist/human.esm-nobundle.js` causes a webpack error:
`Module not found: Error: Package path ./dist/human.esm-nobundle.js is not exported from package`

Changing the import as follows does seem to resolve the issue:
`const Human = require('../../../node_modules/@vladmandic/human/dist/human.esm-nobundle.js').Human`

Should that be added to the exports section too?

**Comment by vladmandic** [comment]
`package.json` was never designed to have multiple exports,  
so all those are unofficial extensions and hacks that may or may-not be supported by 3rd party packers

`exports` section was added to make new `node` module support happy (e.g. to support ` import Human from "@vladmandic/human"` in node), but now it breaks webpack :(

i'm open to suggestions, but don't have idea from the top of my head how to address this?

**Comment by vladmandic** [comment]
i've added named exports to `package.json` and refreshed build on girhub main branch  
<https://github.com/vladmandic/human/commit/a1bd6a16190a373bc402ca8bb7760169e2288673#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519>

**Comment by jacobg** [comment]
Oh sorry for not replying more quickly. Thanks for the update! I'll try it out. Take care.
