### ISSUE TITLE
Custom model training

### ISSUE THREAD

**Issue by mexists** [vladmandic/human#303]
Hi Sir @vladmandic

Thanks for creating this awesome project!
I have noticed in your [example](https://vladmandic.github.io/human/demo/index.html) that you have the object detection model.

My question is:
1. Is it possible to use `human` to train a specific custom object model? eg: Tesla Cybertruck.
2. How do I import custom trained model into `human` so that the object detection model will recognize my custom object model?

Thanks!

**Comment by vladmandic** [comment]
you cannot use `human` for training directly  

you could start with source of the same model that `human` uses and retrain it,  
that way input and output would be in formats that `human` already understands  

human currently implements variations of two object detection models:
- <https://github.com/610265158/mobilenetv3_centernet> (my preferred one)
- <https://github.com/RangiLyu/nanodet>

and they both can be trained with custom data - then using resulting model in `human` is trivial.

alternatively, you can expand `human` with a custom model although its not trivial  

you could add your own model by registering it in `src/models.ts`  
each model must implement two methods:  

`load`: trivial and it can be just copy & pasted from any existing one  
```js
async function load(config: Config): Promise<GraphModel>
```

`predict`: this is the important one as any model would require  
- pre-processing (e.g. does it expect input in range of 0..1, -1..1, 0..255, etc)
- post-processing - there are no two models on the planet that return results in the same format  
  and for object detection, thats likely running some nms functions to filter based on scores and then reconstruct boxes  
  and possibly de-striding outputs (which i hate doing)

```
async function predict(input: Tensor4D, config: Config): Promise<ObjectResult[]>
```

btw, i'm closing the issue as its not a product issue but more of a general question - but feel free to continue on this thread.
