### ISSUE TITLE
does not work with this mp4

### ISSUE THREAD

**Issue by makc** [vladmandic/human#306]
firefox - video plays in background (I can hear the sound) cant compile a shader:

![изображение](https://user-images.githubusercontent.com/242577/201460079-b0b0eab4-14c3-48a8-b392-822960c0d27e.png)

chromium - video does not play, ffmpeg error:

![изображение](https://user-images.githubusercontent.com/242577/201460141-f6d3c266-d3e9-4485-82cd-59fb05d59d9b.png)

mp4:

https://user-images.githubusercontent.com/242577/201460162-f63c930b-e1a1-40fc-9dbb-3d0e09f32222.mp4

**Comment by vladmandic** [comment]
there was a bug in demo app (not library itself) that did not deallocate webcam stream when loading video file,  
so video player got confused what is it actually playing.  

new code is on github (tested with both chrome and firefox).
