### ISSUE TITLE
Warning: require function is used in a way in which dependencies cannot be statically extractedon human.esm.js at build.

### ISSUE THREAD

**Issue by Carlos-Fernandez-PP** [vladmandic/human#314]
**Issue Description**
human.esm.js throws the next warning at build the app:
![image](https://user-images.githubusercontent.com/118986805/203798304-1459bc51-72c9-44eb-bf1c-28434000b932.png)
i use to import:
`import Human from '@vladmandic/human';`

**Steps to Reproduce**

1. Run webpack-dev-server

**Environment**

- Human library version: NPM v3.0.1
- Built-in demo or custom code: Custom Code
- Type of module used: NPM version
- Browser or NodeJS and version: NodeJS v16.13.0
- OS and Hardware platform: Windows 11
- Packager: Webpack
- Framework: React

**Comment by vladmandic** [comment]
see #308

**Comment by vladmandic** [comment]
closing as resolved, but feel free to post any further questions on this thread.
