### ISSUE TITLE
Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted 

### ISSUE THREAD

**Issue by id1945** [vladmandic/human#315]
```javascript
human.esm.js:17:70-77 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
/*  human.esm.js  */
var __export = (target, all2) => {
  for (var name in all2)
    __defProp(target, name, { get: all2[name], enumerable: true });
};

```javascript
human.esm.js:20:45-52 - Warning: Critical dependency: require function is used in a way in which dependencies cannot be statically extracted 
```
/*  human.esm.js  */
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
```

I had this problem and don't know why it's error!
You can help me?

**Comment by vladmandic** [comment]
duplicate, see #308 on how to resolve

**Comment by id1945** [comment]
@vladmandic  I would check again! Thanks you!.
The library is amazing 👍
