### ISSUE TITLE
Issue in loading model

### ISSUE THREAD

**Issue by anurag-wecp** [vladmandic/human#325]
**Issue Description**
I am getting this error while using human.detect in web worker.

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/106675704/210053858-c84bcfec-d6c5-429e-83b9-3adf3a70c16b.png">
Can you please help me with this?
Thanks.

**Comment by vladmandic** [comment]
it clearly states model files not found at `../models` - verify the path?

**Comment by anurag-wecp** [comment]
Hi @vladmandic sorry, about not being clear earlier. I did verify the path and models are present.
Anyways I was able to solve this for now, by initializing Human with modelBasePath: 'https://vladmandic.github.io/human-models/models/'.
Also, one more thing. human.match.distance is giving values greater than 1. Not sure if this is expected. I saw there was no normalization in distance method.

Thanks a lot.

**Comment by vladmandic** [comment]
> Hi @vladmandic sorry, about not being clear earlier. I did verify the path and models are present.

Relative to webworker script?

> Also, one more thing. human.match.distance is giving values greater than 1. Not sure if this is expected. I saw there was no normalization in distance method.

It shouldn't happen if scale values are correct, but I still haven't had the chance to fine-tune them  
take a look at <https://github.com/vladmandic/human/discussions/322#discussioncomment-4497829>

**Comment by vladmandic** [comment]
anyhow, closing the issue as resolved, but feel free to post further with any updates or questions.

**Comment by anurag-wecp** [comment]
Hi @vladmandic , for the distance issue. For two embeddings distance gives very large values whereas for the same embeddings similarity is less than 1. 
The only difference I see is normalization between the two methods.

Had a question, will the face match and face detection models perform better if the dimensions of the images are increased?
Will a face match and detection be better for images of dimensions 1920 × 1080 px than of 640 × 480 px?

Thanks in advance and have a very happy new year !!.

**Comment by vladmandic** [comment]
> For two embeddings distance gives very large values whereas for the same embeddings similarity is less than 1

i'll take a look.

> Had a question, will the face match and face detection models perform better if the dimensions of the images are increased?
Will a face match and detection be better for images of dimensions 1920 × 1080 px than of 640 × 480 px?

sort-of. how it works is that detection 
1. resize image to fit detect faces and find face boxes
2. using original non-resized image, crop each detected box using rescaled box coordinates
3. for each detected box, resize it to match analysis requirements and run analysis

so if face already takes majority of the input image, there is nothing to be gained by sending large image - face is resized to smaller size anyhow. but if input it wider shot so person is further away, then having larger resolution input allows for cropped face to still be at sufficient resolution.

ideally, cropped face after detection should be 224x224 pixels.

**Comment by anurag-wecp** [comment]
Great Thanks.
