### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'inputNodes')

### ISSUE THREAD

**Issue by AnthonyLzq** [vladmandic/human#328]
**Issue Description**

I'm trying to run the `demo/nodejs/node-similarity.js` script, but I have migrated it to TS (check gist [here](https://gist.github.com/AnthonyLzq/7d36c3ed0b4e2439fb8909bdb2897e30)). However when I run the example using `ts-node` I have the following error:

```bash
/projectPath/node_modules/.pnpm/@tensorflow+tfjs-converter@4.2.0_tkoh6rxfpzme3tc2ndqbqcrg7y/tfjs-converter/src/executor/graph_model.ts:62
    return this.executor.inputNodes;
                         ^
TypeError: Cannot read properties of undefined (reading 'inputNodes')
    at GraphModel.get (/projectPath/node_modules/.pnpm/@tensorflow+tfjs-converter@4.2.0_tkoh6rxfpzme3tc2ndqbqcrg7y/tfjs-converter/src/executor/graph_model.ts:62:26)
    at GraphModel.normalizeInputs (/projectPath/node_modules/.pnpm/@tensorflow+tfjs-converter@4.2.0_tkoh6rxfpzme3tc2ndqbqcrg7y/tfjs-converter/src/executor/graph_model.ts:405:52)
    at GraphModel.execute (/projectPath/node_modules/.pnpm/@tensorflow+tfjs-converter@4.2.0_tkoh6rxfpzme3tc2ndqbqcrg7y/tfjs-converter/src/executor/graph_model.ts:488:19)
    at g3 (/projectPath/node_modules/.pnpm/@vladmandic+human@3.0.3/node_modules/@vladmandic/human/dist/human.node.js:121:20355)
    at z3 (/projectPath/node_modules/.pnpm/@vladmandic+human@3.0.3/node_modules/@vladmandic/human/dist/human.node.js:121:25154)
    at q5 (/projectPath/node_modules/.pnpm/@vladmandic+human@3.0.3/node_modules/@vladmandic/human/dist/human.node.js:121:40481)
    at /projectPath/node_modules/.pnpm/@vladmandic+human@3.0.3/node_modules/@vladmandic/human/dist/human.node.js:840:8172
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Steps to Reproduce**

Try to run this [script](https://gist.github.com/AnthonyLzq/7d36c3ed0b4e2439fb8909bdb2897e30) with `ts-node`.

**Expected Behavior**

To work, I don't know what could have gone wrong.

**Environment**

- Human library version? v3.0.3.
- Built-in demo or custom code? Demo, but with TS instead of JS.
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? CommonJS.
- TensorFlow/JS version (if not using bundled module)? v4.2.0.
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? v18.12.1.
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? 5.19.17-2-MANJARO.
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)? No
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? No

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
and just before that error, you see a different one:

```log
07:23:29.740 Human: error loading model: node_modules/@vladmandic/human/models/facemesh.json TypeError: Failed to parse URL from node_modules/@vladmandic/human/models/facemesh.json
```

and no models get loaded.
why? because built-in `fetch` function in `nodejs` **(still) does not support local filesystem**.
your options are to port your code to use `node-fetch` or something like that or to host models on a http/https server.

**Comment by AnthonyLzq** [comment]
Thanks for your quick response, I will try using `node-fetch` as global `fetch` like in the `demo/node-fetch.js` example.

**Comment by AnthonyLzq** [comment]
I ended up using a CDN as follows:

```ts
const humanConfig: Partial<Config> = {
  debug: true,
  face: { emotion: { enabled: false } },
  body: { enabled: false },
  hand: { enabled: false },
  gesture: { enabled: false },
  modelBasePath: 'https://cdn.jsdelivr.net/npm/@vladmandic/human@3.0.3/models/'
}
```

Without populating `fetch` with `node-fetch`, I living this [gist](https://gist.github.com/AnthonyLzq/8d439ec94994059090ec9c59c119258b) for those who may be interested. Again, thanks for the quick reponse.
