### ISSUE TITLE
can only detect one body

### ISSUE THREAD

**Issue by paul2xf** [vladmandic/human#329]
**Issue Description**
const config = {
    backend: 'tensorflow',
    modelBasePath: 'file://models/',
    debug: true,
    async: false,
    warmup: 'full',
    cacheSensitivity: 0.75,
    filter: {
        enabled: true,
        width: 0,
        height: 0,
        flip: true,
        return: true,
        brightness: 0,
        contrast: 0,
        sharpness: 0,
        blur: 0,
        saturation: 0,
        hue: 0,
        negative: false,
        sepia: false,
        vintage: false,
        kodachrome: false,
        technicolor: false,
        polaroid: false,
        pixelate: 0
    },
    gesture: { enabled: true },
    face: {
        enabled: true,
        detector: { modelPath: 'blazeface.json', rotation: false, maxDetected: 200, skipFrames: 15, minConfidence: 0.2, iouThreshold: 0.1, return: false, enabled: true },
        mesh: { enabled: true, modelPath: 'facemesh.json' },
        iris: { enabled: true, modelPath: 'iris.json' },
        description: { enabled: true, modelPath: 'faceres.json', skipFrames: 16, minConfidence: 0.1 },
        emotion: { enabled: true, minConfidence: 0.1, skipFrames: 17, modelPath: 'emotion.json' }
    },
    body: { enabled: true, modelPath: 'movenet-lightning.json', maxDetected: 200, minConfidence: 0.2 },
    hand: {
        enabled: true,
        rotation: true,
        skipFrames: 18,
        minConfidence: 0.1,
        iouThreshold: 0.1,
        maxDetected: 2,
        landmarks: true
    },
    object: { enabled: true, modelPath: 'centernet.json', minConfidence: 0.2, iouThreshold: 0.4, maxDetected: 10, skipFrames: 19 }
}

![image](https://user-images.githubusercontent.com/109809742/212826831-245b0559-0c4a-4c53-971d-448fc49d911b.png)

**Comment by paul2xf** [comment]
here is the result 
<img width="309" alt="image" src="https://user-images.githubusercontent.com/109809742/212827288-1b6e0f72-6b75-4a56-8db6-00e028ad3293.png">

**Comment by vladmandic** [comment]
this is not an issue, this is by design.  
detecting multiple bodies is computationally intensive and disabled by default.  

you need to set your model to `movenet-multipose` (download from <https://github.com/vladmandic/human-models/tree/main/models>)
