### ISSUE TITLE
Incorrect instructions on the wiki

### ISSUE THREAD

**Issue by Epirito** [vladmandic/human#343]
**Issue Description**
On https://github.com/vladmandic/human/wiki/Install
At the end, under the Weights header, it says:

> If your application resides in a different folder, modify `modelPath`

**Expected Behavior**
It should say `modelBasePath` instead

**Comment by vladmandic** [comment]
it says: If your application resides in a different folder, modify modelPath property **in configuration of each module**

which is correct as `modelPath` applies to each model individually while `modelBasePath` is a global setting.
does Wiki cover every possible scenario? no. but this is not incorrect.
