### ISSUE TITLE
Low Performance when no face is detected

### ISSUE THREAD

**Issue by Sau64** [vladmandic/human#349]
I want to detect faces and gestures on mobile devices, so I'm using Blazeface. However, when I move away from the camera and there is no face detected, the frame rate drops from 60fps to 11fps, and this is affecting some other SVG animations since it runs on the main thread.

I tried using face detection on a worker, which solved the FPS issue on the main thread, but I found out that it doesn't work on iOS :(

Is there any way to improve the frame rate when no face is detected? For example, can some frames be skipped or something similar?

- Human library version? v3.0
- Built-in demo or custom code? custom code, but build in have the same issue.
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? esm
- TensorFlow/JS version (if not using bundled module)? wasm
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? browser.. in all of them.
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Android/IOS

Great project, congrats.

**Comment by Sau64** [comment]
update:

i kind of solve it using blazeface-front.json

**Comment by vladmandic** [comment]
a bit more info for you - face detection is much more expensive than face analysis, so `human` performs detection once and if face is found, it tries to keep it "in frame" using some of my tracking algorithms, so there is rarely any need to re-detect (it's tunable via config). but if face is not found, it needs to re-run face detect - thus its much slower. and there is no tunable to "skip n frames if not found".

regarding `blazeface-back` and `blazeface-front`, they are similar models, but tuned very differently. back works with smaller faces that could be anywhere in the frame so analysis of the frame is more expensive. front assumes face is actually in or near the center of the frame and larger, so it only has to try to find it there.

i'm not sure what i could do to help further?

**Comment by Sau64** [comment]
Oh I see, thank you for the explanation, i guess you can close this since there isn’t much it can be done.

With blazeface-front and a lower res it is going much better in mobile.


________________________________
