### ISSUE TITLE
MediaPipe hand detector empty results in web demo

### ISSUE THREAD

**Issue by nicoeiris11** [vladmandic/human#353]
**Issue Description**
Testing the MediaPipe hand detector (`handdetect.json`) in the web demo results in empty hand results.
Checking logs I see for every detection human shows a cached model msg for both detector and skeleton models.

Hand config:
```
hand: {
    enabled: true,
    rotation: true,
    skipFrames: 99,
    skipTime: 1000,
    minConfidence: 0.5,
    iouThreshold: 0.2,
    maxDetected: 2,
    landmarks: true,
    detector: {
      modelPath: "handdetect.json",
    },
    skeleton: {
      modelPath: "handlandmark-lite.json",
    },
  },
```

Logs:
![image](https://user-images.githubusercontent.com/17889735/231167361-bd348f0b-eb15-4e45-bee2-955fa67942c8.png)

**Comment by vladmandic** [comment]
sorry this somehow completely fell under the radar.
fixed now, will publish on github and npmjs later today.
