### ISSUE TITLE
TypeError: Human is not a constructor

### ISSUE THREAD

**Issue by lijualivenow** [vladmandic/human#357]
Hi, I am getting the following error
Uncaught TypeError: Human is not a constructor

here  is my code

```
<script id="humanScript" crossorigin="anonymous" ></script>

<script type="module">
  console.log('here')
  const humanScript = document.getElementById('humanScript')
  console.log('---', humanScript.id)
  humanScript.onload = () => {
    console.log('onload')
    window.Human = Human
    // window.Human = Human.constructor
    // window.Human = Human.constructor
   // console.log(Human.constructor);

    const config = {backend: 'webgl'}
    const human = new Human(config)
  }

  humanScript.onerror = (error) => {
    console.log('onerror', error)
  }

  const src1 = 'https://cdn.jsdelivr.net/npm/@vladmandic/human/dist/human.js'
  const src2 = 'https://unpkg.dev/@vladmandic/human/dist/human.js'
  const src3 = 'https://cdnjs.cloudflare.com/ajax/libs/human/3.0.0/human.js'

  humanScript.setAttribute('src', src2)
</script>
```

**Comment by vladmandic** [comment]
that is a very weird way to do script imports, but ok, that's your choice.
i think that you might end-up with double wrapped script, so you need to do `const human = new Human.Human(config)`

**Comment by vladmandic** [comment]
closing as no updates provided.

**Comment by tbreimer** [comment]
I had a similar issue and this resolved it for me, however I imported in the way suggested on the installation page with the IIFE script.


```
<!DOCTYPE html>
<script src="dist/human.js"></script>
<script>
const human = new Human();
</script>
```


Produces the `Uncaught TypeError: Human is not a constructor`

However,

```
<!DOCTYPE html>
<script src="dist/human.js"></script>
<script>
const human = new Human.Human();
</script>
```

works just fine. I'm still a JS noob so it's probably just a misunderstanding on my part, but just wondering.

**Comment by Zireael07** [comment]
Had the same issue. @tbreimer's fix fixed it for me too.

BTW video demo claims to be standalone, but it isn't - I'm still finding missing files and copying them over
