### ISSUE TITLE
Calling human.load method fails with external tensorflow

### ISSUE THREAD

**Issue by hacktronics** [vladmandic/human#359]
**Issue Description**
While calling the human.load, it fails with errors

**Steps to Reproduce**
const tf = require('@tensorflow/tfjs');
const wasm = require('@tensorflow/tfjs-backend-wasm');
const HUMAN = require('@vladmandic/human/dist/human.esm-nobundle');
        const config = {
            backend: 'wasm',
            wasmPath: `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@${tf.version_core}/dist/`,
            modelBasePath: '/static/models/human/'
        };
        wasm.setWasmPaths(config.wasmPath);
        tf.setBackend('wasm').then(() => {
            tf.ready().then(() => {
                this.human = new HUMAN.Human(config);
                this.human.load().then(() => {
                    this.human.warmup().then(() => {
                        log.info('Human model loaded');
                        this.modelLoaded = true;
                    });
                });
            });
        });

**Expected Behavior**
the load call should work
**Environment**
hardware webgl not there, chrome on windows
- Human library version? 02:06:16.782 Human: version: 3.0.5
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? nobundle
- TensorFlow/JS version (if not using bundled module)? 4.5.0
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Windows 10
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? React

**Diagnostics**
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at human.esm-nobundle.js:99:1
    at Array.map (<anonymous>)
    at h2 (human.esm-nobundle.js:99:1)
    at kn (human.esm-nobundle.js:121:1)
    at i2.load (human.esm-nobundle.js:121:1)
    at Yn.load (human.esm-nobundle.js:840:1)

**Comment by vladmandic** [comment]
> const HUMAN = require('@vladmandic/human/dist/human.esm-nobundle');

you're using browser ESM module in NodeJS.
use appropriate version of human, for example `human.node-wasm.js`

**Comment by hacktronics** [comment]
Using const HUMAN = require('@vladmandic/human/dist/human.node-wasm');
gives the same error. I am using nodejs, but my application is client side only

**Comment by hacktronics** [comment]
human.node-wasm.js:99 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at human.node-wasm.js:99:1
    at Array.map (<anonymous>)
    at Q2 (human.node-wasm.js:99:1)
    at uo (human.node-wasm.js:121:1)
    at G2.load (human.node-wasm.js:121:1)
    at k1.load (human.node-wasm.js:840:1)

**Comment by vladmandic** [comment]
the fact you have the same issue is valid and i would have reopened the issue and tried to reproduce it, but thumbs down? nobody is forcing you to use this library.

**Comment by hacktronics** [comment]
thumbs down is for the solution, not the library. The comment was marked as solution and closed, so thumbs down signify to other users, that this is not correct.
I didn't know you would take that personally. At hacktronics we love your libraries and already uses face-api in our free offering at https://ide.codeskool.cc to teach kids programming.
So sorry if it offended you. Just wanted to use the human library to make a better scratch extension, but currently stuck, as its not working for me. Scratch itself is pretty old and using any new library is a tough challenge, but I believe it would become the perfect example of your API.

**Comment by vladmandic** [comment]
next time try saying you've tried using correct lib and problem remains - if i ignore you, then tumbs down is appropriate, not before.

anyhow, this works:

```shell
npm install @vladmandic/human @tensorflow/tfjs-core @tensorflow/tfjs-converter
```

```js
const tf = require('@tensorflow/tfjs-core');
const wasm = require('@tensorflow/tfjs-backend-wasm');
const Human = require('./dist/human.node-wasm.js');

const config = {
  backend: 'wasm',
  modelBasePath: 'https://vladmandic.github.io/human-models/models/',
  wasmPath: `https://cdn.jsdelivr.net/npm/@tensorflow/tfjs-backend-wasm@${tf.version_core}/dist/`,
};

async function main() {
  wasm.setWasmPaths(config.wasmPath, true);
  const ok = await tf.setBackend('wasm');
  await tf.ready();
  Human.env.updateBackend();
  console.log(Human.env.wasm); // shows that human wasm test passed
  const human = new Human.Human(config);
  await human.load();
  await human.warmup();
}

main();
```

**Comment by hacktronics** [comment]
This works, so you can't use tfjs, you have to use tfjs-core?

**Comment by vladmandic** [comment]
`@tensorflow/tfjs` is just a bundle of 10 separate tfjs packages. `tfjs-core` is part of it (and its much smaller). `human` internally requires it for non-bundled versions, so yes, use that.
