### ISSUE TITLE
Human deployment in windows environment 

### ISSUE THREAD

**Issue by MallekAbd** [vladmandic/human#360]
Thank you sir for this amazing project, I've an issue if you could solve it or demystify it please,  I've run the demo online and everything worked well, but when I tried to clone the repo and run it on my local pc, I get lost , so could you share with me how to test human locally in windows? I mean what are the requirements? Etc. 
Thank you sir.

**Comment by vladmandic** [comment]
1. install [nodejs](https://nodejs.org/en)
2. pick one from below:
- install human from npm: `npm install @vladmandic/human`
- install git and clone human repo: `git clone --depth 1 https://github.com/vladmandic/human`
- download snapshot from releases: <https://github.com/vladmandic/human/releases>
3. install dependencies: `npm install`  

and you're ready to start developing your solutions

to run demo web server as well and not just library,  
4. install dev dependencies: `npm install --production=false`
5. run it: `npm run dev`
6. follow instructions on the screen
