### ISSUE TITLE
i cant take the variable that contain the final result that shows in canvas 

### ISSUE THREAD

**Issue by menna1235** [vladmandic/human#361]
i am trying to take the variable that contain the final result that shows in canvas  and put them in text file but i cant seem to find that final result , thanks in advance

**Comment by vladmandic** [comment]
human result is json object with full data, but true - there is no output canvas as i cannot know how does user want that canvas to look.

you can create HTMLCanvasElement yourself (or use pre-existing one), for example:
```js
canvas = document.createElement('canvas');
canvas.width = 512;
canvas.height = 512;
```

and use built-in `Human` helper methods to draw results on it:
```js
res = await human.detect(input)
drawOptions = { bodyLabels: `person confidence [score] and ${human.result?.body?.[0]?.keypoints.length} keypoints` };
await human.draw.all(canvas, res, drawOptions);
```

for description of all draw options, look at docs interface `DrawOptions`
