### ISSUE TITLE
Module not found: Can't resolve '@tensorflow/tfjs-node' 

### ISSUE THREAD

**Issue by raphael-arce** [vladmandic/human#364]
**Issue Description**

When importing the library as described in https://github.com/vladmandic/human/wiki/Install#22-with-bundler , I'm getting this error message:  

![Bildschirmfoto 2023-05-26 um 10 51 39](https://github.com/vladmandic/human/assets/8709861/3eaea30c-b551-419a-9e9f-9fa518dca2e2)

Interestingly, it seems the default export somehow resolves `human/dist/human.node.js`, and not `@vladmandic/human/dist/human.esm.js` as stated in the installation instructions. 

**Steps to Reproduce**

1. Create a new nextjs project: `npx create-next-app@latest` (I used all settings selected by default)
2. Add in the following snippet in  `src/app/page.tsx`:
```JavaScript
import Human from '@vladmandic/human';

const human = new Human();
```

**Expected Behavior**

to not throw an error

**Environment**

- Human library version?
  -  3.0.6
- Built-in demo or custom code? 
  - custom
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? 
  - esm
- TensorFlow/JS version (if not using bundled module)?
  - bundled (i think?)
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
  -  Browser (Firefox)
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? 
  - MacOS Ventura, M2
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)? 
  - I think it's NextJS' default, so I think it's [SWC](https://swc.rs/), but i'm not sure
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? 
  - NextJS

**Diagnostics**

Cannot do the diagnostics step because it crashes before an instance of `human` is created

**Additional**

Package.json: 

```JSON
{
  "name": "human-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@types/node": "20.2.4",
    "@types/react": "18.2.7",
    "@types/react-dom": "18.2.4",
    "@vladmandic/human": "3.0.6",
    "autoprefixer": "10.4.14",
    "eslint": "8.41.0",
    "eslint-config-next": "13.4.4",
    "next": "13.4.4",
    "postcss": "8.4.23",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "tailwindcss": "3.3.2",
    "typescript": "5.0.4"
  }
}
```

Gist: https://gist.github.com/raphael-arce/f78c8f2cd8937dd673b7e8d83e2a2df7

**Comment by vladmandic** [comment]
> Interestingly, it seems the default export somehow resolves human/dist/human.node.js, and not @vladmandic/human/dist/human.esm.js as stated in the installation instructions.

Your assumption is wrong as you're using Next.JS which is by definition an SSR engine, so when it loads anything by default it shows up as NodeJS app, not browser app.

if you want to load browser esm, you can do that, but you need to do it from browser part of next.js app.

and there is a demo app that shows how to do that - its even mentioned in the readme itself: <https://github.com/vladmandic/human-next>
