### ISSUE TITLE
Crashing on iOS

### ISSUE THREAD

**Issue by mattduff707** [vladmandic/human#368]
**Issue Description**
I have been working on a project that uses human to detect a users face position/angle and take photos when it is in specific positions. It has been working perfectly on desktop but when I test on my phone (Iphone 8 iOS 16.2) the page reloads and I get the "A problem has repeatedly occurred error" in the browser but with no errors logged.

[code](https://gist.github.com/mattduff707/52cfcdb5af24001590ab5e7d0ef56e73)

The above code is a stripped back version of the code with the same issue. the load, warmup and webCam functions all run without issue. The crash seems to occur when calling `human.detect(videoRef.current!)`

**Environment**

- Human library version: 3.0.6 using CDN
- Framework: Remix JS

**Comment by vladmandic** [comment]
i don't have an ios device for testing right now  

i took a quick look at your code and you already have `debug: true`, so there should be a bit more information logged in browser console.

also, i'm assuming this is using safari? it has a really bad webgl implementation. did you try using some other backend?

**Comment by mattduff707** [comment]
I tried with cpu and webgpu with no success. Nothing related to the detect method seems to be logging, but the webcam does seem to set up correctly beforehand. It is hard for me to debug since I can only test on production due to limitations of remix server and HTTPS to allow camera on iOS (I don't have a mac). 

![image](https://github.com/vladmandic/human/assets/51209857/d867f986-7cc5-4fc6-893a-d75c9c5ca90b)

**Comment by vladmandic** [comment]
webgpu is not available on your system, so thats just going to do a fallback to webgl.
i was curious about wasm as that is completely different than webgl. but if even cpu crashes, thats bad.
any chance you can do a quick test using chome instead of safari, just to confirm?

**Comment by mattduff707** [comment]
Haha yeah, I noticed that as I posted the logs. Same thing happening on chrome. Your demo's work on iOS so it leads me to believe something related to my code may be the issue

**Comment by vladmandic** [comment]
hmm, if the demo works, then yeah, that would be logical conclusion...
