### ISSUE TITLE
Crashes with React Native on Android

### ISSUE THREAD

**Issue by Lamarcke** [vladmandic/human#373]
**Issue Description**
Hello. I'm trying to integrate Human with React Native, for a mobile android app. I've been wrapping my head around this for the past 3 days, to no avail. I would greatly appreciate any help in setting this up.

**Steps to Reproduce**
- Clone this repository: https://github.com/Lamarcke/human-test
- `yarn`
- `yarn start`

The following error (which crashes the APP) should appear:
```
Cannot evaluate flag 'CANVAS2D_WILL_READ_FREQUENTLY_FOR_GPU': no evaluation function found.
```

I'm also receiving the "The kenerl x for backend "wasm" is already registered" warnings.

**Some extra info**: 
I've already tried to set this up using the latest expo, tfjs-react-native (using --force to override the outdated dependencies), expo-gl versions. The current `@tensorflow/tfjs-react-native` is using outdated packages, so i'm trying to their example which include tested versions of the dependencies. The example does work, but `human` still doesn't.

I've also tried to use `react-native-canvas` the way you described here: https://github.com/vladmandic/human/issues/327#issuecomment-1410359418 and just importing the package.

**Expected Behavior**
Human should load since the no-bundle version is being used, and `tfjs-react-native` is set up following their example (https://github.com/tensorflow/tfjs-examples/tree/master/react-native/image-classification). I also have `react-native-canvas` installed.

**Environment**
React Native with Expo

- Human library version? ^3.0.7
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)? 0.8.0 (`tfjs-react-native`)
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? Node 18
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Android on Expo Go
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? Expo & React Native

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
```json
{
  "name": "image-classification-with-tfjs-react-native-expo",
  "main": "index.js",
  "version": "0.0.1",
  "license": "Apache-2.0",
  "scripts": {
    "start": "expo start",
    "start:tunnel": "expo start --tunnel"
  },
  "dependencies": {
    "@react-native-async-storage/async-storage": "~1.17.3",
    "@tensorflow-models/mobilenet": "2.1.0",
    "@tensorflow/tfjs": "3.18.0",
    "@tensorflow/tfjs-backend-wasm": "^4.8.0",
    "@tensorflow/tfjs-backend-webgpu": "^4.8.0",
    "@tensorflow/tfjs-react-native": "0.8.0",
    "@vladmandic/human": "^3.0.7",
    "expo": "~45.0.6",
    "expo-camera": "^12.2.0",
    "expo-file-system": "^14.0.0",
    "expo-gl": "^11.3.0",
    "expo-gl-cpp": "^11.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-canvas": "^0.1.39",
    "react-native-fs": "2.14.1",
    "react-native-gesture-handler": "~2.2.1",
    "react-native-webview": "^13.2.2"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0",
    "@expo/webpack-config": "^0.15.0",
    "@types/react": "~16.9.35",
    "@types/react-native": "~0.63.2",
    "babel-preset-expo": "~8.3.0",
    "jest-expo": "~41.0.0",
    "typescript": "~4.0.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}

```
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
given the lack of progress on official tfjs-react-native package, i've halted any testing on react-native platform a while ago and as a result, recent versions of `human` may not be compatible out-of-the-box.

if you feel comfortable, install human in dev mode and change internal code where needed (rebuild is pretty fast).
otherwise, i'm not sure when this will get out of my backlog.

since react-native is not officially supported, i'll mark this as feature request.

**Comment by Lamarcke** [comment]
> given the lack of progress on official tfjs-react-native package, i've halted any testing on react-native platform a while ago and as a result, recent versions of `human` may not be compatible out-of-the-box.
> 
> if you feel comfortable, install human in dev mode and change internal code where needed (rebuild is pretty fast). otherwise, i'm not sure when this will get out of my backlog.
> 
> since react-native is not officially supported, i'll mark this as feature request.

Thank you for the quick response. I have moved over to a PWA architecture because it's a lot easier to work with Human directly on the browser. You have done an incredible work, thank you.

**Comment by vladmandic** [comment]
in that case, i'm going to close this issue as not much i can do about it right now, but feel free to report any problems you might have.
