### ISSUE TITLE
what's the models format and is there a way to convert them to onnx?

### ISSUE THREAD

**Issue by chamecall** [vladmandic/human#374]

**Comment by vladmandic** [comment]
all models are in tensorflow/js graph model format.
there are 3rd party utilities to convert tfjs graph models to tf saved model and then to onnx.
but what would you do with such models as they all require a lot of pre and post processing?

**Comment by chamecall** [comment]
> all models are in tensorflow/js graph model format. there are 3rd party utilities to convert tfjs graph models to tf saved model and then to onnx. but what would you do with such models as they all require a lot of pre and post processing?

I'm mostly interested in age/gender estimation models. Is your point also relevant for these models?

**Comment by vladmandic** [comment]
also relevant. note that age/gender detection require precisely cropped image of the face and that is achieved here by running face detection first. you can convert models to onnx, but results are not going to be what you're hoping for.
