### ISSUE TITLE
gestures should support multiple persons

### ISSUE THREAD

**Issue by Jimmysh** [vladmandic/human#38]
When multiple people's face gesture. The information can't be matched to real one.

**Comment by vladmandic** [comment]
can you elaborate - why not? each face returns separate face embedding feature vector, so it's just a question of having a loop to go through all detected faces.

**Comment by Jimmysh** [comment]
the result.gesture.face data can't match with face.
```JS
// result.gesture.face
 ["facing left", "head down", "facing camera", "blink left eye", "blink right eye"]
```

**Comment by vladmandic** [comment]
ahh, my bad, i was talking about embedding.
yes, gestures currently mashes everything together - and it's not only about face.

i need to redesign that part.

**Comment by vladmandic** [comment]
Implemented via <https://github.com/vladmandic/human/commit/f336b7772fd81bf8dbf5838a04f4f96ffd1534c0>

Gesture is now returning a different format, it's an array of objects which also includes index of a person that gesture belongs to.  

Documentation and demo have also been updated.

Example output:
```js
[
  {face: "0", gesture: "facing camera"}
  {face: "1", gesture: "facing camera"}
  {face: "0", gesture: "head down"}
  {body: "0", gesture: "i give up"}
  {body: "1", gesture: "leaning left"}
  {hand: "0", gesture: "thumb forward middlefinger up"}
]
```

Please confirm before this case can be closed.

**Comment by vladmandic** [comment]
closing as resolved.
