### ISSUE TITLE
Seems to detect only one hand at a time?

### ISSUE THREAD

**Issue by Zireael07** [vladmandic/human#381]
**Issue Description**
Title

**Steps to Reproduce**
Web demo (both full and lite) with a webcam pointed at my hands on a chair's handrests

**Expected Behavior**
Both hands are detected

**Environment**

- Human library version?
- Built-in demo or custom code? web demo
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
Set max hands in config. Default is 1 for 0erformance reasons.

**Comment by Zireael07** [comment]
No such config that I can see in https://vladmandic.github.io/human/demo/index.html , let alone the lite versions :(

**Comment by vladmandic** [comment]
Not every config option is used in demo - it's just a demo.

But config options are fully documented, so check the docs.

**Comment by Zireael07** [comment]
IMHO this option should be in the **full** demo since it claims to be, well, full, and lack of the option makes it seem like the library only supports one hand (which is a common limitation of hand pose libraries)

**Comment by vladmandic** [comment]
That's a fair point.
