### ISSUE TITLE
Typos and the like

### ISSUE THREAD

**Issue by Zireael07** [vladmandic/human#382]
**Issue Description**

[ ] https://github.com/vladmandic/human/wiki/Config has "BaseModelPath" instead of "modelBasePath"

[ ]  "Source" link for video demo is a 404 (I managed to find the source manually, so I think it's just a broken link)

[ ] https://github.com/vladmandic/human/wiki/Gesture claims gesture recognition lives in gesture.js while it is gesture.**t**s

**Steps to Reproduce**

N/A

**Expected Behavior**
N/A
**Environment**

- Human library version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
updated.

**Comment by Zireael07** [comment]
Also: gestures wiki page does NOT tell us how to add a new gesture OR disable preexisting ones.

**Comment by vladmandic** [comment]
I planned to make gestures a user feature, but there was no demand at the time so I left it as a dev feature.
Any dev can see the code and modify or expand them.

**Comment by Zireael07** [comment]
That would require forking human.js itself, though?

**Comment by vladmandic** [comment]
you can, but not necessary. all code is included, modify `gestures.ts` as required and rebuild human using `npm run build`

**Comment by Zireael07** [comment]
Thanks. ^^ this info should be somewhere in the gestures doc

**Comment by vladmandic** [comment]
add that one line
