### ISSUE TITLE
the same photo,human.esm.js human.js both Inconsistent detection results

### ISSUE THREAD

**Issue by catherchen** [vladmandic/human#387]
i use the same photo
when i use human.js in worker,every time the test results are different
![image](https://github.com/vladmandic/human/assets/30284748/50b657bd-6460-4ce4-ab4a-5479ec808219)
but wheni use human.esm.js in main js thread，detection result is stable
![image](https://github.com/vladmandic/human/assets/30284748/72d8f6d6-a4b8-4ccc-bc7f-af7aaca12cbc)

**Comment by vladmandic** [comment]
whats your input? (e.g. is it image, whats the resolution, etc.)

note that when working in main thread, input can be processed nearly-directly if data is available.

but when working in worker thread, input has to be copied to canvas and then transferred to worker thread as worker thread does not have direct access to input. so question is how are you transferring input to worker thread?

**Comment by vladmandic** [comment]
closing due to idle.
