### ISSUE TITLE
Unable to install packages

### ISSUE THREAD

**Issue by rainstorm-studio-australia** [vladmandic/human#389]
Hello.

I have run `npm install` but it does not install any packages
![image](https://github.com/vladmandic/human/assets/19511189/920f272e-383d-45fb-a3e3-46a5f4053059)
Can you please check?

Human version: 3.1.2 
Node version: 18.17.1
NPM version:  9.5.0
Windows version: 11 (x64)

**Comment by vladmandic** [comment]
what dependencies? human does not have runtime dependencies.
if you want to install dev dependencies (ony required if you want to build human from source), then run `npm i --dev`.
