### ISSUE TITLE
Error when run  npm run build

### ISSUE THREAD

**Issue by dongphuongman** [vladmandic/human#391]
Error when run npm run build with human@3.1.2
human-3.1.2\node_modules\@vladmandic\build\node_modules\typedoc\dist\lib\converter\types.js:559
            elements = elements?.map((el, i) => new models_1.NamedTupleMember(namedDeclarations[i].name.getText(), !!namedDeclarations[i].questionToken, (0, reflections_1.removeUndefined)(el)));

**Comment by vladmandic** [comment]
Which version of typescript?
Typedoc has issues with typescript 5.2, use typescript 5.1.

**Comment by dongphuongman** [comment]
> Which version of typescript? Typedoc has issues with typescript 5.2, use typescript 5.1.

Thank you!
My typescript 5.2.2
