### ISSUE TITLE
human.tf.memory().numTensors after human.load() doesn't give zero

### ISSUE THREAD

**Issue by alganzory** [vladmandic/human#399]
**Issue Description**
As the title says, when I print human.tf.memory().numTensors right after human.load, I don't get 0, instead, I get 248, I am not sure if that's expected or not

**Steps to Reproduce**
```
const human = new Human(HUMAN_CONFIG);
human.load().then(() => {
			console.log("human loaded", human.tf.memory().numTensors);
		})
```		
This is the output in the console:
```
16:15:02.073 Human: tf engine state: 14503752 bytes 248 tensors
offscreen.js:9353 human loaded 248
```
**Expected Behavior**

I am not sure if it should start at zero, that might be a silly expectation but I really don't know.

**Environment**

```
16:15:01.988 Human: version: 3.1.2
offscreen.js:8520 16:15:01.989 Human: tfjs version: 4.11.0
offscreen.js:8520 16:15:01.989 Human: environment: 
{
    "browser": true,
    "node": false,
    "worker": false,
    "platform": "Windows NT 10.0; Win64; x64",
    "agent": "Mozilla/5.0 AppleWebKit/537.36 Chrome/119.0.0.0 Safari/537.36",
    "backends": [],
    "tfjs": {
        "version": "4.11.0"
    },
    "offscreen": true,
    "tensorflow": {},
    "wasm": {},
    "webgl": {},
    "webgpu": {},
    "cpu": {
        "flags": []
    }
}
```

here's my config: 

```
const HUMAN_CONFIG = {
	modelBasePath: modelsUrl,
	backend: "webgl",
	debug: true,
	cacheSensitivity: 0.9,
	warmup: "none",
	face: {
		enabled: true,
		iris: { enabled: false },
		mesh: { enabled: false },
		emotion: { enabled: false },
		detector: {
			modelPath: "blazeface.json",
			maxDetected: 3,
		},
		description: {
			enabled: true,
			modelPath: "faceres.json",
		},
	},
	body: {
		enabled: false,
	},
	hand: {
		enabled: false,
	},
	gesture: {
		enabled: false,
	},
	object: {
		enabled: false,
	},
};

```

**Additional**

- This is used in a chrome extension in an offscreen document (chrome.offscreen), I have also attempted using different backends, same results. I would also like to ask you for some tips to optimize for speed and make detection as light as possible as it's used in a browser extension

Thanks for the great work

**Comment by vladmandic** [comment]
Models are also using tensors! So only time you'll get zero is if all models are disabled.
The goal is thar number does not grow over time as that would indicate a memory leak.

Its also normal that it varies during usage (temp tensors, etc.), but it should always return to same value once it's done.

**Comment by alganzory** [comment]
Thanks for the clarification, do you have any tips or advise for optimizations to be speed up detection and make it less resource intensive if I am using human in the context of a chrome extension?

**Comment by vladmandic** [comment]
i'm not sure what to add, you're already using webgl, number of models is minimal and cache sensitivity is set very low.
only major impact would be to reduce maxDetected as faceres that you have enabled runs for each of detected faces.

**Comment by alganzory** [comment]
what about the image size? currently I am not using the filters to reduce image size because I am not sure how to maintain aspect ratio, basically I wanna reduce the image size if the width is greater than a max width or the height is greater than a max height, but right now I can only do either of these because if I provide both to the filters then it will just resize to them and will distort the aspect ratio, is my understanding right?
Also, what's the smallest you'd recommend resizing the image to before you notice a decrease in the accuracy? given that I am using blazeface back model

**Comment by vladmandic** [comment]
resolutions on which each individual models have been trained on are in wiki - specifically faceres is trained on 224px, so your desired input resolution should be such that cropped face is ~224px - more that that and its pointless, less than that and you loose precision. what does that mean for overal resolution? well, depends if faces are near or far from the camera.

but yes, higher resolution does come with performance impact - and not only inside human, due to offscreen usage there is extra copy to transfer image context to human and that is not as fast as i'd like it to be in chrome - but it cannot be avoided.

regarding filters and aspect ratio - its handled automatically if you provide just width or just height.
