### ISSUE TITLE
Can't install dev-dependencies

### ISSUE THREAD

**Issue by flyingfishzxf** [vladmandic/human#410]
**Issue Description**
<img width="773" alt="image" src="https://github.com/vladmandic/human/assets/8775528/b8d9ea18-5f99-4ad7-8a01-811406eaebfe">
<img width="531" alt="image" src="https://github.com/vladmandic/human/assets/8775528/75f20011-9520-4f7e-9e53-ce459d158cd5">

**Steps to Reproduce**
1. git clone repo from github
2. execute 'npm install --dev'

**Expected Behavior**
can install dependencies successfully.

**Environment**

- Human library version? 3.2.0
- Built-in demo or custom code? Built-in
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by flyingfishzxf** [comment]
Sorry, I used a low version npm to install, so I failed.
After upgrading the node and npm version, I successfully install the dependencies.
I will close this issue.

**Comment by iamlaobie** [comment]
> Sorry, I used a low version npm to install, so I failed. After upgrading the node and npm version, I successfully install the dependencies. I will close this issue.

I encounter the same problem, what version you used when you resolve it please?
