### ISSUE TITLE
Human inferencing stops after ~5 mins on Chrome on Windows 

### ISSUE THREAD

**Issue by arvindsaraf** [vladmandic/human#424]
**Issue Description**

I just upgraded from faceapi to human, and here's the core inferencing code, essentially - aimed at inferencing on a frame every second:
`while (new Date() < endTime) {
      snapshotTime = new Date();
      const result = await this.human.detect(this.human.webcam.element);

      await this.uploadData(result, this.human.process.canvas, snapshotTime);

      const processingTime = new Date() - snapshotTime;
      const sleepTime = 1*1000 - processingTime;
      if (sleepTime > 0) {
        await new Promise(resolve => setTimeout(resolve, sleepTime));
      }
`

After ~5mins, the inferencing stops giving this error:
```
D3D12 closing pending command list failed with E_OUTOFMEMORY (0x8007000E)
 - While handling unexpected error type Internal when allowed errors are (Validation|DeviceLost).
    at CheckHRESULTImpl (..\..\third_party\dawn\src\dawn\native\d3d\D3DError.cpp:111)
    at ExecuteCommandList (..\..\third_party\dawn\src\dawn\native\d3d12\CommandRecordingContext.cpp:91)
    at SubmitImpl (..\..\third_party\dawn\src\dawn\native\d3d12\QueueD3D12.cpp:70)
    at SubmitInternal (..\..\third_party\dawn\src\dawn\native\Queue.cpp:663)

Backend messages:
 * Device removed reason: S_OK (0x00000000)

```

**Steps to Reproduce**

**Expected Behavior**

**Environment**

- Human library version? 3.2.1 
- Built-in demo or custom code? Custom-code, example below
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)? 4.17.0
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? Chrome, Node v20.11.0
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Windows
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? NextJS

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
set debug=true in your config and upload entire log leading up to first error, there is nothing i can do without the log.

**Comment by vladmandic** [comment]
any updates?
