### ISSUE TITLE
Face recognition is not working

### ISSUE THREAD

**Issue by predator1995** [vladmandic/human#426]
In some devices on Windows operating system, screen flickers and face is not recognized. There were some situations when on a particular device with different popular browsers like Yandex, Google Chrome and Microsoft Edge, face recognition library did not work. On other devices library worked in Firefox browser. Now, there is no exact solution to apply library. On Mac devices lilbrary works in a proper way.

https://github.com/vladmandic/human/assets/50018996/1198ff38-f1c5-4e4d-87c3-53c83160bbb8

There is screenshot of how library could not work in Microsoft Edge browser. Other browsers acted the same.

**Comment by predator1995** [comment]
> that seems to be a webcam control item where its adjusting brightness controls randomly. and apps you've tried are just example apps, that is not core library functionality. if there is an issue with the core library, post actual log.

we have tried the same extra camera (plugged via USB) on MacOs and Windows operating systems. Face recognition could work only in case with MacOs. On Windows - worked in some cases with specific browsers. The problem is in operating system. Could you check this out?

**Comment by vladmandic** [comment]
> Could you check this out?

could i check it out? how?

**Comment by predator1995** [comment]
I suggest to organize online meeting to perform you how face recognition does not work on our devices (by sharing the screen). Moreover, we would like to sponsor you, if you help us with that.

**Comment by vladmandic** [comment]
you need to check your side before even discussing such option, i'm not typically inclined to jump to online meetings on every issue reported. 

first thing i'd check is if webcam settings are fluctuating, check values in `human.webcam.settings` on each processed frame

**Comment by predator1995** [comment]
I've checked everything from my side, therefore told you about current problem. On video uploaded on first comment, I've showed you the problem that your live demo is not working on my laptop both with internal and external cameras. It is not related to brightness, because I've checked demo in different devices with different browsers and results differed from each other. For example, on Macbook, there were no problems with face recognition. On Windows operating systems, I've tried several laptops. On some laptops,  in Google Chrome browser face was not recognized, but on Microsoft Edge or Yandex Browser face was recognized. On other laptops - vice versa. Therefore I've said you that something wrong with operating systems or browsers while recognizing.

**Comment by predator1995** [comment]
> > Could you check this out?
> 
> could i check it out? how?

Hi again)) Sorry if I misunderstood you, I wanted to check you out your live demo on **Laptop** with Windows 11 on different browsers, I guess that's a global problem. As I checked it by myself, I could get a good result of working of face recognition on Windows operating system properly.
