### ISSUE TITLE
Blaze resized image normalization

### ISSUE THREAD

**Issue by saeidn95** [vladmandic/human#446]
**Issue Description**
[human/src/face/blazeface.ts](https://github.com/vladmandic/human/blob/62396317f5c31b2ec5bc7de2e9eb53b8978b9f28/src/face/blazeface.ts#L60)
  t.normalized = tf.sub(t.div, constants.tf05); does not normalize to (-1, 1).

For normalization to (-1, 1) please change to 
t.normalized = tf.sub(t.div, constants.tf1);

t.div = tf.div(t.resized, constants.tf127);
t.normalized = tf.sub(t.div, constants.tf05);
normalized = image / 127 - 0.5

const normalizedImage = tf.mul(tf.sub(tf.div(resizedImage, 255), 0.5), 2);
normalized = (image / 255 - 0.5) * 2

**Comment by vladmandic** [comment]
done.
