### ISSUE TITLE
Hand Pose very slow

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#45]
**Issue Description**
handpose one hand performance very slow

**Steps to Reproduce**
Open live demo
Enable hand pose only
Set max objects to 1
**Expected Behavior**
Not slow or choppy
**Environment
Chrome (87)

See attached video for demonstration
[human-handpose.zip](https://github.com/vladmandic/human/files/5674045/human-handpose.zip)

**Comment by vladmandic** [comment]
quick q: is this a regression compared to previous versions or just new issue describing old problem?  
and to confirm, this is using `webgl` backend? it's hard to tell from the video you've posted.

and did you try changing default parameters? seems that hand detection looses box and then waits for skip-frames to try to find it again. when i reduce confidence to 0.1, hand box stays in focus much longer.

**Comment by delebash** [comment]
The previous version wasn’t so slow, it was more of a bounding box problem.  I also checked with only facemesh enabled and I have the same problem although not as bad.  If I move my face around just a bit the same slowness and  freezing happens.  I also tried this on firefox with the similar results.  Firefox was a little better but still froze at times.

I am using webgl. Thanks

**Comment by vladmandic** [comment]
hmm...looking now and performance does seem lower, but i can't explain it as none of recent changes would justify it.
i'll investigate.

**Comment by vladmandic** [comment]
first update:
- optimizations for face detection - new config setting to bypass complicated rotation mapping if face is within 20 degrees.
- staggered skipFrames for all models so they don't trigger at the same time

overall, it's about 10% faster.

now onto my least favorite model - hand.

**Comment by delebash** [comment]
Thanks, I will try it.  I know I keep bugging you about the hand model but thanks for taking the time to look at it..  Could you upload a screen video capture of you using the live demo so I can see how it should perform?

Thanks.

**Comment by vladmandic** [comment]
second update:
- removed offset calculation for hand bounding box and used slightly larger box instead.
   this seems to improve bounding box re-usage.
- implemented same skip-image-rotation trick for hand, configurable via `config.hand.rotation`
   result is even bigger performance gain on hand, almost 50%
   only time when this skip-rotation doesn't work is if hand is inverted, otherwise it's pretty flexible with angles.

there is new option in demo UI to enable/disable detection rotation so you can check the impact.

one remaining thing is that i'm not happy with initial hand detection - takes two passes for it to become framed.

**Comment by delebash** [comment]
Thank you.  The original problem seems to be fixed but I don't think it was the setting.  I am not sure exactly why it was frozen because the orginal hand-pose worked even when human was frozen.  Tested both after reboot with same results.  However human hand pose seems to not freeze up anymore.  The detection rotation seems to make a difference.  Thanks

**Comment by vladmandic** [comment]
third update: 
- updated warmup and caching a bit so initial detection picks up faster.
- added warmup options `none`, `face`, `full` depending on how much user wants to spend on warmup

i'm closing this issue as i don't want too much to go under single umbrella, but feel free to open a new one in the future if needed.
