### ISSUE TITLE
Recognizing the wrong person

### ISSUE THREAD

**Issue by rafaelsilvade** [vladmandic/human#451]
**Issue Description**
Hi,

After several tests and I managed to capture the evidence.

As you can see, people are different and yet the model puts a similarity of 0.74.
I tested on other sites and models and even the facejs version below your lib doesn't match the two photos.

![image](https://github.com/vladmandic/human/assets/14947650/70c344b3-c686-4116-872b-1e44290668d8)

I am attaching the two photos, for reasons of privacy for both people, could I not leave the images public?

![match_Renan](https://github.com/vladmandic/human/assets/14947650/da7cbee0-d1c9-47e7-8cab-609d052b23e8)
![661965bedc73a](https://github.com/vladmandic/human/assets/14947650/03cf0778-5152-44f7-bb28-82a272256491)

**Steps to Reproduce**

compare the similarity between the two images

**Expected Behavior**

**Environment**
humanConfig = {
    debug: false,
    modelBasePath: '../assets/models/',
    filter: { enabled: true, equalization: true, flip: false, width: 0 },
    face: {
      enabled: true,
      detector: { rotation: true, maxDetected: 1, minConfidence: 0.6, return: true, mask: false, skipFrames: 1, iouThreshold: 0.5 },
      iris: { enabled: true },
      description: { enabled: true, minConfidence: 0.6, skipFrames: 1 }, // default model for face descriptor extraction is faceres

      //insightface: { enabled: true, modelPath: '../assets/models/insightface-mobilenet-swish.json' }, // alternative model
      mesh: { enabled: true },
      emotion: { enabled: false },
      antispoof: { enabled: false },
      liveness: { enabled: false },
      skipFrames: 1
    },
    body: { enabled: false },
    hand: { enabled: false },
    object: { enabled: false },
    gesture: { enabled: true },
    segmentation: { enabled: false },
    async: false
  };
- Human library version? 3.2.1
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? Chrome
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Windows 11
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? Angular

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
this topic has been discussed many times:
- search for more detailed descriptions/conversations - there have been a lot.
- default model for face intentification is choosen because its fast and lightweight,  
  not because its precise. use a different model, human supports several just via config change
- tune other params as needed

and other than those 3 large topics, i really don't have much to add so i'm closing the issue for now.
