### ISSUE TITLE
Feature: Enhance head pose estimation

### ISSUE THREAD

**Issue by saeidn95** [vladmandic/human#464]
**Changes to rotationMatrixToEulerAngle**

Need for dropping the factor of 2 in return values (pitch, yaw and roll) in the function rotationMatrixToEulerAngle (https://github.com/vladmandic/human/blob/1114014bfd6c114baf2d31942382a2b2dc065c7d/src/face/angles.ts#L56)

The formulation can be modified as follows;
var cosThetaZ  = math.sqrt(r00 * r00 +  _r20 * _r20);
// thetaZ = Math.asin(r10);
  thetaZ = Math.tan2(r10, cosThetaZ);

what this change thetaX, thetaY, thetaZ, are within the range of -pi to +pi, and there is no need to scale the return values by 2.

**Comment by vladmandic** [comment]
why not submit a PR?

**Comment by vladmandic** [comment]
it would be better as then your name goes to contributors list. if you can't, I'll deal with it next week.

**Comment by saeidn95** [comment]
Not sure if I did it right, but I did a pull request now.

**Comment by vladmandic** [comment]
sorry for a long delay, somehow this dropped off the radar.
anyhow, you did a pull request on your fork of this repo, you never submitted it to actual upstream (this) repo.
go to https://github.com/vladmandic/human/compare/main...saeidn95:human:main and you can click create pr there.

but...your code is non-functional as it is:
> var cosThetaZ = math.sqrt(r00 * r00 + _r20 * _r20);

there is no `math`, it should be `Math` and there are no `_r20` values, so which ones you wanted to use?
i can test on my side and do the changes if you don't want to deal with pull request, but at give me a working code :)

**Comment by saeidn95** [comment]
Apologies for typos. Please replace _r20 with r20), The equation should be
var cosThetaZ = math.sqrt(r00 * r00 + r20 * r20); 

You can double check that by looking at the formulation that you use in section 2.4 in reference https://www.geometrictools.com/Documentation/EulerAngles.pdf

Please go ahead and do the changes yourself. I would appreciate that. That saves doing a pull request on a code that is wong anyway!

BTW: is there a reason you use _r01, and _r02 instead of r01, and r02 in https://github.com/vladmandic/human/blob/1114014bfd6c114baf2d31942382a2b2dc065c7d/src/face/angles.ts#L56

**Comment by vladmandic** [comment]
> BTW: is there a reason you use _r01, and _r02 instead of r01, and r02 in

underscore in front of variable visually indicates that variable is not actually used in the code.

> Please go ahead and do the changes yourself. I would appreciate that

done, will be pushed to github soon.
