### ISSUE TITLE
info: MediaPipe  javascript api

### ISSUE THREAD

**Issue by delebash** [vladmandic/human#47]
MediaPipe now has it's own javascript api that you can use instead of tensor flow.

https://ai.googleblog.com/2020/12/mediapipe-holistic-simultaneous-face.html

https://google.github.io/mediapipe/getting_started/javascript#ready-to-use-javascript-solutions

**Comment by vladmandic** [comment]
Thanks - I'm impressed how they implemented smoothing.  
And performance is definitely higher than with `human`.  

Unfortunately, cannot use it to learn anything useful as @mediapipe solutions are written in C++ (JS is used just as loader for a custom compiled WASM binary).  

I do see that @mediapipe uses `tflite` models which are normally not even supported on desktop - this is all custom work by @mediapipe and does not rely on a published release of `tensorflow`.  
Even image handling is done using OpenCV binary embedded in @mediapipe WASM module.  

if anything, @mediapipe showcases just how much faster is a native binary code than any JS code that is interpreted in browser and uses a generic framework for backend (which is not unexpected).

**Comment by vladmandic** [comment]
i'm converting this to a discussion topic now that github supports discussions :)
