### ISSUE TITLE
Error: Argument 'x' passed to 'squeeze' must be a Tensor or TensorLike, but got 'null'

### ISSUE THREAD

**Issue by zmk-punchbowl** [vladmandic/human#478]
**Issue Description**

We encountered this error `Error: Argument 'x' passed to 'squeeze' must be a Tensor or TensorLike, but got 'null'`. To be clear, we've been using version `3.2.1` for a while without ever seeing this issue. I'm unsure at this point what caused it.

<img width="1090" alt="Screenshot 2024-07-09 at 11 48 00 AM" src="https://github.com/vladmandic/human/assets/83088000/0152837b-5847-4e33-a733-d961a01190c7">

**Steps to Reproduce**

I'm currently unsure. We're using `human` to detect faces in videos for a while, without this issue. It does not happen regularly. This is the first time I've seen it.

**Expected Behavior**

To not encounter this error (or at least to be able to catch it and proceed).

**Environment**

- Human library version? 3.2.1
- Built-in demo or custom code? Custom code
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? 
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? NodeJS v20.15.0
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Docker image running on Amazon Linux 2 via ECS
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)? `yarn`
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? Running in nodejs, not in the browser.

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by zmk-punchbowl** [comment]
Okay, after some follow-up investigation, I believe this error happened because we were in an unexpected state caused by a previous error (a process ran out of memory and encountered ENOMEM). That would explain why we never saw this before. For us, the bug is the original error (running out of memory). It's possible that this caused us to feed a corrupt/incomplete file into `human`. Could that cause the error above?

**Comment by vladmandic** [comment]
Definitely possible, need to take a look at the code around the stack trace you've posted.

**Comment by zmk-punchbowl** [comment]
> Definitely possible, need to take a look at the code around the stack trace you've posted.

Our main usage looks like this:

```
export async function detectFacesInImage(
  imgFile: string
): Promise<FaceResult[]> {
  const buffer = fs.readFileSync(imgFile);
  const tensor = (await getHuman()).tf.node.decodeImage(buffer);
  const res = await (await getHuman()).detect(tensor);

  // Dispose all tensors
  if (res?.face) {
    res.face.forEach(async (f: FaceResult) =>
      (await getHuman()).tf.dispose(f.tensor)
    );
  }

  return res.face as FaceResult[];
}
```

Our only other call into the library is to assess similarity:

```
      const s = (await getHuman()).match.similarity(
        faceToFind.embedding!,
        face.embedding!
      );
```

**Comment by zmk-punchbowl** [comment]
I think this issue can be closed, since it was caused by a memory leak. However, I believe that memory issue to be related to `human`. I will post that as a new issue, for clarity.
