### ISSUE TITLE
Snapshot Face Detection

### ISSUE THREAD

**Issue by HelpTest24** [vladmandic/human#484]
I want to know if there is one function for print, save the width and height position in file directory. or i need one one third lib like ffmpeg to save image position in one new image?

**Comment by HelpTest24** [comment]
I want to schedule periodic analysis in face detetion to random people and insert to face recognition input. there is one auto input face recognition using the windows system display screen.

**Comment by vladmandic** [comment]
sorry, i don't understand the question?

**Comment by HelpTest24** [comment]
what do you dont understand?

**Comment by vladmandic** [comment]
honestly, nothing. if i say i didn't understand and i'd like to help, then its really up to you to explain the question.
also please the general questions go into discussions, not into product issues.
