### ISSUE TITLE
input error: attempted to use tensor with unrecognized shape: 1,1,196,200,3

### ISSUE THREAD

**Issue by brendon** [vladmandic/human#490]
**Issue Description**
I'm getting the occasional strangely shaped tensor in production:

input error: attempted to use tensor with unrecognized shape: 1,1,196,200,3

**Steps to Reproduce**

Use the attached file for face detection:

![parent-teacher-student-connect-29zb9qh-e1476970719500](https://github.com/user-attachments/assets/adf6e0ac-651f-4d36-af6d-58ed716262b5)

```
const tf = require('@tensorflow/tfjs-node') // Required
const Human = require("@vladmandic/human").default
const app = require("express")()

const human = new Human({
  modelBasePath: 'file://../../node_modules/@vladmandic/human/models'
})

const configuration = {
  backend: 'tensorflow',
  face: {
    enabled: true,
    detector: { maxDetected: 10 }
  },
  body: { enabled: false },
  hand: { enabled: false },
  gesture: { enabled: false },
  filter: { enabled: true, width: 2048 },
  cacheSensitivity: 0
}

    const tensor = human.tf.tidy(() => {
      const decode = human.tf.node.decodeImage(req.files.image.data, 3)
      const expand = human.tf.expandDims(decode, 0)

      return human.tf.cast(expand, 'float32')
    })

    human.detect(tensor, configuration).then(result => {
      res.json(
        map(filter(result.face, { faceScore: 1 }), (face) => {
          return pick(face, ['box', 'boxRaw', 'boxScore'])
        })
      )
    }).catch(() => {
      Bugsnag.notify
      res.status(500).send("Unable to process the image for faces.")
    }).finally(() => {
      human.tf.dispose(tensor)
    })
```

**Expected Behavior**

It shouldn't find a face and shouldn't raise an error.

**Environment**

```
    "@tensorflow/tfjs-node": "^4.21.0",
    "@vladmandic/human": "^3.3.2",
```

**Comment by vladmandic** [comment]
I agree, but please post reproducible code snippet if possible, makes any kind of solution much faster.

**Comment by brendon** [comment]
Ok, will do :) Just a simple node script?

**Comment by brendon** [comment]
Ok, here you go :)

```
const fs = require('fs')
const tf = require('@tensorflow/tfjs-node') // Required
const Human = require("@vladmandic/human").default

const human = new Human({
  modelBasePath: 'file://../../node_modules/@vladmandic/human/models'
})

const configuration = {
  backend: 'tensorflow',
  face: {
    enabled: true,
    detector: { maxDetected: 10 }
  },
  body: { enabled: false },
  hand: { enabled: false },
  gesture: { enabled: false },
  filter: { enabled: true, width: 2048 },
  cacheSensitivity: 0
}

human.tf.ready().then(human.load()).then(() => {
  fs.readFile('image.gif', (_err, data) => {
    const tensor = human.tf.tidy(() => {
      const decode = human.tf.node.decodeImage(data, 3)
      const expand = human.tf.expandDims(decode, 0)

      return human.tf.cast(expand, 'float32')
    })

    human.detect(tensor, configuration)
  })
})
```

![image](https://github.com/user-attachments/assets/2b11d6a5-8d58-4653-a45b-ccbe51295142)

You'll just need to adjust `'file://../../node_modules/@vladmandic/human/models'` depending on where your models are.

**Comment by vladmandic** [comment]
seems like `tf.node.decodeImage` changed default behavior in recent version of `tfjs-node`.

remove this
> const expand = human.tf.expandDims(decode, 0)

with that, you end up with extra dimension.
without that, your tensor is in a correct shape: 1,1,196,200,3 = batch=1 x height=196 x width=200 x channels=rgb

**Comment by brendon** [comment]
That's interesting. I've had a look at the source code:

https://github.com/tensorflow/tfjs/blob/8fcd129f3c1daaaf503a3c8f0a6697e11e1f2e1b/tfjs-node/src/image.ts#L155-L186

Is it not related to this being a GIF and `decodeImage` returning a 4 element array in that instance (by default since it expands the animations by default)? I'll do some additional testing but I suspect we instead need to tell `decodeImage` to not expand animations and then still `expandDims` to get the right tensor shape.

**Comment by brendon** [comment]
In my testing, simply removing that line didn't account for animated GIF's. This is what seemed to work:

```
const decode = human.tf.node.decodeImage(data, 3, 'int32', false)
const expand = human.tf.expandDims(decode, 0)
```

However, now we can also remove `const expand = human.tf.expandDims(decode, 0)` and it still works. I don't know enough details as to why that is ok :D

**Comment by vladmandic** [comment]
ahh, animated gif - that explains it - each frame gets decoded into batch.
what you just did would result in only first frame being decoded.
or you can decode all and then check if batch dimension exists - if not, then do expanddim conditionally.

**Comment by brendon** [comment]
Indeed :) For the purposes of a single face detection for cropping purposes the first frame works fine. It's an unlikely use case in any regard, just need to stop it from blowing up even if the outcome of cropping a GIF based on the face in the first frame would be weird! :D
