### ISSUE TITLE
Multi Person Pose Tracking in Live Demo

### ISSUE THREAD

**Issue by aihkla** [vladmandic/human#491]
**Issue Description**
Hello, in the human example gallery, I saw that it is able to perform multi body tracking, but in the live demo, I changed the max object to more than 1, faces and other things works, but for pose it is still only tracking one.

Is it the model limitation? Or it is just the live demo not adjusting the parameter?

**Steps to Reproduce**

**Expected Behavior**
Tracking multi person pose.

**Environment**

- Human library version?
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- TensorFlow/JS version (if not using bundled module)?
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)?
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)?
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)?
- Framework (if any) (e.g. *React*, *NextJS*, etc.)?

**Diagnostics**

- Check out any applicable [diagnostic steps](https://github.com/vladmandic/human/wiki/Diag)

**Additional**

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)
- For general questions, create a [discussion topic](https://github.com/vladmandic/human/discussions)

**Comment by vladmandic** [comment]
for body you need to specify multi-person compliant model in config, then max-detected will work.
example:
```js
  config = {
    body: {
      enabled: true,
      maxDetected: 5,
      modelPath: 'https://vladmandic.github.io/human-models/models/movenet-multipose.json' },
    }
  }
```
