### ISSUE TITLE
Hand gesture quality

### ISSUE THREAD

**Issue by ceyxasm** [vladmandic/human#493]
**Issue Description**
My work needs recognition of simple hand gestures like thumbs up, thumbs down and so on. But gestures reported are in the format of `X forward Y up` and I am unable to make sense of what that even means as they are not consistent (see image attached). Also handlandmarks are also erroneous.

![image](https://github.com/user-attachments/assets/bbca0f34-7396-4495-80c7-f4f8e97955b1)
![image](https://github.com/user-attachments/assets/bc207679-d893-4965-8130-6c6928058f5a)
![image](https://github.com/user-attachments/assets/cd239dfb-a4cc-4124-9eb4-e45016bf46ea)

Direction of image in first and third seem to be wrong. While in the case of second image, no results are generated.
Also I am unable to wrap my head around as to what `X forward Y up` means.
Thanks!!

**Comment by vladmandic** [comment]
gestures assume hand orientation is upside.
if you want to have full free gestures, best to train your own model on exact examples. for example, training yolo is not that complicated.
or you could contribute here to do rotation correction before doing hand gesture analysis.
but as it is, hand gestures are nice-to-have and not the key item in this repo.

**Comment by ceyxasm** [comment]
Thank you @vladmandic 
If i get time, in future I would love to contribute.
As of now, I will make do with other approaches.
Regards.
