### ISSUE TITLE
models stats percentageLoaded 0 on initial load

### ISSUE THREAD

**Issue by pgg** [vladmandic/human#494]
**Issue Description**
models stats ```percentageLoaded``` remains 0 on initial load (i.e before models are stored in indexedDB). works fine after models are in indexedDB

**Steps to Reproduce**
```https://stackblitz.com/edit/vitejs-vite-9dzkry?file=app.js```

**Comment by vladmandic** [comment]
nothing to do with indexdb or not, its just that percentageLoaded made had value in older version of Human where models were loaded sequentially.

nowadays, all models are loaded asynchronously with a single await that waits for all promises to resolve/reject. so `percentageLoaded` just from 0 -> 100%.

it would be possible in theory to update global stats from inside each of the individual model loaders, but that's highly intrusive and imo not worth it.

**Comment by pgg** [comment]
why does percentageLoaded show incremental progress then after the models has been cached? fyi numDefinedModels and   numLoadedModels are equal after load, even when one model fails . . .

**Comment by vladmandic** [comment]
fixed in latest dev, will be published shortly.
