### ISSUE TITLE
Face API vs Human emotion/expression classification differs

### ISSUE THREAD

**Issue by motin** [vladmandic/human#496]
**Issue Description**

Face API vs Human emotion classification differs out-of-the-box. Notably, Face API shows "100% Happy" when I smile, while Human has a more bleak interpretation of my facial expression. 

Face API:
<img width="235" alt="image" src="https://github.com/user-attachments/assets/d43265c5-ac2e-4c2b-b283-bc579a86a7da">

Human w FaceMesh enabled:
<img width="206" alt="image" src="https://github.com/user-attachments/assets/27a3745a-4001-4650-a6c0-8213b1406ef0">

Human w/o FaceMesh enabled:
<img width="318" alt="image" src="https://github.com/user-attachments/assets/1f975376-d376-42f6-8f38-f4bd23083f09">

Human does not report "Surprised" either. Seems like different models are used, or that face expression detection support has been dropped in Human compared to Face API.

**Steps to Reproduce**

Try webcam demos side by side:
* https://vladmandic.github.io/face-api/demo/webcam.html
* https://vladmandic.github.io/human/demo/index.html

**Expected Behavior**

Emotion/expression classification results are the same for the same webcam stream.

**Environment**

- Human library version? The one used in the demo
- Built-in demo or custom code? Demo
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? Demo
- TensorFlow/JS version (if not using bundled module)? Demo
- Browser or NodeJS and version (e.g. *NodeJS 14.15* or *Chrome 89*)? Browser, Firefox & Chromium same results
- OS and Hardware platform (e.g. *Windows 10*, *Ubuntu Linux on x64*, *Android 10*)? Mac M1
- Packager (if any) (e.g, *webpack*, *rollup*, *parcel*, *esbuild*, etc.)? Demo
- Framework (if any) (e.g. *React*, *NextJS*, etc.)? Demo

**Possible explanation**

Maybe Human picks up on more subtler clues and acts as a mirror to the soul, indicating that my smile is not representative of my inner emotional state? That would be some real cool tech, but I'd prefer a simpler algorithm that just classified facial expressions at face value :)

**Comment by vladmandic** [comment]
> Face API vs Human emotion classification differs out-of-the-box

hmm - yes, they do - those are different libs. they have NOTHING in common.

> Emotion/expression classification results are the same for the same webcam stream.

i'm really not sure why would this be expected behavior.

**Comment by motin** [comment]
> hmm - yes, they do - those are different libs. they have NOTHING in common.

Of course they do, you! :)
And you specifically say in https://github.com/vladmandic/face-api?tab=readme-ov-file#note that they cover the same use cases, that Face API is superseded by Human. I would expect that while they are built from completely different starting points, they both basically take frames in, moves them through various models and spits out predictions. 

> i'm really not sure why would this be expected behavior

Given the above (mis?)conception, that Human is the preferred library to use in lieu of Face API, it was a bit surprising that the face emotion classification was so useful in Face API but so much less useful in Human. I'd love to use Human, but I am looking for Face expression classification, not Face emotion scoring. 

While not obvious, maybe "HSE-AffectNet" is the model that Face API uses for face expression detection? If so, it ought to be possible to configure Human to use the same model and get the same results.

Thanks for staying curious about the perceptions and usecase ideas of Human.

**Comment by vladmandic** [comment]
`human` already supports HSE-AffectNet, you can switch to it just by saying so in config.
default configuration is selected so its as lightweight as possible while being of sufficient quality for primary use-cases.
i cannot select absolute-best method for every single thing since it would run far slower.
