### ISSUE TITLE
False Positives and False Negatives in Hand Detection & Linking faces with hands.

### ISSUE THREAD

**Issue by ceyxasm** [vladmandic/human#497]
**Issue Description**
Model giving a high number of false positives (minConfidence: 0.75).
Also has a fair share of false negatives.

Human config:
```
const myConfig = {
  modelBasePath: 'file://models/',
  debug: true,
  filter: { enabled: false, equalization: false, flip: false },
  face: {
    enabled: true,
    detector: {
      maxDetected: 100,
      rotation: false,
      skipFrames: 30,
      minConfidence: 0.5
    },
    mesh: {enabled: false},
    attention: {enabled: false},
    iris: {enabled: false},
    description: {enabled: false},
    emotion: {
      enabled: false,
      skipFrames: 30,
    }
  },
  person: {
    enabled: true
  },
  body: { enabled: false },
  hand: { enabled: true, maxDetected: 100, minConfidence: 0.75 },
  gesture: { enabled: false },
  object: { enabled: false },
  segmentation: { enabled: false },
};
```
**Hands are supposed to be in green boxes**
![image](https://github.com/user-attachments/assets/e5a6d3e7-9fbb-4719-9ac5-2a3fb7d9e04f)
![image](https://github.com/user-attachments/assets/e1069628-68d1-4acb-b7c9-e98f7b3ab488)
![image](https://github.com/user-attachments/assets/82c7f2f7-e2b5-4586-a917-fc65e47bd888)

-----------------------------------------------
My second concern is how can I link a particular hand with a particular face (/human).
IDs in result.hand are independent of IDs in result.face

**Comment by vladmandic** [comment]
human's hand module was never intended for this.
you can try using alternative hand detection model (it supports handdetect as alternative in addition to handtrack which is default) which is more reliable, but much slower.

and try with less extreme inputs - use large resolution **square** images where each person is **separate**.
having really skewed aspect ratios and people overlapping by more than 50% is drastically reducing any chance of sane results.

and then you can look at per-person unified results using human.person getter that recombines all different results into per-person view. but for that to work, you also need to have body detection which you've turned off.

**Comment by arvindsaraf** [comment]
Trying to understand @vladmandic - are you saying that if body detection was turned on, the results will be combined into human.person objects - and thus the person's face & hand will be linked? How does that work with body detection on - does one detet the bodies, and do face & hand detection in each of them? Thanks cc: @ceyxasm
