### ISSUE TITLE
wasm streaming compile failed

### ISSUE THREAD

**Issue by cfinfosolutions** [vladmandic/human#504]
<img width="724" alt="image" src="https://github.com/user-attachments/assets/71a0c77e-33ed-4ef6-b681-a08bd11417eb">

when i switch to wasm , console is giving 404 (NOT FOUND) error.

**Comment by vladmandic** [comment]
you're using some packer that is modifying paths - so of course there are no wasm packages there.
place wasm files where you know they are and specify that path in human config.
