### ISSUE TITLE
Cannot use mesh model without enabling iris model

### ISSUE THREAD

**Issue by ost12666** [vladmandic/human#56]
I get an exception when I call warmup("full"). It works if I enabled the iris model.

Unhandled Rejection (TypeError): Cannot read property '0' of undefined
Human.detectFace
src/human.js:310
  307 | 
  308 | // calculate iris distance
  309 | // iris: array[ center, left, top, right, bottom]
> 310 | const irisSize = (face.annotations.leftEyeIris && face.annotations.rightEyeIris)
      | ^  311 |   /* average human iris size is 11.7mm */
  312 |   ? 11.7 * Math.max(Math.abs(face.annotations.leftEyeIris[3][0] - face.annotations.leftEyeIris[1][0]), Math.abs(face.annotations.rightEyeIris[4][1] - face.annotations.rightEyeIris[2][1]))
  313 |   : 0;
View compiled
async
src/human.js:392
  389 |   resolve({ error: 'could not convert input to tensor' });
  390 |   return;
  391 | }
> 392 | this.perf.image = Math.trunc(now() - timeStamp);
      | ^  393 | this.analyze('Get Image:');
  394 | 
  395 | // run face detection followed by all models that rely on face bounding box: face mesh, age, gender, emotion

**Comment by vladmandic** [comment]
fixed via <https://github.com/vladmandic/human/commit/0417058ff99e613d025e72de0d972dc95e89ece7>
