### ISSUE TITLE
createImageBitmap, bitmap.close() safari can't use.

### ISSUE THREAD

**Issue by Jimmysh** [vladmandic/human#58]
**Issue Description**

createImageBitmap,  bitmap.close() safari can't use.
https://github.com/vladmandic/human/blob/77408fc2a72544a4ed880696c48dac467f942af1/src/human.js#L463-L485
[createImageBitmap](https://caniuse.com/?search=createImageBitmap)
[ImageBitmap](https://caniuse.com/?search=ImageBitmap)

Please back to  
https://github.com/vladmandic/human/blob/977f92fa96d3718b7907b3b403910becd184cb52/src/human.js#L425-L465

**Comment by vladmandic** [comment]
fixed via <https://github.com/vladmandic/human/commit/01aeb1cd308744a97cd9b0ce26728a166483ff49#diff-e2a20d78766968135bd0375bd1811a6ae5d7ad35a015b26f5bc2e3239290ab1e>
