### ISSUE TITLE
detect video still back last result.

### ISSUE THREAD

**Issue by Jimmysh** [vladmandic/human#60]
**Issue Description**

enable face feature only
```json
face enabled true
face.mesh false
face.iris false
face.age false
face.gender false
face.emotion false
face.embedding false


```

**Steps to Reproduce**

- Keep the face in the video
- human.detct(video)
- Keep the face out of the video
- human.detct(video)

The result alway is same one.

**Expected Behavior**

Second result without human face

**Environment
- browser
- chrome 86
- 
**Additional**
- 0.9.25

**Comment by vladmandic** [comment]
since invalidation of the detected face happens if mesh cannot be determined, this is correct.
but since having detection only is a valid use-case, i'll add code to handle this.

**Comment by vladmandic** [comment]
fixed via <https://github.com/vladmandic/human/commit/508e7c73cf4cec6254d71c5cebb173eeaf84eef5>
