### ISSUE TITLE
Run demo on nginx ?

### ISSUE THREAD

**Issue by rnehrboss** [vladmandic/human#61]
Can we run the human demo on NGINX?
If so any recommendations?

Thanks

**Comment by vladmandic** [comment]
of course, no reason why not.  
no special recommendations except path to modules must be resolvable (and path to WASM binaries if you use WASM backend).
if unsure, you can always start `npm run dev` which starts built-in web server and monitor incoming HTTP requests and make sure they are handled correctly by NGINX. but again, built-in web server is just there just for help, when people don't have their own web server.

and if you get any exceptions noted in browser inspector, check your server's content-security-policy - I had to relax my locked down server for WASM loading and web workers.

**Comment by rnehrboss** [comment]
Thanks !
