### ISSUE TITLE
how to process a video file

### ISSUE THREAD

**Issue by rnehrboss** [vladmandic/human#62]
great project Vladimir!

Broswer Demo works great on our hardware.

Do you have a suggestion on how to process a video file via a command line?   We would like to sample a video file, checking scores for models each second and outputting to a csv file or something.

Again, nice work!

**Comment by vladmandic** [comment]
**nodejs** does not have built-in video capabilities (in browser, it's handled by browser itself and just exposed via html element), so you'd need a module that can process the video and on-demand output frames as images.  

and such library would likely be a wrapper around a native binary player as decoding video in pure *javascript* inside **nodejs** would be too slow. most libraries around are just wrappers around `ffmpeg` as that is considered most flexible video engine.  
for example, <https://www.npmjs.com/package/fluent-ffmpeg>

**Comment by lghasemzadeh** [comment]
> **nodejs** does not have built-in video capabilities (in browser, it's handled by browser itself and just exposed via html element), so you'd need a module that can process the video and on-demand output frames as images.
> 
> and such library would likely be a wrapper around a native binary player as decoding video in pure _javascript_ inside **nodejs** would be too slow. most libraries around are just wrappers around `ffmpeg` as that is considered most flexible video engine.
> for example, https://www.npmjs.com/package/fluent-ffmpeg

1. so your model just work with real-time stream? we ca not test the model with a previously recorded video?
2. is it also true from the Mediapie? can't we install mediapipe and test it with a video, not live stream.

**Comment by ButzYung** [comment]
I did something similar in my own project. A simple answer: run it on `electron`

**Comment by vladmandic** [comment]
@lghasemzadeh i didn't say it only works with real-time stream, i said it works with any video format (stream or not) supported by underlying platform.  

for `browsers`, they can decode live streams (but not in RTSP format) or video files (MP4, AVI, etc. - again, a lot of formats are supported out of the box, but it depends on codecs pre-installed on OS).  

but `nodejs` does not have built-in video decoder of any kind, so user has to provide it's own.

it's the same with python, it does not have video decoding capabilities of its own, so users use a library such as `OpenCV` and pass frames to detection library.

**Comment by vladmandic** [comment]
closing the issue as the original question is answered.
