### ISSUE TITLE
Path to /@vladmandic/human/models incorrect for /@vladmandic/human/demo/node.js

### ISSUE THREAD

**Issue by meeki007** [vladmandic/human#71]
**Issue Description**
Path to /@vladmandic/human/models incorrect for /@vladmandic/human/demo/node.js

**Steps to Reproduce**
from inside dir /@vladmandic/human/demo run:
```
$ node node.js
```

Output error:
```
UnhandledPromiseRejectionWarning: Error: Path /@vladmandic/human/demo/models/faceboxes.json does not exist: loading failed
    at /@tensorflow/tfjs-node/dist/io/file_system.js:67:23
```

**Expected Behavior**
correct path to models

**Environment
NodeJS: v12.20.2
Ubuntu 20.04 Linux on x64

**FIX - Pull Request
[https://github.com/vladmandic/human/pull/70](https://github.com/vladmandic/human/pull/70)

**Comment by vladmandic** [comment]
nodejs apps are typically run from project root, so this works fine
```
node demo/node.js
```
but this does not
```
cd demo
node node.js
```
i could fix it using it path resolve and require main tricks, but it's just a quick demo, it's not part of the module code. so it will stay as-is.
