### ISSUE TITLE
About blazeface front

### ISSUE THREAD

**Issue by simon-lanf** [vladmandic/human#85]
First off, congrats on shipping version 1 !

I was wondering if I could still use human with blazeface front by providing my own model.

Thank you.

**Comment by vladmandic** [comment]
Thanks!

And yes. I just removed it to reduce overall size, but code for front and back is the same, only inputSize param is different (256 vs 128).

**Comment by simon-lanf** [comment]
Perfect, thank you !

**Comment by vladmandic** [comment]
@simon-lanf may i ask what's the use-case where blazeface-front is better suited than blazeface-back? i found blazeface-back equally good even for large center-faced use-cases, so i removed front variation. but if there is a good use-case, i'll bring it back.

**Comment by simon-lanf** [comment]
Front is just way faster. My use case is with low power hosts.

**Comment by vladmandic** [comment]
ah...purely due to input size, 128x128 is 1/4 of size of 256x256  

model is pretty small, i'll bring it back in but leave it out of configuration documentation so to discourage its usage
