### ISSUE TITLE
Issues with meshRaw and boxRaw in facemesh

### ISSUE THREAD

**Issue by ButzYung** [vladmandic/human#88]
I notice that things have changed in the latest version of `human` regarding `meshRaw` and `boxRaw` in `facemesh.ts`, and this is giving me some headaches because it doesn't work like the way it was, especially `boxRaw`, or more like the bounding box in general. The way you do the bounding box is to clamp it within the input dimension.

```
const box = prediction.box ? [
        Math.max(0, prediction.box.startPoint[0]),
        Math.max(0, prediction.box.startPoint[1]),
        Math.min(input.shape[1], prediction.box.endPoint[0]) - prediction.box.startPoint[0],
        Math.min(input.shape[2], prediction.box.endPoint[1]) - prediction.box.startPoint[1],
      ] : 0;
```

Let's say `startPoint[0]` is negative. The width will still be `prediction.box.endPoint[0] - prediction.box.startPoint[0]`. Wouldn't it effectively "shift" the returned bounding box because `x` is clamped to 0? Isn't it better to just return the bounding box without clamping the values? It will be easy to clamp those on the client side anyways.

I also have questions regarding `input.shape`. I assume `input.shape[1]` is width and `input.shape[2]` is height (judging from `box`), right? If that's the case, it seems the updated meshRaw and boxRaw is wrong with these values as well.

**Comment by vladmandic** [comment]
regarding clamping, i don't want to return out-of-bounds coordinates  
but yes, good point on wrong math - i'll fix that  

regarding input.shape, most TensorFlow models use NHWC format (batch/height/width/color-depth), so input.shape[1] is actual height  

i know, i don't like it as well as everywhere else standard is width/height.

Note that different framework use different formats, for example PyTorch typically uses NCHW. but there is never a strict rule, so it's really up to the each model definition

**Comment by ButzYung** [comment]
I understand that clamped bounds are convenient in most cases, but sometimes the raw value still has its purpose. For example, in my case I need the absolute center of the bounding box. Obviously I need the raw values instead of clamped ones to do the computation. As a suggestion, maybe you can return clamped values as usual in `box` and raw values in `boxRaw`?

**Comment by vladmandic** [comment]
that's a good suggestion

**Comment by vladmandic** [comment]
New version `1.1.9` is published, let me know if this fixes the issue:
- `box` output should be correctly clamped to image size
- `boxRaw` output should be unclamped

This applies to both `face` and `hand` outputs

**Comment by ButzYung** [comment]
Thanks for the quick fix. Things work well so far. `meshRaw` is still different from the old version, but by adjusting its xy aspect ratio from `boxRaw` it becomes the same thing so no big deal, and `meshRaw` is now properly rotated like `mesh` so the new version is actually a bonus.

**Comment by vladmandic** [comment]
> meshRaw is still different from the old version

yes, i considered it broken in the old version :)  
it's a change of behavior, but i did follow semver versioning, this came in a new major version  

closing the issue as resolved
