### ISSUE TITLE
Human: error: cannot set backend: webgl Error: Backend name 'webgl' not found in registry

### ISSUE THREAD

**Issue by MuriloRS** [vladmandic/human#89]
**Issue Description**
I'm trying to verify that the two photos are the same (baixados.jpg) just for test.

![Screenshot_2](https://user-images.githubusercontent.com/18061819/111920580-8659cd80-8a6e-11eb-96ef-1f072143dd3b.png)

But when I run this code it gives me this error:
![Screenshot_1](https://user-images.githubusercontent.com/18061819/111920500-1fd4af80-8a6e-11eb-8b1c-a13fea23dcaf.png)

My package.json

![Screenshot_3](https://user-images.githubusercontent.com/18061819/111920598-9b366100-8a6e-11eb-91aa-425d3e7ded75.png)

What I'm doing wrong? 

**Environment
- Module version? 1.2.1
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)? esm
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Nodejs 14.15.4
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Windows 10

**Comment by vladmandic** [comment]
`webgl` is the default backend for `human`, you should specify you want to use node backend for tensorflow  
just add ```backend: 'tensorflow'``` to your `myConfig ` object.

i'll add extra check so `human` automatically sets default per-platform in the future.

**Comment by MuriloRS** [comment]
> `webgl` is the default backend for `human`, you should specify you want to use node backend for tensorflow
> just add `backend: 'tensorflow'` to your `myConfig ` object.
> 
> i'll add extra check so `human` automatically sets default per-platform in the future.

Worked, thank you so much.
