### ISSUE TITLE
executable

### ISSUE THREAD

**Issue by alphaleadership** [vladmandic/human#93]
you can compile your code in js and exe

**Comment by vladmandic** [comment]
@alphaleadership Is this a request to provide `Human` library in a form of an executable for Windows platform? `Human` is a library, you can create an Electron (<https://www.electronjs.org/>) based project that uses `Human` and compile it. But doing so in the library is not my goal.

**Comment by alphaleadership** [comment]
In a js but non te

**Comment by vladmandic** [comment]
@alphaleadership I have no idea what that means - please explain?

**Comment by alphaleadership** [comment]
transform a typescript code in javascript to easy using

**Comment by vladmandic** [comment]
> transform a typescript code in javascript to easy using

using what? i still have no idea what you mean?  
typescript code is already compiled to javascript bundle
