### ISSUE TITLE
Something went wrong (TypeError: t is not a function)

### ISSUE THREAD

**Issue by Nekronik** [vladmandic/human#95]
**Issue Description**
I was experimenting with this library (awesome by the way) and everything was working fine, but without apparently changing anything it stopped working and I can't find the root cause.

Maybe you could help me.

**Steps to Reproduce**
The issue happens with both `Human.detect` and `Human.warmup`.

This is the full log I get in chrome:
```
Platform browser has already been set. Overwriting the platform with [object Object].
cpu backend was already registered. Reusing existing backend factory.
webgl backend was already registered. Reusing existing backend factory.
14:38:48.315 Human: setting backend: webgl
14:38:48.341 Human: gl version:WebGL 2.0 (OpenGL ES 3.0 Chromium) renderer:WebKit WebGL
14:38:48.342 Human: version: 1.3.4
14:38:48.342 Human: tfjs version: 3.3.0
14:38:48.342 Human: platform: iPhone; CPU iPhone OS 13_2_3 like Mac OS X
14:38:48.342 Human: agent: Mozilla/5.0 AppleWebKit/605.1.15 Version/13.0.3 Mobile/15E148 Safari/604.1
14:38:48.342 Human: setting backend: webgl
14:38:48.342 Human: gl version:WebGL 2.0 (OpenGL ES 3.0 Chromium) renderer:WebKit WebGL
14:38:48.342 Human: configuration: {backend: "webgl", wasmPath: "../assets/", debug: true, async: true, profile: false, …}
14:38:48.342 Human: tf flags: {IS_BROWSER: true, IS_NODE: false, DEBUG: false, WEBGL_VERSION: 2, HAS_WEBGL: true, …}
14:38:48.377 Human: load model: models/blazeface-back
14:38:48.440 Human: load model: models/facemesh
14:38:48.440 Human: tf engine state: 3501876 bytes 231 tensors
Uncaught (in promise) TypeError: t is not a function
    at somecode.js:23
    at somecode.js:23
    at t.scopedRun (somecode.js:23)
    at t.tidy (somecode.js:23)
    at f (somecode.js:23)
    at somecode.js:23
    at t.scopedRun (somecode.js:23)
    at t.runKernelFunc (somecode.js:23)
    at t.runKernel (somecode.js:23)
    at somecode.js:6271
(anonymous) @ somecode.js:23
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.tidy @ somecode.js:23
f @ somecode.js:23
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.runKernelFunc @ somecode.js:23
t.runKernel @ somecode.js:23
(anonymous) @ somecode.js:6271
(anonymous) @ somecode.js:23
(anonymous) @ somecode.js:23
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.tidy @ somecode.js:23
f @ somecode.js:23
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.runKernelFunc @ somecode.js:23
(anonymous) @ somecode.js:23
uE @ somecode.js:6271
fusedConv2d__op @ somecode.js:6259
jne @ somecode.js:10411
(anonymous) @ somecode.js:10411
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.tidy @ somecode.js:23
z$1 @ somecode.js:6264
(anonymous) @ somecode.js:10411
qv @ somecode.js:10411
(anonymous) @ somecode.js:10411
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.tidy @ somecode.js:23
z$1 @ somecode.js:6264
execute @ somecode.js:10411
execute @ somecode.js:10411
predict @ somecode.js:10411
(anonymous) @ somecode.js:10413
(anonymous) @ somecode.js:23
t.scopedRun @ somecode.js:23
t.tidy @ somecode.js:23
z$1 @ somecode.js:6264
getBoundingBoxes @ somecode.js:10413
predict @ somecode.js:10413
estimateFaces @ somecode.js:10413
L2 @ somecode.js:10413
(anonymous) @ somecode.js:11139
async function (async)
(anonymous) @ somecode.js:11139
detect @ somecode.js:11139
(anonymous) @ somecode.js:11139
async function (async)
(anonymous) @ somecode.js:11139
warmup @ somecode.js:11139
warmup @ somecode.js:11346
warmupModels @ somecode.js:11522
```
which I tried to map to this library code and it follows this path:
```ts
faceall.detectFace(this, process.tensor)
  -> const faces = await parent.models.face?.estimateFaces(input, parent.config);
       -> const predictions = await this.facePipeline.predict(input, config);
            -> detector = await this.boundingBoxDetector.getBoundingBoxes(input);
                 -> const [batch, boxes, scores] = tf.tidy(() => {
```

The config I provide:
```ts
const config = {
  backend: 'webgl',
  filter: { enabled: false},
  body: { enabled: false },
  hand: { enabled: false },
  object: { enabled: false },
  gesture: { enabled: true },
  face: {
    enabled: true,
    detector: {
      maxFaces: 2
      // skipFrames: 21
    },
    description: { enabled: false },
    embedding: { enabled: false },
    emotion: { enabled: false },
    gender: { enabled: false },
    iris: { enabled: false },
    age: { enabled: false },
    mesh: {
      enabled: true
      // modelPath:
    }
  }
} as Config;
const human = new Human(config);

export async function warmup(): Promise<void> {
  await human.warmup();
  return;
}
```

**Expected Behavior**
It should work again, but I don't know what is causing the error.

**Environment**

- Module version? 1.3.5
- Built-in demo or custom code?
- Type of module used (e.g. `js`, `esm`, `esm-nobundle`)?
- Browser or NodeJS and version (e.g. NodeJS 14.15 or Chrome 89)? Node v14.16.0, npm 7.8.0, Chrome 89.0.4389.114
- OS and Hardware platform (e.g. Windows 10, Ubuntu Linux on x64, Android 10)? Windows 10
- Packager (if any) (e.g, webpack, rollup, parcel, esbuild, etc.)?

**Additional**

I am running the code in Chrome while emulating an `iPhone 6/7/8 Plus` using the DevTools

Tensor flags:
```json
{
    "IS_BROWSER": true,
    "IS_NODE": false,
    "DEBUG": false,
    "WEBGL_VERSION": 2,
    "HAS_WEBGL": true,
    "PROD": true,
    "CHECK_COMPUTATION_FOR_ERRORS": false,
    "WEBGL_PACK_DEPTHWISECONV": true,
    "TENSORLIKE_CHECK_SHAPE_CONSISTENCY": false,
    "IS_TEST": false,
    "WEBGL_MAX_TEXTURE_SIZE": 16384,
    "WEBGL_PACK": true,
    "WEBGL_FORCE_F16_TEXTURES": false,
    "WEBGL_RENDER_FLOAT32_CAPABLE": true,
    "WEBGL_RENDER_FLOAT32_ENABLED": true,
    "WEBGL_LAZILY_UNPACK": true,
    "WEBGL_PACK_IMAGE_OPERATIONS": true,
    "WEBGL_PACK_BINARY_OPERATIONS": true,
    "WEBGL_CPU_FORWARD": true
}
```

Full config (logged on console):
```json
{
    "backend": "webgl",
    "wasmPath": "../assets/",
    "debug": true,
    "async": true,
    "profile": false,
    "deallocate": false,
    "scoped": false,
    "videoOptimized": false,
    "warmup": "face",
    "filter": {
        "enabled": false,
        "width": 0,
        "height": 0,
        "return": true,
        "brightness": 0,
        "contrast": 0,
        "sharpness": 0,
        "blur": 0,
        "saturation": 0,
        "hue": 0,
        "negative": false,
        "sepia": false,
        "vintage": false,
        "kodachrome": false,
        "technicolor": false,
        "polaroid": false,
        "pixelate": 0
    },
    "gesture": {
        "enabled": true
    },
    "face": {
        "enabled": true,
        "detector": {
            "modelPath": "../models/blazeface-back.json",
            "rotation": false,
            "maxFaces": 2,
            "skipFrames": 21,
            "skipInitial": false,
            "minConfidence": 0.2,
            "iouThreshold": 0.1,
            "scoreThreshold": 0.2,
            "return": false
        },
        "mesh": {
            "enabled": true,
            "modelPath": "../models/facemesh.json"
        },
        "iris": {
            "enabled": false,
            "modelPath": "../models/iris.json"
        },
        "description": {
            "enabled": true,
            "modelPath": "../models/faceres.json",
            "skipFrames": 31
        },
        "emotion": {
            "enabled": false,
            "minConfidence": 0.1,
            "skipFrames": 32,
            "modelPath": "../models/emotion.json"
        },
        "age": {
            "enabled": false,
            "modelPath": "../models/age.json",
            "skipFrames": 33
        },
        "gender": {
            "enabled": false,
            "minConfidence": 0.1,
            "modelPath": "../models/gender.json",
            "skipFrames": 34
        },
        "embedding": {
            "enabled": false,
            "modelPath": "../models/mobileface.json"
        }
    },
    "body": {
        "enabled": false,
        "modelPath": "../models/posenet.json",
        "maxDetections": 10,
        "scoreThreshold": 0.3,
        "nmsRadius": 20
    },
    "hand": {
        "enabled": false,
        "rotation": false,
        "skipFrames": 12,
        "skipInitial": false,
        "minConfidence": 0.1,
        "iouThreshold": 0.1,
        "scoreThreshold": 0.5,
        "maxHands": 1,
        "landmarks": true,
        "detector": {
            "modelPath": "../models/handdetect.json"
        },
        "skeleton": {
            "modelPath": "../models/handskeleton.json"
        }
    },
    "object": {
        "enabled": false,
        "modelPath": "../models/nanodet.json",
        "minConfidence": 0.2,
        "iouThreshold": 0.4,
        "maxResults": 10,
        "skipFrames": 41
    }
}
```

- For installation or startup issues include your `package.json`
- For usage issues, it is recommended to post your code as [gist](https://gist.github.com/)

**Comment by vladmandic** [comment]
I've tried with your config and it works fine on my system.

Error itself is not helpful as it comes from minified code:

> Uncaught (in promise) TypeError: t is not a function
>     at somecode.js:23

However, this indicates that TFJS is being loaded twice  

> Platform browser has already been set. Overwriting the platform with [object Object].
> cpu backend was already registered. Reusing existing backend factory.
> webgl backend was already registered. Reusing existing backend factory.

Likely it's loaded once from your code and once the bundled version within `Human` - and that can cause conflict  

Can you share full import statements from your code?  

Also, can you describe your environment? Your code is TS so you must compile it and likely run through bundler?  

Additionally, you can create non-minified version of Human to get a proper backtrace  
Simply run `npm run dev` and it will run build in non-minified form. Once build is complete (1sec), just CTRL+C to stop web server (if you don't need it)  
Once you want to go back to prod (minified) version of `Human`, simply run `npm run build`

**Comment by Nekronik** [comment]
> I've tried with your config and it works fine on my system.

Yeah, I also tried it on codepen and it seems to work. I've never doubted it was a config input issue.

> However, this indicates that TFJS is being loaded twice

I also have `face-api.js` in the same project. Maybe they are conflicting. I will try to remove it in order to isolate the library.

> Can you share full import statements from your code?

This is how I am importing it:
```ts
import type { Config, Error, Result } from '@vladmandic/human';
import Human from '@vladmandic/human';
```
> Also, can you describe your environment?
Your code is TS so you must compile it and likely run through bundler?

It is inside a [StencilJS ](https://github.com/ionic-team/stencil) project. The bundling is handled by its internals and I am not aware of what they are using now.

**Comment by Nekronik** [comment]
@vladmandic Apparently the other library was conflicting with this one. After removing it this works again, such a silly oversight. Thanks for your help.

I also had a comment related to how the config is provided.
I understand that right now if you want to change the path of the models you need to provide all of them separately even if all the models end up in the same folder (just in a different place). Could it be possible to change this path only once instead of having to change it for all the models?

**Comment by vladmandic** [comment]
> I also have face-api.js in the same project. Maybe they are conflicting. I will try to remove it in order to isolate the library.

Original `face-api.js` is based on TFJS 1.7.0 and not updated since - that is a hard conflict with TFJS 3.3.0 used by `Human`  
Before I started `Human`, I did a project to modernize face-api.js: <https://github.com/vladmandic/face-api>  
I still maintain it, but it's pretty much surpassed in functionality by `Human` nowadays.  

> Could it be possible to change this path only once instead of having to change it for all the models?

That's a a good idea for an enhancement - I'll implement it.

**Comment by Nekronik** [comment]
My plan is to switch from the original `face-api.js` to `Human`, basically, because it is easier to set up, more performant, does more things, and is maintained.

I will report more setup/usability enhancements as I find them.

Again, thanks for your work. :)

**Comment by vladmandic** [comment]
you're welcome!

i've just added config option `modelBasePath` that is used as base path when constructing each individual `modelPath`.  
if any specific `modelPath` is an absolute path, then `modelBasePath` will be ignored for that model.  

new version 1.4 is published
