### ISSUE TITLE
Result type is not matched with returning data

### ISSUE THREAD

**Issue by okeoke85** [vladmandic/human#97]
```
      let baseImageDetection: humanapi.Result = await HumanInstance.detect(baseImage) as humanapi.Result;
      baseImageDetection.face[0].angle //doesnt exists
```

it is under rotation in real data
![image](https://user-images.githubusercontent.com/15729538/114333542-36dc5e00-9b51-11eb-92e0-9b964ac5e492.png)

Thank you for great library, best.

**Comment by vladmandic** [comment]
thanks for the report, it was an oversight on my side  
i've updated the rotation output recently and types were not updated correctly  
(i'm surprised that linter did not flag it up automatically)  

it's been fixed now and will be rolled out in the new version later today

**Comment by okeoke85** [comment]
Linter is frisky time to time :), yes it is fixed, thank you.
